import { useEffect,useRef,useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Bookmark,Download,FileUp,Link,LoaderCircle,RefreshCw,Trash2,X } from 'lucide-react';
import { downloadBlob,downloadRecord,investigationRequest,MAX_FILE_BYTES,modeLabel,readShare,shareLink,verifyInvestigation,type Investigation,type Replay,type SaveDraft } from './contracts';
import { listRecords,removeRecord,storeRecord,type SavedRecord } from './storage';
import './investigations.css';
import {offlineInvestigation} from './offline';

type Props={onSaved?:(record:Investigation)=>void;open:boolean;setOpen:(open:boolean)=>void;draft:SaveDraft|null;onRestore:(record:Investigation)=>void};
export function InvestigationPanel({open,setOpen,draft,onRestore,onSaved}:Props){
  const [records,setRecords]=useState<SavedRecord[]>([]),[active,setActive]=useState<Investigation|null>(null),[incoming,setIncoming]=useState<Replay|null>(null),[title,setTitle]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[link,setLink]=useState('');
  const operation=useRef<AbortController|null>(null),[cancellable,setCancellable]=useState(false);
  const generation=useRef(0),returnFocus=useRef<HTMLElement|null>(null);
  useEffect(()=>{if(open){returnFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;void refresh();}},[open]);
  useEffect(()=>{if(draft){generation.current++;operation.current?.abort();setBusy('');setCancellable(false);setActive(null);setIncoming(null);setTitle(`${modeLabel[draft.recipe.mode]} investigation`);setError('');setNotice('');setLink('');}},[draft]);
  useEffect(()=>{let stopped=false;const load=async()=>{if(!location.hash.startsWith('#investigation='))return;try{const shared=await readShare(location.hash);if(!stopped&&shared){setIncoming(shared);setActive(null);setOpen(true);setNotice('Shared settings are ready. Recalculate to verify the sources and reopen the investigation.');}}catch(e){if(!stopped){setError(message(e));setOpen(true);}}};void load();window.addEventListener('hashchange',load);return()=>{stopped=true;window.removeEventListener('hashchange',load);};},[setOpen]);
  const selected=active?.replay??incoming;
  async function refresh(){try{setRecords(await listRecords());}catch(e){setError(message(e));}}
  useEffect(()=>()=>{generation.current++;operation.current?.abort();},[]);
  function cancel(){generation.current++;operation.current?.abort();setBusy('');setCancellable(false);setNotice('Operation cancelled. Earlier saved records and the current workspace are kept. A server calculation already started may finish within its request limits.');}
  async function run(label:string,action:(signal:AbortSignal,check:()=>void)=>Promise<void>,canCancel=true){
    operation.current?.abort();const controller=new AbortController();operation.current=controller;const g=++generation.current;
    const check=()=>{if(controller.signal.aborted||g!==generation.current)throw new Error('Operation cancelled.');};
    setBusy(label);setCancellable(canCancel);setError('');setNotice('');
    try{await action(controller.signal,check);}catch(e){if(g===generation.current)setError(message(e));}finally{if(g===generation.current){setBusy('');setCancellable(false);}}
  }
  async function save(){if(!draft||!title.trim())return;await run('Calculating saved evidence',async(signal,check)=>{
    const record=await verifyInvestigation(await investigationRequest('capture',{title:title.trim(),...draft},false,signal));check();
    setActive(record);setIncoming(null);setBusy('Writing local record');setCancellable(false);
    await storeRecord(record);check();onSaved?.(record);await refresh();setNotice('Saved on this browser. Download a file to keep a portable backup.');
  });}
  async function reopen(replay:Replay){await run('Recalculating saved results',async(signal,check)=>{
    const record=await verifyInvestigation(await investigationRequest('replay',replay,false,signal));check();
    if(record.result_sha256!==replay.expected_result_sha256||record.replay.expected_recipe_sha256!==replay.expected_recipe_sha256)throw new Error('The replay did not match the requested investigation.');
    setActive(record);onRestore(record);setOpen(false);if(location.hash.startsWith('#investigation='))history.replaceState(null,'',location.pathname+location.search);
  });}
  async function select(record:Investigation){await run('Checking saved record',async(_signal,check)=>{const verified=await verifyInvestigation(record);check();setActive(verified);setIncoming(null);setLink('');});}
  async function importFile(file?:File){if(!file)return;await run('Checking investigation file',async(_signal,check)=>{if(file.size>MAX_FILE_BYTES)throw new Error('Choose an investigation JSON file up to 8 MB.');const record=await verifyInvestigation(JSON.parse(await file.text()));check();setActive(record);setIncoming(null);setLink('');setNotice('File checked. Recalculate online to reopen the workspace, or download the offline viewer for saved values.');});}
  async function keep(){if(!active)return;await run('Writing local record',async()=>{await storeRecord(active);await refresh();setNotice('Saved on this browser.');},false);}
  async function exportFile(format:'zip'|'html'|'csv'){if(!selected)return;await run('Verifying export',async(signal,check)=>{const blob=await investigationRequest('export',{replay:selected,format},true,signal) as Blob;check();downloadBlob(blob,format==='zip'?'ocean-investigation.zip':format==='html'?'ocean-investigation-report.html':'ocean-investigation-values.csv');setNotice('Export verified and downloaded. Keep source attribution with the files.');});}
  async function exportOffline(){if(!active)return;await run('Preparing offline viewer',async(_signal,check)=>{const html=await offlineInvestigation(active);check();downloadBlob(new Blob([html],{type:'text/html'}),'ocean-investigation-offline.html');setNotice('Offline viewer downloaded. It includes saved values and any embedded original import. No network is needed to view it.');});}
  async function copyLink(){if(!selected)return;try{const value=shareLink(selected);setLink(value);try{await navigator.clipboard.writeText(value);setNotice('Replay link copied. Anyone with the link can read its title and analysis settings.');}catch{setNotice('Select and copy the replay link below.');}}catch(e){setError(message(e));}}
  async function remove(id:string){setError('');try{await removeRecord(id);await refresh();setNotice('Local copy removed. Downloaded files and shared links are unchanged.');}catch(e){setError(message(e));}}
  return <Dialog.Root open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="investigation-dialog" onCloseAutoFocus={event=>{event.preventDefault();const target=returnFocus.current;if(target?.isConnected&&target!==document.body&&!target.closest('[role="dialog"]'))target.focus();else document.querySelector<HTMLButtonElement>('[aria-label="Open saved investigations"]')?.focus();}}>
    <div className="investigation-title"><div><span className="eyebrow">REPRODUCIBLE ANALYSIS</span><Dialog.Title>Saved investigations</Dialog.Title></div><Dialog.Close asChild><button className="icon-button" disabled={Boolean(busy)} aria-label="Close saved investigations"><X size={20}/></button></Dialog.Close></div>
    <Dialog.Description>Keep the settings, source versions and calculated evidence together. Reopening recalculates the results before restoring the workspace.</Dialog.Description>
    <div data-tutorial-save-guide/>
    {draft&&!selected&&<form className="investigation-capture" onSubmit={e=>{e.preventDefault();void save();}}><h3>Save this {modeLabel[draft.recipe.mode].toLowerCase()}</h3><label>Investigation name<input aria-label="Investigation name" maxLength={100} required value={title} onChange={e=>setTitle(e.target.value)} disabled={Boolean(busy)}/></label><p>{draft.import_source?'Includes the original uploaded file, column mappings, parsed profiles and results. Saving sends the file to the app service again, then stores the record on this browser. Share a download only if you have permission to share its data.':'Includes the applied analysis settings and selected source values. Camera orbit, unsubmitted drafts and unrelated temporary imports are not included.'}</p><button className="primary-button" disabled={Boolean(busy)||!title.trim()}><Bookmark size={16}/>Save on this browser</button></form>}
    <div className="investigation-import"><label className="secondary-button"><FileUp size={16}/>Open investigation file<input aria-label="Open investigation file" type="file" accept=".json,application/json" disabled={Boolean(busy)} onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></label><span>JSON, up to 8 MB</span></div>
    {busy&&<p className="investigation-notice" role="status"><LoaderCircle className="spin" size={16}/>{busy}…</p>}{busy&&cancellable&&<button className="secondary-button" onClick={cancel}>Cancel operation</button>}{error&&<p className="investigation-error" role="alert">{error}</p>}{notice&&<p className="investigation-notice" role="status">{notice}</p>}
    {selected&&<section className="investigation-selected" aria-label="Selected saved investigation"><span className="eyebrow">{modeLabel[selected.recipe.mode]}</span><h3>{selected.title}</h3><p>{active?`Recorded ${new Date(active.created_at).toLocaleString()} · App ${active.software.app}`:'Shared replay recipe'}<br/>Source case: {selected.recipe.case_id}</p><div className="investigation-actions"><button className="primary-button" disabled={Boolean(busy)} onClick={()=>void reopen(selected)}><RefreshCw size={16}/>Recalculate and reopen</button>{active&&<button className="secondary-button" disabled={Boolean(busy)} onClick={()=>void keep()}>Keep local copy</button>}</div><p>{active&&`Snapshot age: ${Math.max(0,Math.floor((Date.now()-Date.parse(active.created_at))/86400000))} days. `}Sources, methods and numerical fingerprints must match. An unavailable or changed source stops replay and keeps your current workspace.</p>
      <div className="investigation-actions export-actions">{active&&active.results.some(m=>['native_profile','observation_profile','comparison','reference_comparison'].includes(m.module))&&<button className="secondary-button" disabled={Boolean(busy)} onClick={()=>void exportOffline()}>Offline viewer</button>}{active&&<button className="secondary-button" disabled={Boolean(busy)} onClick={()=>downloadRecord(active)}><Download size={15}/>Investigation JSON</button>}<button className="secondary-button" disabled={Boolean(busy)} onClick={()=>void exportFile('html')}>Readable report</button><button className="secondary-button" disabled={Boolean(busy)} onClick={()=>void exportFile('csv')}>Numerical CSV</button><button className="secondary-button" disabled={Boolean(busy)} onClick={()=>void exportFile('zip')}>Complete evidence ZIP</button><button className="secondary-button" disabled={Boolean(busy)||Boolean(selected.import_source)} onClick={()=>void copyLink()}><Link size={15}/>Copy replay link</button></div>
      <p className="investigation-note">Offline viewer supports saved profiles, comparisons and model columns. Its charts and sample values work without the service; new calculations still need the model service. Downloaded copies are removed by deleting their files. {selected.import_source&&'This record includes the original uploaded file. Share through JSON or ZIP, not a replay link. Reopening restores this file as the active imported set. '}The report can be printed to PDF. The ZIP includes the investigation, settings, report, numerical CSV files and sources. Links contain the title and settings, and require the sources to remain available.</p>{link&&<label>Replay link<input aria-label="Replay link" readOnly value={link} onFocus={e=>e.target.select()}/></label>}
      <details><summary>Saved settings and source fingerprints</summary><pre>{JSON.stringify(selected.import_source?{...selected,import_source:{...selected.import_source,content_base64:'Original file embedded in download; hidden here for readability.'}}:selected,null,2)}</pre></details></section>}
    <section className="investigation-library"><h3>On this browser <span>{records.length}</span></h3>{!records.length?<p>No local investigations yet. Use Save investigation in an ocean view, comparison, structure search or checked observation profile.</p>:<ul>{records.map(item=><li key={item.id}><button className="investigation-record" disabled={Boolean(busy)} onClick={()=>void select(item.record)}><strong>{item.record.replay.title}</strong><span>{modeLabel[item.record.replay.recipe.mode]} · {new Date(item.record.created_at).toLocaleDateString()}</span></button><button className="icon-button" disabled={Boolean(busy)} aria-label={`Remove local copy of ${item.record.replay.title}`} onClick={()=>void remove(item.id)}><Trash2 size={16}/></button></li>)}</ul>}</section>
    <p className="investigation-note">Saved locally in this browser, without an account or server database. Clearing site data or browser storage eviction can remove records. Download a backup for another device or long-term keeping. Up to 25 records and 32 MB.</p>
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
function message(error:unknown){return error instanceof Error?error.message:'The investigation could not be opened. Your current workspace has been kept.';}
