import { useEffect, useRef, useState } from 'react';
import { useLearningTool } from '../learning/bridge';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Bookmark, FlaskConical, Info, LoaderCircle, RefreshCw } from 'lucide-react';
import { ApiError, appVersion, getApi } from '../contracts';
import type { SaveDraft } from '../investigations/contracts';
import { latitudeLabel, longitudeLabel } from '../geography';
import { ClimateColourbar, ClimateProfiles, ClimateSection } from './ClimateCharts';
import { climateCaseId, ensoLabel, eventLabel, parseClimateCatalog, postClimate, sameClimateQuery, type ClimateAnalysis, type ClimateCatalog, type ClimateEvent, type ClimateQuery, type ClimateRecipe, type ClimateScale } from './contracts';
import './climate.css';

const initialQuery: ClimateQuery = { event_id: 'son-2015', reference_event_id: 'son-2013', period: 'SON', longitude_index: 70, depth_index: 10 };
const number = (value: number | null, digits = 3) => value === null ? 'Missing' : (value === 0 ? 0 : value).toLocaleString('en-US', { maximumFractionDigits: digits });
const signed = (value: number | null) => value === null ? 'Missing' : `${value > 0 ? '+' : ''}${number(value)}`;
const range = (scale: ClimateScale): [number, number] => [scale.min ?? 0, scale.max ?? 0];
type Props = { active: boolean; restore?: ClimateRecipe; restoredAnalysis?: ClimateAnalysis; onSave: (draft: SaveDraft) => void; onContext: (caseId: string) => void; onOpenCase: (caseId: string, profileId?: string) => void };

function ErrorNotice({ error, retry }: { error: Error; retry: () => void }) {
  const reload = error instanceof ApiError && error.kind !== 'service';
  return <div className="climate-error" role="alert"><p><strong>{reload ? 'The response could not be verified.' : 'The calculation could not finish.'}</strong><br/>{error.message}</p><button className="secondary-button" onClick={reload ? () => window.location.reload() : retry}><RefreshCw size={15}/>{reload ? 'Reload workspace' : 'Try again'}</button></div>;
}

export function ClimateWorkspace({ active, restore, restoredAnalysis, onSave, onContext, onOpenCase }: Props) {
  const [draft, setDraft] = useState<ClimateQuery>(restore?.query ?? initialQuery), [result, setResult] = useState<ClimateAnalysis | null>(restoredAnalysis ?? null);
  const [busy, setBusy] = useState(false), [error, setError] = useState<Error | null>(null), [notice, setNotice] = useState('');
  const [display, setDisplay] = useState<'anomaly' | 'temperature' | 'difference'>('anomaly');
  const controller = useRef<AbortController | null>(null), generation = useRef(0), initialized = useRef(Boolean(restoredAnalysis)), pending = useRef<ClimateQuery>(draft);
  const catalog = useQuery({ queryKey: ['climate-catalog', appVersion], queryFn: ({ signal }) => getApi('/api/climate/catalog', parseClimateCatalog, signal), enabled: active, staleTime: Infinity, gcTime: 600000 });
  useEffect(() => () => { generation.current++; controller.current?.abort(); }, []);
  // Completed background work must not replace another tool's current study case.
  useEffect(() => { if(active&&result)onContext(result.case_id); },[active,result]);
  useEffect(() => { if (active && catalog.data && !initialized.current) { initialized.current = true; const query = restore?.query ?? catalog.data.default_query; setDraft(query); void calculate(query); } }, [active, catalog.data, restore]);
  async function calculate(query: ClimateQuery) {
    controller.current?.abort(); const abort = new AbortController(), current = ++generation.current; controller.current = abort; pending.current = query;
    setBusy(true); setError(null); setNotice('');
    try {
      const analysis = await postClimate(query, abort.signal);
      if (current !== generation.current) return;
      if (catalog.data && analysis.climate_manifest_sha256 !== catalog.data.climate_manifest_sha256) throw new ApiError('The catalogue and analysis have different source versions. Reload the workspace.', undefined, 'response');
      setResult(analysis); setDraft(analysis.query); setNotice('Both historical fields now use the same calendar window, native coordinates and baseline.');
    } catch (error) { if (current !== generation.current) return; if (error instanceof Error && error.name === 'AbortError') setNotice('Calculation cancelled. Your completed comparison is kept.'); else setError(error instanceof Error ? error : new Error('The climate comparison could not finish.')); }
    finally { if (current === generation.current) { setBusy(false); controller.current = null; } }
  }
  const change = <K extends keyof ClimateQuery>(key: K, value: ClimateQuery[K]) => { setDraft(previous => ({ ...previous, [key]: value })); setError(null); };
  function probe(x: number, z: number) { if (result && !busy) { const query = { ...result.query, longitude_index: x, depth_index: z }; setDraft(query); void calculate(query); } }
  const changed = result && !sameClimateQuery(result.query, draft);
  useLearningTool('climate',active,{
    tool:'climate',caseId:result?.case_id??'',status:error||catalog.error?'error':busy||!result?'loading':'ready',title:'Historical climate comparison',kind:'derived',
    facts:[{label:'Selected season',value:result?`${result.events[0].year} ${result.period.label}`:null},{label:'ENSO classification',value:result?ensoLabel(result.events[0]):null},{label:'Potential-temperature anomaly at selected point',value:result?.selected_point.selected.anomaly_c??null,unit:'°C'},{label:'Selected minus reference at same point',value:result?.selected_point.difference_c??null,unit:'°C'},{label:'Depth',value:result?.selected_point.depth_m??null,unit:'m'}],parameters:result?{...result.query}:{},sources:[{label:'Historical fields, indices and baseline',href:'/api/climate/catalog'}],limits:['Anomaly means difference from the same calendar window in the 1991-2020 baseline.','These historical comparisons do not prove causation or predict the next climate event.'],message:error?.message??catalog.error?.message,
  },async command=>{
    if(catalog.error){const retried=await catalog.refetch();if(retried.error)throw retried.error;return false;}
    if(command.action==='inspect')return true;
    if(command.action==='la_nina'||command.action==='el_nino'){
      if(!catalog.data||busy)return false;
      const q:ClimateQuery={...catalog.data.default_query,event_id:command.action==='la_nina'?'son-2022':'son-2015',reference_event_id:'son-2013'};
      if(error||!result||!sameClimateQuery(result.query,q))await calculate(q);return true;
    }
    throw new Error('This climate action is not supported.');
  });
  return <section className="climate-workspace" aria-label="Climate Event Lab">
    <div className="climate-heading"><div><span className="eyebrow">EL NIÑO / LA NIÑA / INDIAN OCEAN DIPOLE</span><h2>Climate Event Lab</h2><p>Compare the same season in three historical years. See how the Pacific water column differed, then inspect the separate Indian Ocean context.</p></div><button className="secondary-button" disabled={!result} onClick={() => result && onSave({ recipe: { mode: 'climate', case_id: result.case_id, query: result.query }, expected_model_sha256: result.model_manifest_sha256, expected_climate_manifest_sha256: result.climate_manifest_sha256 })}><Bookmark size={16}/>Save climate investigation</button></div>
    <div className="climate-scope"><Info size={18}/><p><strong>Historical evidence, with a shared seasonal reference.</strong> The colours below show GODAS potential temperature, its anomaly against the 1991–2020 mean for the same calendar window, or the difference between the selected years. ENSO labels use pinned surface indices. IOD episode labels use the cited agency statements. This is not a climate forecast.</p></div>
    <div className="climate-content"><div className="climate-steps"><span><b>1</b>Choose two historical years</span><span><b>2</b>Inspect the same season at depth</span><span><b>3</b>Check sources and Indian Ocean context</span></div>
      {catalog.isPending && <p className="climate-loading" role="status"><LoaderCircle className="spin" size={17}/>Loading the checked historical catalogue.</p>}
      {catalog.error && <ErrorNotice error={catalog.error} retry={() => void catalog.refetch()}/>}
      {catalog.data && <form className="climate-settings" onSubmit={event => { event.preventDefault(); void calculate(draft); }}>
        <label>Selected event<select aria-label="Selected climate event" value={draft.event_id} disabled={busy} onChange={event => change('event_id', event.target.value as ClimateQuery['event_id'])}>{catalog.data.events.map(event => <option key={event.event_id} value={event.event_id}>{eventLabel(event)}</option>)}</select></label>
        <label>Reference event<select aria-label="Reference climate event" value={draft.reference_event_id} disabled={busy} onChange={event => change('reference_event_id', event.target.value as ClimateQuery['reference_event_id'])}>{catalog.data.events.map(event => <option key={event.event_id} value={event.event_id}>{eventLabel(event)}</option>)}</select></label>
        <label>Same calendar window<select aria-label="Climate calendar window" value={draft.period} disabled={busy} onChange={event => change('period', event.target.value as ClimateQuery['period'])}>{catalog.data.periods.map(period => <option key={period.id} value={period.id}>{period.label}</option>)}</select></label>
        <button className="primary-button" disabled={busy}><FlaskConical size={16}/>{busy ? 'Comparing' : 'Compare historical fields'}</button>
        <p className="climate-note">September, October and November are available in each year. The seasonal view gives each complete monthly mean equal weight. ENSO labels always describe the pinned September–November window, including when you inspect one month.</p>
      </form>}
      {busy && <div className="climate-loading" role="status"><LoaderCircle className="spin" size={17}/><span>Comparing the same source coordinates and calendar window. {result ? 'The completed comparison remains visible with its original labels.' : 'Loading the first checked comparison.'}</span><button className="secondary-button" onClick={() => controller.current?.abort()}>Cancel comparison</button></div>}
      {error && <ErrorNotice error={error} retry={() => void calculate(pending.current)}/>}
      {!busy && notice && <p className="climate-note" role="status">{notice}</p>}
      {changed && result && <p className="climate-applied-note">The controls contain unapplied changes. Charts and saves still describe {eventLabel(result.events[0])} compared with {eventLabel(result.events[1])}, {result.period.label}.</p>}
      {result && <div aria-label="Applied climate comparison">
        <div className="climate-event-cards">{result.events.map((event, index) => <EventCard key={index} event={event} role={index === 0 ? 'Selected' : 'Reference'} onOpen={() => onOpenCase(climateCaseId(event.event_id))}/>)}</div>
        <section className="climate-pacific" aria-label="Pacific climate sections"><div className="climate-section-heading"><div><span className="eyebrow">TROPICAL PACIFIC / BELOW THE SURFACE</span><h3>What changed through the water column?</h3><p>{result.period.label} in {result.events[0].year} and {result.events[1].year}. Both plots use the same scale, longitude positions and actual depth levels.</p></div><label>Show<select aria-label="Climate section quantity" value={display} onChange={event => setDisplay(event.target.value as typeof display)}><option value="anomaly">Anomaly against baseline</option><option value="temperature">Potential temperature</option><option value="difference">Selected minus reference</option></select></label></div>
          <p className="climate-reading-key">{display === 'anomaly' ? 'Blue is cooler and brown is warmer than the 1991–2020 mean for the same calendar window at that depth and location. An ENSO-neutral year can still have a local anomaly.' : display === 'temperature' ? 'Colour shows potential temperature, which accounts for pressure changes relative to the surface. These are monthly model analyses, not raw instrument temperatures.' : 'Blue means the selected year is cooler than the reference year at the same location and depth. Brown means warmer. This difference does not establish a cause.'}</p>
          <ClimateColourbar hasFinite={result.scales.pacific[display].min !== null} range={range(result.scales.pacific[display])} mode={display === 'temperature' ? 'temperature' : 'anomaly'} label={display === 'anomaly' ? 'Both panels: anomaly against 1991–2020 (°C)' : display === 'temperature' ? 'Both panels: potential temperature (°C)' : `${result.events[0].year} minus ${result.events[1].year} (°C)`}/>
          <SectionPanels result={result} basin="pacific" display={display} onSelect={probe}/>
        </section>
        <section className="climate-probe" aria-label="Synchronized climate profiles"><div className="climate-section-heading"><div><h3>Inspect one water column in both years</h3><p>The cursor and profile share exact source coordinates. No vertical interpolation is applied.</p></div></div>
          <div className="climate-probe-controls"><label>Native Pacific longitude<select aria-label="Climate profile longitude" disabled={busy} value={result.query.longitude_index} onChange={event => probe(Number(event.target.value), result.query.depth_index)}>{result.panels[0].pacific.longitude.map((lon, index) => <option key={lon} value={index}>{longitudeLabel(lon, 1)}</option>)}</select></label><label>Native depth<select aria-label="Climate profile depth" disabled={busy} value={result.query.depth_index} onChange={event => probe(result.query.longitude_index, Number(event.target.value))}>{result.panels[0].pacific.depth_m.map((depth, index) => <option key={depth} value={index}>{number(depth, 0)} m</option>)}</select></label><p>{latitudeLabel(result.selected_point.latitude, 3)} · {longitudeLabel(result.selected_point.longitude, 1)}<br/>Original source latitude nearest the equator.</p></div>
          <div className="climate-profile-body"><ClimateProfiles depth={result.panels[0].profile.depth_m} first={result.panels[0].profile.potential_temperature_c} second={result.panels[1].profile.potential_temperature_c} baseline={result.panels[0].profile.baseline_c} labels={[String(result.events[0].year), String(result.events[1].year)]} selectedDepth={result.selected_point.depth_m}/><div className="climate-point-readout" aria-label="Selected climate source values"><h4>At {number(result.selected_point.depth_m, 0)} m</h4><div className="climate-value-table"><table><caption>Potential temperature and anomaly, °C</caption><thead><tr><th>Value</th><th>{result.events[0].year}</th><th>{result.events[1].year}</th></tr></thead><tbody><tr><th>Potential temperature</th><td>{number(result.selected_point.selected.potential_temperature_c)}</td><td>{number(result.selected_point.reference.potential_temperature_c)}</td></tr><tr><th>1991–2020 mean</th><td>{number(result.selected_point.selected.baseline_c)}</td><td>{number(result.selected_point.reference.baseline_c)}</td></tr><tr><th>Anomaly</th><td>{signed(result.selected_point.selected.anomaly_c)}</td><td>{signed(result.selected_point.reference.anomaly_c)}</td></tr></tbody></table></div><p className="climate-difference-value">Selected minus reference<strong>{signed(result.selected_point.difference_c)} °C</strong></p><p className="climate-note">Anomaly subtracts the matching baseline. Difference subtracts the reference year. Missing source or baseline values stay missing. Displayed values are rounded; exports retain calculation precision.</p></div></div>
        </section>
        <section className="climate-indian" aria-label="Separate Indian Ocean context"><span className="eyebrow">SAME DATES / A SEPARATE CLIMATE PATTERN</span><h3>What was happening in the Indian Ocean?</h3><p className="climate-note">The Indian Ocean Dipole compares sea-surface temperature anomalies in two Indian Ocean regions. It is separate from ENSO. The depth sections here supply historical context; comparing two years does not establish that one pattern caused the other.</p><div className="climate-iod-cards">{result.events.map((event, index) => <article key={index}><h4>{event.year}: {event.iod.classification === 'unassigned' ? 'No IOD episode assigned' : `${event.iod.classification === 'positive' ? 'Positive' : 'Negative'} IOD episode documented`}</h4><dl><dt>September–November DMI · ERSSTv6</dt><dd>{signed(event.iod.seasonal_dmi_c)} °C</dd></dl><p>{event.iod.classification_basis}</p><p>{event.iod.episode_timing_note}</p>{catalog.data && <SourceLink catalog={catalog.data} id={event.iod.event_label_source_id}/>}</article>)}</div>
          <details className="climate-indian-sections"><summary>Compare Indian Ocean depth sections for the same dates</summary><p className="climate-note">Same GODAS product, calendar window and 1991–2020 baseline. This section is not the surface DMI index or either index-region average.</p><ClimateColourbar hasFinite={result.scales.indian[display].min !== null} range={range(result.scales.indian[display])} mode={display === 'temperature' ? 'temperature' : 'anomaly'} label={display === 'temperature' ? 'Indian sections: potential temperature (°C)' : display === 'anomaly' ? 'Indian sections: anomaly against 1991–2020 (°C)' : 'Indian section: selected minus reference (°C)'}/><SectionPanels result={result} basin="indian" display={display}/></details>
        </section>
        <section className="climate-observations" aria-label="Climate observation context"><h3>Check the original observations</h3><p className="climate-note">These profiles retain their own positions, dates and source quality flags. A monthly potential-temperature analysis and an instantaneous in-situ profile are different quantities. Opening a profile does not imply independent model validation.</p><div>{result.observations.map((group, index) => <article key={`${group.event_id}-${index}`}><h4>{group.event_id.slice(4)} source profiles</h4>{group.profiles.length ? group.profiles.map(profile => <div className="climate-observation" key={profile.id}><p><strong>{profile.title ?? `Argo ${profile.platform ?? profile.id}`}</strong><br/>{profile.time.slice(0, 10)} · {latitudeLabel(profile.latitude, 3)}, {longitudeLabel(profile.longitude, 3)}</p><button className="secondary-button" onClick={() => onOpenCase(group.case_id, profile.id)}>Inspect source profile <ArrowRight size={14}/></button></div>) : <p className="climate-note">No checked profile is linked to this event. A synthetic observation is not substituted.</p>}</article>)}</div></section>
        {catalog.data && <Methods result={result} catalog={catalog.data}/>}
      </div>}
    </div>
  </section>;
}

function EventCard({ event, role, onOpen }: { event: ClimateEvent; role: string; onOpen: () => void }) { return <article className={`climate-event-card ${role.toLowerCase()}`}><span className="eyebrow">{role.toUpperCase()} HISTORICAL EVENT</span><h3>{event.year} · {ensoLabel(event)}</h3><p>September–November · RONI / ERSSTv6</p><strong>{signed(event.enso.value_c)} °C <small>surface index</small></strong><p className="climate-note">The event label uses the official historical episode and persistence rule, not a single subsurface cell.</p><button className="secondary-button" onClick={onOpen}>Explore this Pacific case <ArrowRight size={14}/></button></article>; }
function SectionPanels({ result, basin, display, onSelect }: { result: ClimateAnalysis; basin: 'pacific' | 'indian'; display: 'temperature' | 'anomaly' | 'difference'; onSelect?: (x: number, z: number) => void }) {
  const selected: [number, number] | undefined = basin === 'pacific' ? [result.query.longitude_index, result.query.depth_index] : undefined;
  const shared = { range: range(result.scales[basin][display]), selected, onSelect };
  if (display === 'difference') { const data = result.difference[basin]; return <ClimateSection {...shared} longitude={data.longitude} depth={data.depth_m} latitude={data.latitude} values={data.values_c} mode="anomaly" quantityLabel="selected minus reference temperature difference" title={`${result.events[0].year} minus ${result.events[1].year}`} subtitle={`${result.period.label}. Signed difference at matching native cells.`}/>; }
  return <div className="climate-section-pair">{result.panels.map((panel, index) => { const data = panel[basin]; return <ClimateSection key={index} {...shared} longitude={data.longitude} depth={data.depth_m} latitude={data.latitude} values={display === 'temperature' ? data.potential_temperature_c : data.anomaly_c} mode={display} title={`${index === 0 ? 'Selected' : 'Reference'}: ${eventLabel(panel.event)}`} subtitle={`${panel.period_start.slice(0, 10)} to ${new Date(Date.parse(panel.period_end_exclusive)-86400000).toISOString().slice(0, 10)}. ${result.period.label}.`}/>; })}</div>;
}
function SourceLink({ catalog, id }: { catalog: ClimateCatalog; id: string | null }) { const source = catalog.index_sources.find(source => source.source_id === id), url = source?.url ?? source?.source_url; return url ? <a href={url} target="_blank" rel="noreferrer">Read the original agency statement</a> : null; }
function Methods({ result, catalog }: { result: ClimateAnalysis; catalog: ClimateCatalog }) { return <details className="climate-methods"><summary>Methods, index versions and source records</summary><h4>Calculation and support</h4><ul>{result.methods.map(method => <li key={method}>{method}</li>)}</ul><h4>ENSO and IOD definitions</h4>{Object.entries(result.index_definitions).map(([id, definition]) => <article key={id}><h5>{String(definition.name ?? id)} · {String(definition.dataset ?? '')}</h5><p>{String(definition.method ?? '')}</p><p>{String(definition.classification ?? definition.interpretation ?? '')}</p><p>{Array.isArray(definition.baseline_period) ? `Baseline: ${definition.baseline_period.join(' to ')}.` : String(definition.baseline_policy ?? '')}</p></article>)}<h4>Versioned historical ONI context</h4><p>These are separate historical indices. They do not replace the RONI values above.</p><div className="climate-value-table"><table><thead><tr><th>Year</th><th>Historical ONI · ERSSTv5</th><th>ONI · ERSSTv6</th></tr></thead><tbody>{result.events.map((event, index) => <tr key={index}><td>{event.year}</td><td>{signed(event.legacy_enso_context.find(item => item.index_id === 'oni_v5')?.value_c ?? null)} °C</td><td>{signed(event.legacy_enso_context.find(item => item.index_id === 'oni_v6')?.value_c ?? null)} °C</td></tr>)}</tbody></table></div><h4>Limits</h4><ul>{result.caveats.map(caveat => <li key={caveat}>{caveat}</li>)}</ul><h4>Original sources</h4><p>Method: <code>{result.method_version}</code><br/>Combined source identity: <code>{result.climate_manifest_sha256}</code></p><ul>{[catalog.field_source, ...catalog.index_sources].map((source, index) => <li key={index}>{source.url || source.source_url ? <a href={source.url ?? source.source_url} target="_blank" rel="noreferrer">{source.title ?? source.name ?? source.source_id ?? 'Original field source'}</a> : source.title ?? source.name ?? 'Field source'}{source.retrieved_at && <span> · retrieved {source.retrieved_at.slice(0, 10)}</span>}</li>)}</ul></details>; }
