import { useId,useMemo,useState } from 'react';
import { Crosshair,Maximize2 } from 'lucide-react';
import { atTime,number,utc,type Bounds,type DriftContext,type DriftQuery,type DriftResult } from './contracts';

type Props={context?:DriftContext;contextUnavailable:boolean;bounds:Bounds;runs:[DriftResult|null,DriftResult|null];elapsed:number;selected:{run:0|1;id:number};onSelect:(run:0|1,id:number)=>void;draft:DriftQuery;drawing:'point'|'release'|'target'|null;firstPoint:[number,number]|null;onPoint:(point:[number,number])=>void;showTrails:boolean};
const colours=['#92e8c9','#f4c08b'];
export function DriftMap({context,contextUnavailable,bounds,runs,elapsed,selected,onSelect,draft,drawing,firstPoint,onPoint,showTrails}:Props){
  const [extent,setExtent]=useState<'case'|'paths'>('paths'),id=useId().replaceAll(':',''),w=820,h=460,L=66,R=24,T=28,B=54;
  const visibleRuns=drawing?[null,null] as Props['runs']:runs;
  const area=useMemo<Bounds>(()=>{
    if(extent==='case'||drawing||!runs[0])return bounds;
    const points=runs.flatMap(r=>r?.particles.flatMap(p=>p.points)??[]),xs=points.map(p=>p.longitude),ys=points.map(p=>p.latitude);
    for(const run of runs){if(run?.query.target_bounds){xs.push(run.query.target_bounds[0],run.query.target_bounds[2]);ys.push(run.query.target_bounds[1],run.query.target_bounds[3]);}}
    const west=Math.min(...xs),east=Math.max(...xs),south=Math.min(...ys),north=Math.max(...ys),cx=(west+east)/2,cy=(south+north)/2,aspect=(w-L-R)/(h-T-B),cos=Math.cos(cy*Math.PI/180);
    let dx=Math.max(.06,east-west)*1.3,dy=Math.max(.06,north-south)*1.3;dx=Math.max(dx,dy*aspect/cos);dy=Math.max(dy,dx*cos/aspect);
    return [Math.max(bounds[0],cx-dx/2),Math.max(bounds[1],cy-dy/2),Math.min(bounds[2],cx+dx/2),Math.min(bounds[3],cy+dy/2)];
  },[extent,runs,bounds,drawing]);
  const [west,south,east,north]=area,cos=Math.cos((south+north)/2*Math.PI/180),availableW=w-L-R,availableH=h-T-B,scale=Math.min(availableW/((east-west)*cos),availableH/(north-south)),pw=(east-west)*cos*scale,ph=(north-south)*scale,x0=L+(availableW-pw)/2,y0=T+(availableH-ph)/2,x=(v:number)=>x0+(v-west)*cos*scale,y=(v:number)=>y0+(north-v)*scale;
  const bg=useMemo(()=>{
    if(!context)return null;const speeds=context.u.map((u,i)=>u===null||context.v[i]===null?null:Math.sqrt(u*u+context.v[i]!**2)),max=Math.max(0,...speeds.filter((v):v is number=>v!==null)),edges=(axis:number[])=>[axis[0],...axis.slice(1).map((v,i)=>(v+axis[i])/2),axis.at(-1)!],xs=edges(context.longitude),ys=edges(context.latitude),paths=new Map<string,string>(),arrows:React.ReactNode[]=[];
    for(let j=0;j<context.latitude.length;j++)for(let i=0;i<context.longitude.length;i++){
      const k=j*context.longitude.length+i,speed=speeds[k],f=max&&speed!==null?speed/max:0,c=speed===null?`url(#${id}-missing)`:`rgb(${Math.round(15+22*f)},${Math.round(39+55*f)},${Math.round(53+53*f)})`,d=`M${x(xs[i])},${y(ys[j+1])}h${x(xs[i+1])-x(xs[i])}v${y(ys[j])-y(ys[j+1])}h-${x(xs[i+1])-x(xs[i])}Z`;paths.set(c,(paths.get(c)??'')+d);
      if(speed&&i%2===0&&j%2===0){const px=x(context.longitude[i]),py=y(context.latitude[j]),u=context.u[k]!,v=context.v[k]!,dx=u/Math.cos(context.latitude[j]*Math.PI/180)*cos,dy=-v,length=Math.sqrt(dx*dx+dy*dy),ax=dx/length*9,ay=dy/length*9;arrows.push(<path key={k} d={`M${px-ax/2},${py-ay/2}l${ax},${ay}m${-ax*.36+ay*.28},${-ay*.36-ax*.28}l${ax*.36-ay*.28},${ay*.36+ax*.28}l${-ax*.36-ay*.28},${-ay*.36+ax*.28}`} stroke="#93b2bd" strokeWidth="1" opacity=".6" fill="none"/>);}
    }return {paths:[...paths],arrows,max};
  },[context,west,south,east,north,id]);
  function box(b:Bounds,colour:string,dashed:boolean,key:string){return <rect key={key} x={x(b[0])} y={y(b[3])} width={x(b[2])-x(b[0])} height={y(b[1])-y(b[3])} fill={colour} fillOpacity=".06" stroke={colour} strokeWidth="1.5" strokeDasharray={dashed?'7 5':undefined}/>;}
  function click(event:React.MouseEvent<SVGSVGElement>){if(!drawing)return;const matrix=event.currentTarget.getScreenCTM();if(!matrix)return;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());if(p.x<x0||p.x>x0+pw||p.y<y0||p.y>y0+ph)return;onPoint([west+(p.x-x0)/scale/cos,north-(p.y-y0)/scale]);}
  const ready=Boolean(runs[0]),backgroundLabel=context?`${number(context.depth_m)} m · ${utc(context.model_time)}`:contextUnavailable?'Current context unavailable':'Current context loading';
  return <div className="drift-visual"><div className="drift-map-top"><div><h3>{drawing?'Choose draft coordinates':ready?'Calculated particle paths':'Choose where to release particles'}</h3><p>{ready&&!drawing?`Run ${selected.run===0?'A':'B'} start-snapshot currents`:'Draft start-snapshot currents'}: {backgroundLabel}</p></div><div className="drift-view-buttons"><button type="button" aria-pressed={extent==='case'} onClick={()=>setExtent('case')}><Maximize2 size={13}/> Study area</button><button type="button" aria-pressed={extent==='paths'} disabled={!ready||Boolean(drawing)} onClick={()=>setExtent('paths')}><Crosshair size={13}/> Fit paths</button></div></div>
    <div className="drift-map-scroll" role="region" aria-label="Drift map, scroll horizontally when needed" tabIndex={0}><svg role="group" aria-label="Drift trajectory map" viewBox={`0 0 ${w} ${h}`} onClick={click}><defs><clipPath id={`${id}-clip`}><rect x={x0} y={y0} width={pw} height={ph}/></clipPath><pattern id={`${id}-missing`} width="8" height="8" patternUnits="userSpaceOnUse"><rect width="8" height="8" fill="#17232f"/><path d="M0 8L8 0" stroke="#4f6570" strokeWidth="1"/></pattern></defs>
      <rect x={x0} y={y0} width={pw} height={ph} fill="#112e3d" stroke="#547786"/>
      <g clipPath={`url(#${id}-clip)`}>{bg?.paths.map(([fill,d])=><path key={fill} d={d} fill={fill}/>)}{bg?.arrows}
        {[0,.25,.5,.75,1].map(t=><g key={t} opacity=".17"><line x1={x0+t*pw} x2={x0+t*pw} y1={y0} y2={y0+ph} stroke="#bdd5de"/><line x1={x0} x2={x0+pw} y1={y0+t*ph} y2={y0+t*ph} stroke="#bdd5de"/></g>)}
        {visibleRuns.map((run,index)=>run&&<g key={index}>{run.query.release.kind==='box'&&box(run.query.release.bounds,colours[index],true,`release-${index}`)}{run.query.target_bounds&&box(run.query.target_bounds,index===0?'#e6d694':'#eaa69b',true,`target-${index}`)}{run.particles.map(p=>{const t=Math.min(elapsed,run.query.duration_hours*3600),point=atTime(p,t),points=p.points.filter(v=>v.elapsed_seconds<=t),chosen=selected.run===index&&selected.id===p.id,stopped=t>=p.stop_elapsed_seconds&&p.status!=='completed',arrived=p.arrival_elapsed_seconds!==null&&p.arrival_elapsed_seconds<=t,path=[...points,point].map(v=>`${x(v.longitude)},${y(v.latitude)}`).join(' ');return <g key={p.id} role="button" tabIndex={chosen?0:-1} aria-label={`Inspect run ${index===0?'A':'B'} particle ${p.id}`} aria-pressed={chosen} onClick={e=>{e.stopPropagation();onSelect(index as 0|1,p.id);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(index as 0|1,p.id);}}}>{showTrails&&<polyline points={path} stroke={colours[index]} strokeOpacity={chosen?1:.48} strokeWidth={chosen?2.8:1.25} strokeDasharray={index===1?'6 4':undefined} fill="none"/>}<path d={`M${x(p.release_longitude)},${y(p.release_latitude)-3}l3 3l-3 3l-3 -3Z`} fill="none" stroke={colours[index]} strokeOpacity=".7"/>{chosen&&<circle cx={x(point.longitude)} cy={y(point.latitude)} r="10" fill="#081e2b" fillOpacity=".8" stroke={colours[index]}/>}<circle cx={x(point.longitude)} cy={y(point.latitude)} r={chosen?5:3.1} fill={colours[index]} stroke={arrived?'#fcf0c1':'#0b2230'} strokeWidth={arrived?2:1}/>{stopped&&<path d={`M${x(point.longitude)-5},${y(point.latitude)-5}l10 10m-10 0l10 -10`} stroke="#f2ac9b" strokeWidth="1.6"/>}</g>;})}</g>)}
        {(!ready||drawing)&&<>{draft.release.kind==='box'?box(draft.release.bounds,'#96dec9',true,'draft-release'):<g><circle cx={x(draft.release.longitude)} cy={y(draft.release.latitude)} r="8" fill="#0b2833" stroke="#a6ecd4" strokeWidth="2"/><path d={`M${x(draft.release.longitude)-13} ${y(draft.release.latitude)}h26m-13 -13v26`} stroke="#a6ecd4"/></g>}{draft.target_bounds&&box(draft.target_bounds,'#e6d694',true,'draft-target')}{firstPoint&&<circle cx={x(firstPoint[0])} cy={y(firstPoint[1])} r="5" fill="#f5dbb2"/>}</>}
      </g>
      {[0,.25,.5,.75,1].map(t=><g key={t}><text className="drift-coordinate" x={x0+t*pw} y={y0+ph+23} textAnchor={t===0?'start':t===1?'end':'middle'}>{number(west+t*(east-west),2)}° E</text><text className="drift-coordinate" x={x0-9} y={y0+t*ph+4} textAnchor="end">{number(north-t*(north-south),2)}° N</text></g>)}<text x={x0+pw/2} y={h-8} textAnchor="middle">Longitude · north is up</text>
    </svg></div>
    <div className="drift-map-legend"><span><i className="drift-key"/>Run A</span>{runs[1]&&<span><i className="drift-key b"/>Run B</span>}<span><i className="drift-key release"/>Release points / box</span>{ready&&!drawing?runs.map((run,i)=>run?.query.target_bounds&&<span key={i}><i className="drift-key target" style={{borderColor:i===0?'#e6d694':'#eaa69b'}}/>Run {i===0?'A':'B'} target box</span>):draft.target_bounds&&<span><i className="drift-key target"/>Draft target box</span>}<span><i className="drift-key stopped"/>Stopped early</span>{runs.some(r=>r?.query.target_bounds)&&<span>Bright marker rim: target reached</span>}</div>
    <p className="drift-map-caption">{ready&&!drawing?'Lines connect calculated output positions. Markers interpolate between them for playback only. A stopped marker stays at its last accepted position.':'Dashed boxes and crosshairs are draft geometry. Calculate a run to see particle movement.'} {bg&&`The subsampled background shows speed from 0 to ${number(bg.max,3)} m/s; brighter means faster. Equal-length arrows show direction at the labelled start snapshot and stay fixed during playback. Hatching marks missing preview samples. Trajectories use the full native grid; a coloured preview cell does not guarantee valid currents everywhere within it.`}<span className="drift-map-hint"> Scroll sideways for the map. Coordinate fields and the particle selector work without map interaction.</span></p>
  </div>;
}
