import { useEffect,useMemo,useRef,useState } from 'react';
import { useLearningTool, modelSource } from '../learning/bridge';
import { useQuery } from '@tanstack/react-query';
import { Bookmark,GitCompareArrows,Info,LoaderCircle,MapPin,Pause,Play,RefreshCw,Square,Waves } from 'lucide-react';
import { ApiError,appVersion,getApi,type CaseManifest } from '../contracts';
import type { SaveDraft } from '../investigations/contracts';
import { DriftMap } from './DriftMap';
import { atTime,defaultDrift,hours,number,same,statusLabels,streamDrift,utc,validDriftQuery,verifyContext,type Bounds,type DriftProgress,type DriftQuery,type DriftRecipe,type DriftResult } from './contracts';
import './drift.css';

type Props={manifest:CaseManifest;active:boolean;restore?:DriftRecipe;restoredRuns?:[DriftResult|null,DriftResult|null];onSave:(draft:SaveDraft)=>void};
type Fields={kind:'point'|'box';coordinates:[string,string,string,string];depth:number;start:number;duration:string;count:string;seed:string;dt:300|600|1200;target:boolean;targetCoordinates:[string,string,string,string]};
function fields(q:DriftQuery,bounds:Bounds):Fields {const [w,s,e,n]=bounds;return {kind:q.release.kind,coordinates:(q.release.kind==='box'?q.release.bounds:[q.release.longitude,q.release.latitude,q.release.longitude,q.release.latitude]).map(String) as Fields['coordinates'],depth:q.depth_index,start:q.start_time_index,duration:String(q.duration_hours),count:String(q.particle_count),seed:String(q.seed),dt:q.dt_seconds,target:Boolean(q.target_bounds),targetCoordinates:(q.target_bounds??[w+.5*(e-w),s+.4*(n-s),w+.7*(e-w),s+.6*(n-s)]).map(String) as Fields['coordinates']};}
function query(f:Fields):DriftQuery{return {release:f.kind==='point'?{kind:'point',longitude:Number(f.coordinates[0]),latitude:Number(f.coordinates[1])}:{kind:'box',bounds:f.coordinates.map(Number) as Bounds},depth_index:f.depth,start_time_index:f.start,duration_hours:Number(f.duration),particle_count:Number(f.count),seed:Number(f.seed),dt_seconds:f.dt,target_bounds:f.target?f.targetCoordinates.map(Number) as Bounds:null};}
export function DriftWorkspace({manifest,active,restore,restoredRuns,onSave}:Props){
  const bounds=manifest.case.bounds,base=`/api/cases/${encodeURIComponent(manifest.case.id)}/drift`,initial=restore?.query??defaultDrift(bounds);
  const [draft,setDraft]=useState(()=>fields(initial,bounds)),[runs,setRuns]=useState<[DriftResult|null,DriftResult|null]>(restoredRuns??[null,null]),[editing,setEditing]=useState<0|1>(0),[busy,setBusy]=useState<0|1|null>(null),[progress,setProgress]=useState<DriftProgress|null>(null),[error,setError]=useState<Error|null>(null),[notice,setNotice]=useState(''),[drawing,setDrawing]=useState<'point'|'release'|'target'|null>(null),[firstPoint,setFirstPoint]=useState<[number,number]|null>(null),[selected,setSelected]=useState<{run:0|1;id:number}>({run:0,id:1}),[elapsed,setElapsed]=useState(restoredRuns?.[0]?.query.duration_hours?restoredRuns[0].query.duration_hours*3600:0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(4),[trails,setTrails]=useState(true),[reducedMotion,setReducedMotion]=useState(false);
  const abortRef=useRef<AbortController|null>(null),generation=useRef(0),elapsedRef=useRef(elapsed),restoreStarted=useRef(false),draftQuery=useMemo(()=>query(draft),[draft]),longest=Math.max(...runs.map(r=>(r?.query.duration_hours??0)*3600)),chosenRun=runs[selected.run]??runs[0],particle=chosenRun?.particles.find(p=>p.id===selected.id)??chosenRun?.particles[0],currentPoint=particle?atTime(particle,elapsed):undefined,changed=Boolean(runs[editing]&&!same(runs[editing]!.query,draftQuery)),availableHours=(Date.parse(manifest.coordinates.times.at(-1)!)-Date.parse(manifest.coordinates.times[draft.start]))/3600000;
  const context=useQuery({queryKey:['drift-context',appVersion,manifest.case.id,draft.depth,draft.start],queryFn:({signal})=>getApi(`${base}/context?depth_index=${draft.depth}&time_index=${draft.start}`,v=>verifyContext(v,manifest,draft.depth,draft.start),signal),enabled:active,staleTime:Infinity,gcTime:600000});
  useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>{setReducedMotion(media.matches);if(media.matches)setPlaying(false);};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
  useEffect(()=>()=>{generation.current++;abortRef.current?.abort();},[]);
  useEffect(()=>{if(!active)setPlaying(false);},[active]);
  useEffect(()=>{elapsedRef.current=elapsed;},[elapsed]);
  useEffect(()=>{if(!playing||!active||!longest)return;let frame=0,previous=performance.now();const tick=(now:number)=>{const next=Math.min(longest,elapsedRef.current+(now-previous)/1000*3600*speed);previous=now;elapsedRef.current=next;setElapsed(next);if(next>=longest)setPlaying(false);else frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,active,longest,speed]);
  useEffect(()=>{if(active&&restore&&!restoredRuns?.[0]&&!restoreStarted.current){restoreStarted.current=true;void calculate(restore.query,0).then(result=>{if(result&&restore.comparison)void calculate(restore.comparison,1);});}},[active,restore,restoredRuns]);
  function update<K extends keyof Fields>(key:K,value:Fields[K]){setDraft(f=>({...f,[key]:value}));setError(null);}
  function coordinate(index:number,value:string,target=false){setDraft(f=>{const key=target?'targetCoordinates':'coordinates',a=[...f[key]] as Fields['coordinates'];a[index]=value;return {...f,[key]:a};});setError(null);}
  function chooseEditor(slot:0|1){setEditing(slot);if(runs[slot])setDraft(fields(runs[slot]!.query,bounds));else if(runs[0])setDraft(fields(runs[0]!.query,bounds));setDrawing(null);setFirstPoint(null);setError(null);setNotice(slot===1&&!runs[1]?'Change the release, start time or another setting, then calculate run B. Run A remains visible.':'');}
  function validate(){const q=draftQuery,inside=(lon:number,lat:number)=>lon>=bounds[0]&&lon<=bounds[2]&&lat>=bounds[1]&&lat<=bounds[3];if(![draft.duration,draft.count,draft.seed,...draft.coordinates.slice(0,draft.kind==='point'?2:4),...(draft.target?draft.targetCoordinates:[])].every(s=>s.trim())||!validDriftQuery(q))return 'Choose a valid release, 1 to 64 particles, 1 to 72 whole hours and an integer seed from 0 to 2147483647. Box coordinates must increase from west to east and south to north.';if(q.release.kind==='point'?!inside(q.release.longitude,q.release.latitude):!inside(q.release.bounds[0],q.release.bounds[1])||!inside(q.release.bounds[2],q.release.bounds[3]))return 'Keep the release inside the checked study area.';if(q.target_bounds&&(!inside(q.target_bounds[0],q.target_bounds[1])||!inside(q.target_bounds[2],q.target_bounds[3])))return 'Keep the target box inside the checked study area.';if(q.duration_hours>availableHours)return `Only ${availableHours} hours of forcing remain after this start. Shorten the duration or choose an earlier start; the run will not be silently shortened.`;if(editing===1&&same(q,runs[0]?.query))return 'Change at least one setting for run B so the two runs describe different experiments.';return null;}
  async function calculate(q:DriftQuery,slot:0|1){const controller=new AbortController(),g=++generation.current;abortRef.current?.abort();abortRef.current=controller;setBusy(slot);setProgress(null);setError(null);setNotice('');setDrawing(null);setPlaying(false);try{const result=await streamDrift(`${base}/stream`,q,manifest,controller.signal,p=>{if(g===generation.current)setProgress(p);});if(g!==generation.current)return;setRuns(old=>slot===0?[result,old[1]&&same(old[1].query,q)?null:old[1]]:[old[0],result]);setSelected({run:slot,id:1});setElapsed(Math.max(result.query.duration_hours*3600,(runs[slot===0?1:0]?.query.duration_hours??0)*3600));setNotice(`Run ${slot===0?'A':'B'} is complete. Playback shows calculated historical trajectories.`);return result;}catch(e){if(g!==generation.current)return;if(e instanceof Error&&e.name==='AbortError')setNotice('Calculation cancelled. Completed runs are kept; no partial run was saved.');else setError(e instanceof Error?e:new Error('The calculation could not finish.'));}finally{if(g===generation.current){setBusy(null);setProgress(null);abortRef.current=null;}}}
  function submit(e:React.FormEvent){e.preventDefault();const problem=validate();if(problem){setError(new Error(problem));return;}void calculate(draftQuery,editing);}
  function cancel(){abortRef.current?.abort();generation.current++;setBusy(null);setProgress(null);setNotice('Calculation cancelled. Completed runs are kept; no partial run was saved.');}
  function startDrawing(mode:'point'|'release'|'target'){setDrawing(drawing===mode?null:mode);setFirstPoint(null);setPlaying(false);}
  function point(p:[number,number]){if(drawing==='point'){update('coordinates',[String(p[0]),String(p[1]),String(p[0]),String(p[1])]);setDrawing(null);return;}if(!firstPoint){setFirstPoint(p);return;}const b=[Math.min(firstPoint[0],p[0]),Math.min(firstPoint[1],p[1]),Math.max(firstPoint[0],p[0]),Math.max(firstPoint[1],p[1])];if(b[0]===b[2]||b[1]===b[3]){setError(new Error('Choose a different second corner to give the box a width and height.'));return;}update(drawing==='target'?'targetCoordinates':'coordinates',b.map(String) as Fields['coordinates']);setDrawing(null);setFirstPoint(null);}
  function save(){if(!runs[0])return;onSave({recipe:{mode:'drift',case_id:manifest.case.id,query:runs[0].query,comparison:runs[1]?.query??null},expected_model_sha256:runs[0].manifest_sha256});}
  const usableDraft=validDriftQuery(draftQuery)?draftQuery:initial,shownContext=drawing||!runs[0]?context.data:chosenRun?.background,reload=error instanceof ApiError&&error.kind!=='service';
  useLearningTool('drift',active,{
    tool:'drift',caseId:manifest.case.id,status:error?'error':busy!==null?'loading':runs[0]?'ready':'empty',title:'Calculated particle paths',kind:'simulation',
    facts:[{label:'Released particles',value:runs[0]?.summary.released??null},{label:'Duration',value:runs[0]?.query.duration_hours??null,unit:'hours'},{label:'Mean accepted travel distance',value:runs[0]?.summary.mean_distance_km??null,unit:'km'},{label:'Release time (UTC)',value:runs[0]?.start_time??null}],parameters:{depth_index:runs[0]?.query.depth_index??draft.depth,particle_count:runs[0]?.query.particle_count??Number(draft.count),seed:runs[0]?.query.seed??Number(draft.seed),duration_hours:runs[0]?.query.duration_hours??Number(draft.duration)},
    sources:[modelSource(manifest.case.id),{label:'Drift method and API',href:'/api/docs#/'}],limits:['Passive particles follow historical horizontal model currents at a fixed depth.','No windage, sinking or diffusion. This is not a rescue forecast or a probability.'],message:error?.message,
  },async(command,signal)=>{
    if(command.action==='run'){
      const q={...defaultDrift(bounds),particle_count:8,duration_hours:6};setDraft(fields(q,bounds));setEditing(0);
      signal.addEventListener('abort',cancel,{once:true});
      try{const result=await calculate(q,0);if(!result)throw new Error('The particle calculation did not produce a completed result.');return true;}finally{signal.removeEventListener('abort',cancel);}
    }
    if(command.action==='play'){
      if(!runs[0])return false;
      if(reducedMotion){setElapsed(longest);return true;}
      elapsedRef.current=0;setElapsed(0);setSpeed(4);setPlaying(true);signal.addEventListener('abort',()=>setPlaying(false),{once:true});return true;
    }
    if(command.action==='inspect')return true;
    throw new Error('This Drift action is not supported.');
  });
  return <section className="drift-workspace" aria-label="Drift Lab"><header className="drift-heading"><div><span className="eyebrow">DRIFT LAB / HISTORICAL PASSIVE TRACERS</span><h2>Where do these currents carry a particle?</h2><p>Choose a release, calculate the paths, then press Play.</p></div><button className="secondary-button" disabled={!runs[0]||busy!==null} onClick={save}><Bookmark size={16}/>Save drift experiment</button></header><div className="drift-scope"><Info size={18}/><p>Fixed-depth passive tracers in historical currents. No sinking, windage, diffusion or swimming. Not a rescue forecast or arrival probability.</p></div>
    <div className="drift-content"><div className="drift-steps"><span><b>1</b>Choose the release</span><span><b>2</b>Calculate and play</span><span><b>3</b>Compare and save</span></div>
      {runs[0]&&<div className="drift-result-header"><div className="drift-actions"><label>Settings for<select aria-label="Drift settings for run" value={editing} disabled={busy!==null} onChange={e=>chooseEditor(Number(e.target.value) as 0|1)}><option value="0">Run A</option><option value="1">Comparison B</option></select></label><button className="secondary-button" disabled={busy!==null} onClick={()=>chooseEditor(1)}><GitCompareArrows size={16}/>Compare another release</button>{runs[1]&&<button className="secondary-button" disabled={busy!==null} onClick={()=>{setRuns(old=>[old[0],null]);setSelected({run:0,id:1});chooseEditor(0);}}>Remove run B</button>}</div><span>Only completed, applied settings are saved.</span></div>}
      <div className="drift-main-layout"><form className="drift-setup" aria-label="Drift release settings" onSubmit={submit}>
        <label>Release geometry<select aria-label="Drift release geometry" value={draft.kind} disabled={busy!==null} onChange={e=>{const kind=e.target.value as Fields['kind'];if(kind==='box'&&draft.coordinates[0]===draft.coordinates[2])setDraft(f=>({...fields(defaultDrift(bounds),bounds),depth:f.depth,start:f.start,duration:f.duration,count:f.count,seed:f.seed,dt:f.dt,target:f.target,targetCoordinates:f.targetCoordinates}));else update('kind',kind);setDrawing(null);}}><option value="box">Box of particles</option><option value="point">Single location</option></select></label>
        <label>Particles<input aria-label="Drift particle count" type="number" min="1" max="64" step="1" value={draft.count} disabled={busy!==null} onChange={e=>update('count',e.target.value)} required/></label>
        <label>Fixed native depth<select aria-label="Drift depth" value={draft.depth} disabled={busy!==null} onChange={e=>update('depth',Number(e.target.value))}>{manifest.coordinates.depth_m.map((d,i)=>d<=1000&&i<=32?<option key={d} value={i}>{number(d)} m</option>:null)}</select></label>
        <label>Duration (hours)<input aria-label="Drift duration hours" type="number" min="1" max="72" step="1" value={draft.duration} disabled={busy!==null} onChange={e=>update('duration',e.target.value)} required/></label>
        <label className="drift-start">Starting snapshot (UTC)<select aria-label="Drift start snapshot" value={draft.start} disabled={busy!==null} onChange={e=>update('start',Number(e.target.value))}>{manifest.coordinates.times.map((t,i)=><option key={t} value={i}>{utc(t)}</option>)}</select></label>
        <p className="drift-note">{availableHours} hours remain after this start. The model ends at {utc(manifest.coordinates.times.at(-1)!)}. A longer request is rejected.</p>
        <details className="drift-location"><summary>Release coordinates</summary><fieldset className="drift-release-fields"><legend>{draft.kind==='box'?'Release box coordinates':'Release point coordinates'}</legend>{(draft.kind==='point'?['Longitude (° E)','Latitude (° N)']:['West (° E)','South (° N)','East (° E)','North (° N)']).map((label,i)=><label key={i}>{label}<input aria-label={`Drift release ${draft.kind==='point'?['longitude','latitude'][i]:['west','south','east','north'][i]}`} type="number" step="any" min={bounds[i%2]} max={bounds[i%2+2]} disabled={busy!==null} value={draft.coordinates[i]} onChange={e=>coordinate(i,e.target.value)} required/></label>)}{draft.kind==='point'&&Number(draft.count)>1&&<p className="drift-note">Identical particles at one point follow the same path. Overlapping markers are intentional. Use a box release to inspect spatial spread.</p>}</fieldset></details><div className="drift-map-action"><div className="drift-actions"><button type="button" className="secondary-button" disabled={busy!==null} aria-pressed={drawing!==null&&drawing!=='target'} onClick={()=>startDrawing(draft.kind==='point'?'point':'release')}><MapPin size={15}/>{drawing&&drawing!=='target'?'Cancel drawing':draft.kind==='point'?'Place release on map':'Draw release box'}</button></div></div>
        <details className="drift-advanced"><summary>Target box and numerical settings</summary><label className="drift-check"><input aria-label="Enable drift target box" type="checkbox" checked={draft.target} disabled={busy!==null} onChange={e=>{update('target',e.target.checked);setDrawing(null);}}/>Count arrivals in a target box</label>{draft.target&&<fieldset className="drift-target-fields"><legend>Target coordinates</legend>{['West (° E)','South (° N)','East (° E)','North (° N)'].map((label,i)=><label key={i}>{label}<input aria-label={`Drift target ${['west','south','east','north'][i]}`} type="number" step="any" min={bounds[i%2]} max={bounds[i%2+2]} value={draft.targetCoordinates[i]} disabled={busy!==null} onChange={e=>coordinate(i,e.target.value,true)} required/></label>)}<button type="button" className="secondary-button" disabled={busy!==null} aria-pressed={drawing==='target'} onClick={()=>startDrawing('target')}><MapPin size={15}/>{drawing==='target'?'Cancel target drawing':'Draw target box'}</button></fieldset>}<div className="drift-advanced-grid"><label>Release seed<input aria-label="Drift release seed" type="number" min="0" max="2147483647" step="1" value={draft.seed} disabled={busy!==null} onChange={e=>update('seed',e.target.value)} required/></label><label>Integration step<select aria-label="Drift integration step" value={draft.dt} disabled={busy!==null} onChange={e=>update('dt',Number(e.target.value) as Fields['dt'])}><option value="300">5 minutes</option><option value="600">10 minutes</option><option value="1200">20 minutes</option></select></label></div><p className="drift-note">The seed controls uniform longitude/latitude release positions within a box. It does not add random motion. Smaller numerical steps can change results; the forcing snapshots remain 12 hours apart.</p></details>
        <div className="drift-actions"><button className="primary-button" disabled={busy!==null} type="submit">{busy!==null?<LoaderCircle size={16} className="spin"/>:<Waves size={16}/>}Calculate run {editing===0?'A':'B'}</button></div>
      </form>
      <div className="drift-stage">{!runs[0]&&<div className="drift-empty"><h3>Your release is ready to inspect</h3><p>Start with 24 particles over 24 hours, or adjust the release. Calculate run A to see the paths.</p></div>}
        {drawing&&<p className="drift-warning" role="status">{drawing==='point'?'Click one point on the map.':firstPoint?'Choose the opposite corner to finish the draft box.':'Choose two opposite corners on the map.'} Coordinate fields provide a keyboard alternative. Previously calculated paths return when drawing finishes.</p>}
        {changed&&<p className="drift-warning" role="status">Controls differ from applied run {editing===0?'A':'B'}. Calculate to apply them. The displayed trajectories and saved experiment still use their completed settings.</p>}
        {busy!==null&&<div className="drift-progress" role="status"><span>Calculating run {busy===0?'A':'B'}{progress?`: ${progress.completed_steps} of ${progress.total_steps} integration steps`:': preparing verified current fields'}<br/><small>Progress counts finished solver steps. No partial trajectories are displayed or saved.</small></span><button className="secondary-button" onClick={cancel}><Square size={14}/>Cancel calculation</button>{progress&&<progress aria-label="Drift calculation progress" value={progress.completed_steps} max={progress.total_steps}/>}</div>}
        {notice&&<p className="drift-note" role="status">{notice}</p>}{error&&<div className="drift-error" role="alert"><p>{error.message}</p>{reload&&<button className="secondary-button" onClick={()=>location.reload()}><RefreshCw size={15}/>Reload workspace</button>}</div>}
        {context.error&&(drawing||!runs[0])&&<div className="drift-error" role="alert"><p>{context.error.message}</p><button className="secondary-button" onClick={()=>void context.refetch()}><RefreshCw size={15}/>Retry current context</button></div>}
        <DriftMap context={shownContext} contextUnavailable={Boolean(context.error&&(drawing||!runs[0]))} bounds={bounds} runs={runs} elapsed={elapsed} selected={selected} onSelect={(run,id)=>setSelected({run,id})} draft={usableDraft} drawing={drawing} firstPoint={firstPoint} onPoint={point} showTrails={trails}/>
        {runs[0]&&<div className="drift-playback" aria-label="Drift playback controls"><button className="secondary-button" onClick={()=>{if(!playing&&elapsed>=longest){elapsedRef.current=0;setElapsed(0);}setPlaying(p=>!p);}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause paths':'Play paths'}</button><label>Elapsed simulation time<input aria-label="Drift elapsed time" type="range" min="0" max={longest} step="60" value={Math.round(elapsed)} onChange={e=>{setPlaying(false);setElapsed(Number(e.target.value));}}/></label><div className="drift-time" aria-label="Drift elapsed readout">{hours(elapsed)} after release<small>Compared runs share elapsed time, not necessarily calendar time.</small></div><label>Playback speed<select aria-label="Drift playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="1">1 hour / second</option><option value="4">4 hours / second</option><option value="8">8 hours / second</option></select></label><label className="drift-check"><input aria-label="Show drift trails" type="checkbox" checked={trails} onChange={e=>setTrails(e.target.checked)}/>Show calculated trails</label><p className="drift-note">Animation starts only when you press Play. {reducedMotion?'Reduced motion is enabled. Use the time slider for still views. ':''}Positions between saved outputs use visual interpolation; numerical arrivals use accepted solver steps.</p></div>}
      </div></div>
      {runs[0]&&<><div className="drift-run-cards" aria-label="Applied drift runs">{runs.map((run,index)=>run&&<RunCard key={index} result={run} index={index}/>)}</div>{runs[1]&&<p className="drift-note">Comparison describes the two chosen experiments. Different release counts, depths, targets or durations can affect the totals. Neither track set is an observation-based forecast validation.</p>}
      {chosenRun&&particle&&currentPoint&&<section className="drift-particle-card" aria-label="Drift particle inspector"><h3>Inspect a calculated particle</h3><div className="drift-advanced-grid"><label>Run<select aria-label="Inspect drift run" value={selected.run} onChange={e=>setSelected({run:Number(e.target.value) as 0|1,id:1})}><option value="0">Run A</option>{runs[1]&&<option value="1">Run B</option>}</select></label><label>Particle<select aria-label="Inspect drift particle" value={particle.id} onChange={e=>setSelected(s=>({...s,id:Number(e.target.value)}))}>{chosenRun.particles.map(p=><option key={p.id} value={p.id}>Particle {p.id}: {statusLabels[p.status]}</option>)}</select></label></div><dl className="drift-facts"><div><dt>Displayed position</dt><dd>{number(currentPoint.longitude,6)}° E, {number(currentPoint.latitude,6)}° N</dd></div><div><dt>Displayed model time</dt><dd>{utc(new Date(Date.parse(chosenRun.start_time)+currentPoint.elapsed_seconds*1000).toISOString().replace('.000Z','Z'))}{currentPoint.elapsed_seconds<elapsed?' (last available particle position)':''}</dd></div><div><dt>Final status</dt><dd>{statusLabels[particle.status]}{particle.stop_reason?`. ${particle.stop_reason}`:''}</dd></div><div><dt>Accepted path distance</dt><dd>{number(particle.distance_km,6)} km over {hours(particle.stop_elapsed_seconds)}</dd></div><div><dt>First target arrival</dt><dd>{chosenRun.query.target_bounds?hours(particle.arrival_elapsed_seconds):'No target selected'}</dd></div></dl></section>}
      <details className="drift-table-details"><summary>Inspect every particle and stopping reason</summary><p className="drift-note">Scroll the table sideways when needed. Counts include invalid releases. Distances are sums along accepted numerical steps.</p><div className="drift-table-scroll" tabIndex={0} role="region" aria-label="Drift particle results table"><table><thead><tr><th>Run / particle</th><th>Release (° E, ° N)</th><th>Final status</th><th>Accepted duration</th><th>Distance (km)</th><th>First target arrival</th></tr></thead><tbody>{runs.flatMap((run,index)=>run?.particles.map(p=><tr key={`${index}-${p.id}`} aria-selected={selected.run===index&&selected.id===p.id}><td><button onClick={()=>setSelected({run:index as 0|1,id:p.id})}>Run {index===0?'A':'B'} / {p.id}</button></td><td>{number(p.release_longitude,6)}, {number(p.release_latitude,6)}</td><td>{statusLabels[p.status]}{p.stop_reason&&<><br/>{p.stop_reason}</>}</td><td>{hours(p.stop_elapsed_seconds)}</td><td>{number(p.distance_km,6)}</td><td>{run.query.target_bounds?hours(p.arrival_elapsed_seconds):'No target'}</td></tr>)??[])}</tbody></table></div></details>
      <details className="drift-methods"><summary>Scientific method, boundaries and source identity</summary><h3>How movement is calculated</h3><ul>{runs[0].methods.map(m=><li key={m}>{m}</li>)}</ul><h3>What this experiment cannot establish</h3><ul>{runs[0].limitations.map(m=><li key={m}>{m}</li>)}</ul><p>Source case: {runs[0].case_id}<br/>Method: {runs[0].method_version}<br/>Model manifest SHA-256: <code>{runs[0].manifest_sha256}</code></p><p>Saving keeps completed run A and any completed run B, including the seed, numerical step, trajectories and stopping reasons. Draft edits and playback position are excluded. Cancelled requests do not create a saved investigation.</p></details></>}
    </div>
  </section>;
}
function RunCard({result:r,index}:{result:DriftResult;index:number}){const s=r.summary;return <section className={`drift-run-card ${index===1?'run-b':''}`} aria-label={`Applied drift run ${index===0?'A':'B'}`}><h3>Run {index===0?'A':'B'} · {r.query.particle_count} simulated particles</h3><p>{utc(r.start_time)} to {utc(r.end_time)}<br/>{number(r.depth_m)} m fixed depth · {r.query.duration_hours} hours · {r.query.dt_seconds/60}-minute integration step</p><p>{r.query.release.kind==='point'?`Point: ${number(r.query.release.longitude,5)}° E, ${number(r.query.release.latitude,5)}° N`:`Release box: ${r.query.release.bounds.map(n=>number(n,5)).join(', ')} (west, south, east, north)`}<br/>Seed: {r.query.seed}; saved output every {r.output_interval_seconds/60} minutes</p><div className="drift-arrival">{r.query.target_bounds?<><strong>{s.arrived} of {s.released} released particles reached the target</strong>{number((s.arrival_fraction??0)*100,2)}% of requested particles, including invalid releases in the denominator.<br/>First arrival: {hours(s.earliest_arrival_seconds)} · last first-arrival: {hours(s.latest_arrival_seconds)}<br/>Target: {r.query.target_bounds.map(n=>number(n,5)).join(', ')} (west, south, east, north)</>:<><strong>No arrival target selected</strong>Enable a target box before calculating to count simulated arrivals.</>}</div><div className="drift-status-list">{(Object.keys(statusLabels) as (keyof typeof statusLabels)[]).map(status=><span key={status}>{s[status]} {statusLabels[status].toLowerCase()}</span>)}</div><p>Mean accepted distance: {number(s.mean_distance_km,3)} km across {s.valid_releases} valid releases. This is accumulated travel distance, not straight-line displacement.</p></section>;}
