import { useEffect, useMemo, useRef, useState } from 'react';
import { geoEquirectangular,geoPath,geoGraticule10 } from 'd3-geo';
import { feature } from 'topojson-client';
import type { GeometryObject,Topology } from 'topojson-specification';
import landTopology from 'world-atlas/land-110m.json';
import { BasicView } from '../ocean/BasicView';
import { nearest,palettes,type Paint,type Point,type ScalarDisplayGrid } from '../ocean/grid';
import { latitudeLabel,longitudeLabel } from '../geography';
import type { OceanScene } from '../ocean/scene';
import type { WideField,WideProfile,WideQuery } from './contracts';
const topo=landTopology as unknown as Topology<{land:GeometryObject}>;
const land=feature(topo,topo.objects.land);
export function RegionLocator({query,latitudeRange}:{query:WideQuery;latitudeRange?:[number,number]}){
 const projection=geoEquirectangular().scale(620/(2*Math.PI)).translate([310,158]),path=geoPath(projection);
 const east=query.east<query.west?query.east+360:query.east;
 const valid=[query.west,query.east,query.south,query.north].every(Number.isFinite)&&Math.abs(query.west)<=180&&Math.abs(query.east)<=180&&query.south>=-90&&query.north<=90&&query.south<query.north;const rects=!valid?[]:east>180?[[query.west,180],[-180,east-360]]:[[query.west,east]];
 return <svg className="wide-locator" viewBox="0 0 620 315" role="img" aria-label="Selected region and source latitude coverage"><rect width="620" height="315" fill="#0b202c"/>{latitudeRange&&<rect x="0" y={projection([0,latitudeRange[1]])![1]} width="620" height={projection([0,latitudeRange[0]])![1]-projection([0,latitudeRange[1]])![1]} fill="#183541"/>}<path d={path(geoGraticule10())??''} fill="none" stroke="#2b4654" strokeWidth=".6"/><path d={path(land)??''} fill="#46616b" stroke="#718992" strokeWidth=".4"/>{rects.map(([west,e],i)=>{const a=projection([west,query.north])!,b=projection([e,query.south])!;return <rect key={i} x={a[0]} y={a[1]} width={Math.max(0,b[0]-a[0])} height={Math.max(0,b[1]-a[1])} fill="#82d6c433" stroke="#9ce3d0" strokeWidth="2"/>;})}<text x="12" y="300" fill="#d4e3e9" fontSize="12">Shaded band: source latitude support. Outline: requested area.</text></svg>;
}
export function localProfile(field:WideField,point:Point):WideProfile{
 const x=nearest(field.longitude,point[0]),y=nearest(field.latitude,point[1]),ny=field.shape[1],nx=field.shape[2];
 return {levels:field.levels,values:field.levels.map((_,z)=>field.values[(z*ny+y)*nx+x]),latitude:field.latitude[y],longitude:field.longitude[x],units:field.units,vertical_units:field.dataset.vertical_units,source_sha256:field.source_sha256,source_indices:{level:field.source_indices.level,latitude:field.source_indices.latitude[y],longitude:field.source_indices.longitude[x]}};
}
export function RegionalView({field,mode,depth,section,paint,cutaway,quality,onPick,active}:{field:WideField;mode:'slice'|'section'|'volume';depth:number;section:number;paint:Paint;cutaway:boolean;quality:'auto'|'basic';onPick:(p:Point)=>void;active:boolean}){
 const host=useRef<HTMLDivElement>(null),scene=useRef<OceanScene|null>(null),[failure,setFailure]=useState('');
 const grid=useMemo<ScalarDisplayGrid>(()=>{const take=(n:number)=>Array.from({length:Math.min(n,40)},(_,i)=>Math.round(i*(n-1)/(Math.min(n,40)-1)));const xs=take(field.longitude.length),ys=take(field.latitude.length);return {depth_m:field.levels,latitude:ys.map(i=>field.latitude[i]),longitude:xs.map(i=>field.longitude[i]),shape:[field.levels.length,ys.length,xs.length],values:field.levels.flatMap((_,z)=>ys.flatMap(y=>xs.map(x=>field.values[(z*field.shape[1]+y)*field.shape[2]+x]))),units:field.units};},[field]);
 const is3D=mode==='volume'&&field.dataset.vertical_units==='m'&&field.levels.length>1&&quality==='auto'&&!failure;
 const picked=useRef(onPick);picked.current=onPick;
 useEffect(()=>{if(!is3D||!host.current)return;let stopped=false;import('../ocean/scene').then(({OceanScene})=>{if(stopped||!host.current)return;try{scene.current=new OceanScene(host.current,p=>picked.current(p),setFailure,()=>{});scene.current.update({data:grid,mode:'volume',paint,depthIndex:Math.min(depth,grid.shape[0]-1),sectionIndex:Math.min(section,grid.shape[1]-1),iso:20,exaggeration:5000,quality:'balanced',probe:[grid.longitude[0],grid.latitude[0],grid.depth_m[0]],cutaway,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,active,pickEnabled:true});}catch(e){setFailure(String(e));}}).catch(()=>setFailure('3D could not load. The scientific section remains available.'));return()=>{stopped=true;scene.current?.dispose();scene.current=null;};},[is3D,grid]);
 useEffect(()=>{scene.current?.update({data:grid,mode:'volume',paint,depthIndex:Math.min(depth,grid.shape[0]-1),sectionIndex:Math.min(section,grid.shape[1]-1),iso:20,exaggeration:5000,quality:'balanced',probe:[grid.longitude[0],grid.latitude[0],grid.depth_m[0]],cutaway,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,active,pickEnabled:true});},[grid,paint,depth,section,cutaway,active]);
 const basicMode=field.levels.length<2?'slice':mode==='volume'?'section':mode;
 return <><div className="wide-data-view">{is3D?<div ref={host} className="wide-scene" aria-label="Regional 3D ocean volume"/>:<BasicView data={grid} mode={basicMode} depthIndex={Math.min(depth,grid.shape[0]-1)} sectionIndex={Math.min(section,grid.shape[1]-1)} paint={paint} onPick={onPick} verticalUnit={field.dataset.vertical_units}/>}</div>{is3D&&<p className="wide-muted">Depth exaggerated 5,000 times for visibility. Drag to rotate. Source depths stay unchanged.</p>}{failure&&<p role="status">{failure}</p>}<div className="wide-colorbar"><span>{paint.min} {field.units}</span><i style={{background:`linear-gradient(90deg,${palettes[paint.palette].join(',')})`}}/><span>{paint.max} {field.units}</span></div><p className="wide-muted">Display sampling uses at most 40 horizontal positions per axis. Hatching marks missing support. Colours are display interpolation; the profile and export retain native values.</p></>;
}
export function NativeProfile({profile,uncertainty}:{profile:WideProfile;uncertainty?:WideProfile|null}){
 const good=profile.values.filter((v):v is number=>v!==null),low=good.length?Math.min(...good):0,high=good.length?Math.max(...good):1,span=high-low||1,z0=profile.levels[0],zspan=profile.levels.at(-1)!-z0||1;
 const x=(v:number)=>65+(v-low)/span*285,y=(z:number)=>25+(z-z0)/zspan*265;let d='';let pen=false;
 profile.values.forEach((v,i)=>{if(v===null){pen=false;return;}d+=`${pen?'L':'M'}${x(v)} ${y(profile.levels[i])} `;pen=true;});
 return <section className="wide-profile"><h3>Native water column</h3><p>{longitudeLabel(profile.longitude)}, {latitudeLabel(profile.latitude)}</p><svg viewBox="0 0 395 335" role="img" aria-label={`Native profile in ${profile.units} against ${profile.vertical_units}`}><path d="M65 25V290H350" fill="none" stroke="#79909d"/>{[0,.25,.5,.75,1].map(t=><g key={t}><text x="58" y={25+t*265+4} textAnchor="end">{Number((z0+t*zspan).toFixed(1))}</text><text x={65+t*285} y="311" textAnchor="middle">{(low+t*span).toFixed(1)}</text></g>)}<path d={d} stroke="#9ee5d1" strokeWidth="2" fill="none"/><text x="65" y="15">{profile.vertical_units}, increasing downward</text><text x="205" y="333" textAnchor="middle">{profile.units}</text>{!good.length&&<text x="200" y="150" textAnchor="middle">No valid samples</text>}</svg><details><summary>Exact values and source indices</summary><div className="wide-table-scroll"><table><thead><tr><th>Source level</th><th>{profile.vertical_units}</th><th>{profile.units}</th>{uncertainty&&<th>Provider uncertainty</th>}</tr></thead><tbody>{profile.levels.map((z,i)=><tr key={i}><td>{profile.source_indices.level[i]}</td><td>{z}</td><td>{profile.values[i]??'Missing'}</td>{uncertainty&&<td>{uncertainty.values[i]??'Unavailable'}</td>}</tr>)}</tbody></table></div></details></section>;
}
