import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { useLearningTool } from '../learning/bridge';
import { useQuery } from '@tanstack/react-query';
import { Download,LoaderCircle,MapPin,Globe2,X } from 'lucide-react';
import { latitudeLabel,longitudeLabel } from '../geography';
import { type Paint,type Point } from '../ocean/grid';
import { DEFAULT_QUERY,cacheField,cacheKey,cachedField,cacheStats,parseWideCatalog,parseWideField,parseWideProfile,verifyPack,wideRequest,type WideField,type WidePack,type WideProfile,type WideQuery } from './contracts';
import { NativeProfile,RegionalView,RegionLocator,localProfile } from './RegionalView';
import { download,offlineHtml } from './offline';
import './wider.css';
const STORAGE='ocean-regional-pack-v1';
const message=(e:unknown)=>e instanceof Error?e.message:'The operation could not finish.';
export function WiderWorkspace({active}:{active:boolean}){
 const catalog=useQuery({queryKey:['wider-catalog'],queryFn:({signal})=>wideRequest('catalog',undefined,parseWideCatalog,signal),enabled:active,staleTime:Infinity,retry:false});
 const [query,setQuery]=useState<WideQuery>(DEFAULT_QUERY),[field,setField]=useState<WideField|null>(null),[uncertainty,setUncertainty]=useState<WideField|null>(null),[profile,setProfile]=useState<WideProfile|null>(null),[uncertaintyProfile,setUncertaintyProfile]=useState<WideProfile|null>(null);
 const [stage,setStage]=useState(''),[status,setStatus]=useState('Choose a source and area, then load the region.'),[error,setError]=useState(''),[pack,setPack]=useState<WidePack|null>(null),[offline,setOffline]=useState(false),[profileBusy,setProfileBusy]=useState(false),[saving,setSaving]=useState(false);
 const [mode,setMode]=useState<'slice'|'section'|'volume'>('slice'),[depth,setDepth]=useState(0),[section,setSection]=useState(0),[cutaway,setCutaway]=useState(false),[quality,setQuality]=useState<'auto'|'basic'>(()=>{const n=navigator as Navigator&{deviceMemory?:number;connection?:{saveData?:boolean;effectiveType?:string}};return (n.deviceMemory??8)<=4||n.connection?.saveData||['slow-2g','2g'].includes(n.connection?.effectiveType??'')?'basic':'auto';});
 const loadRef=useRef<AbortController|null>(null),profileRef=useRef<AbortController|null>(null),actionRef=useRef<AbortController|null>(null),generation=useRef(0),input=useRef<HTMLInputElement>(null);
 const dataset=catalog.data?.datasets.find(d=>d.id===query.dataset)??(field?.dataset.id===query.dataset?field.dataset:undefined);
 const shown=field?.dataset.variables[field.query.variable];
 const paint=useMemo<Paint>(()=>({min:shown?.paint[0]??0,max:shown?.paint[1]??30,palette:field?.query.variable==='oxygen_uncertainty'?'mono':'thermal',log:false,opacity:1}),[shown,field?.query.variable]);
 const changed=field&&Object.keys(query).some(k=>k!=='resolution'&&field.query[k as keyof WideQuery]!==query[k as keyof WideQuery]);
 const pending=Boolean(stage);
 function cancel(){generation.current++;loadRef.current?.abort();profileRef.current?.abort();actionRef.current?.abort();setStage('');setSaving(false);setProfileBusy(false);setStatus('Cancelled. Any completed view remains labelled below.');}
 useEffect(()=>{if(!active){loadRef.current?.abort();profileRef.current?.abort();actionRef.current?.abort();generation.current++;setStage('');setSaving(false);setProfileBusy(false);}},[active]);
 useEffect(()=>()=>{loadRef.current?.abort();profileRef.current?.abort();actionRef.current?.abort();},[]);
 async function load(){
  if(!dataset)return;cancel();const run=++generation.current,controller=new AbortController();loadRef.current=controller;setError('');setOffline(false);setPack(null);setProfile(null);setUncertaintyProfile(null);setUncertainty(null);setStage('Checking native bounds and request size');const selected={...query,resolution:'display' as const};
  const accept=(next:WideField)=>{if(next.source_sha256!==dataset.source_sha256)throw new Error('Source version changed. Reload the source catalogue.');if(generation.current!==run)return;setField(next);setDepth(0);setSection(Math.floor(next.latitude.length/2));if(next.dataset.vertical_units!=='m'||next.levels.length<2)setMode('slice');};
  try{
   await wideRequest('preview',selected,x=>x,controller.signal);
   const key=cacheKey(selected,dataset.source_sha256),cached=cachedField(key);
   if(cached){accept(cached);setStatus('Loaded checked data from this tab’s bounded cache.');}
   else{
    setStage('Loading a light preview');const preview=await wideRequest('subset',{...selected,resolution:'preview'},parseWideField,controller.signal);if(generation.current!==run)return;accept(preview);setStatus('Coarse preview. Display refinement is loading.');setStage('Refining the display at native vertical levels');
    const complete=await wideRequest('subset',selected,parseWideField,controller.signal);if(generation.current!==run)return;cacheField(key,complete);accept(complete);setStatus('Region loaded. Click the view to inspect a native water column.');
   }
   if(selected.variable==='oxygen'){
    setStage('Loading the provider uncertainty field');const uq={...selected,variable:'oxygen_uncertainty' as const},uk=cacheKey(uq,dataset.source_sha256);let u=cachedField(uk);if(!u){u=await wideRequest('subset',uq,parseWideField,controller.signal);cacheField(uk,u);}if(generation.current!==run)return;if(u.source_sha256!==dataset.source_sha256)throw new Error('Uncertainty and field source versions differ.');setUncertainty(u);
   }
  }catch(e){if(controller.signal.aborted)return;if(generation.current===run)setError(message(e));}
  finally{if(generation.current===run)setStage('');}
 }
 const pick=useCallback(async(point:Point)=>{
  if(!field)return;profileRef.current?.abort();const c=new AbortController();profileRef.current=c;const run=generation.current;
  if(offline){setProfile(localProfile(field,point));setUncertaintyProfile(uncertainty?localProfile(uncertainty,point):null);return;}
  setProfileBusy(true);setError('');setUncertaintyProfile(null);
  try{const p=await wideRequest('profile',{query:field.query,longitude:point[0],latitude:point[1]},parseWideProfile,c.signal);if(c.signal.aborted||run!==generation.current)return;if(p.source_sha256!==field.source_sha256)throw new Error('Profile and view source versions differ.');setProfile(p);
   if(field.query.variable==='oxygen'){const u=await wideRequest('profile',{query:{...field.query,variable:'oxygen_uncertainty'},longitude:point[0],latitude:point[1]},parseWideProfile,c.signal);if(!c.signal.aborted&&run===generation.current){if(u.source_sha256!==p.source_sha256||JSON.stringify(u.levels)!==JSON.stringify(p.levels)||u.latitude!==p.latitude||u.longitude!==p.longitude)throw new Error('Uncertainty and profile coordinates differ.');setUncertaintyProfile(u);}}
  }catch(e){if(!c.signal.aborted&&run===generation.current)setError(message(e));}finally{if(!c.signal.aborted&&run===generation.current)setProfileBusy(false);}
 },[field,offline,uncertainty]);
 function selectSource(id:WideQuery['dataset']){const source=catalog.data?.datasets.find(d=>d.id===id);if(!source)return;setQuery(q=>({...q,dataset:id,variable:id==='godas-2022'?'potential_temperature':'oxygen',level_min:source.level_range[0],level_max:source.level_range[1],south:Math.max(q.south,Math.ceil(source.latitude_range[0])),north:Math.min(q.north,Math.floor(source.latitude_range[1]))}));}
 async function getPack(controller:AbortController){if(pack)return pack;if(!field)throw new Error('Load a region first.');const raw=await wideRequest('pack',field.query,x=>x,controller.signal),checked=await verifyPack(raw);if(controller.signal.aborted)throw new DOMException('Cancelled','AbortError');setPack(checked.pack);return checked.pack;}
 async function exportAs(kind:'json'|'html'|'save'|'replay'){
  actionRef.current?.abort();const controller=new AbortController();actionRef.current=controller;setError('');setSaving(true);try{const p=await getPack(controller);if(controller.signal.aborted)return;if(kind==='replay'){await wideRequest('replay',p,x=>{if(!x||typeof x!=='object'||!('matched' in x)||x.matched!==true)throw new Error('Replay did not match.');return x;},controller.signal);setStatus('Server replay matched the original source, settings and every numerical value.');}
   else if(kind==='save'){const text=JSON.stringify(p);if(new TextEncoder().encode(text).length>4_000_000)throw new Error('This pack exceeds the 4 MB browser-storage limit. Download it instead.');localStorage.setItem(STORAGE,text);setStatus('Saved one regional pack on this device. Saving another replaces it.');}
   else if(kind==='json')download('ocean-region.json',JSON.stringify(p));else download('ocean-region-offline.html',offlineHtml(p),'text/html');
  }catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError(message(e));}finally{setSaving(false);}
 }
 async function openPack(raw:unknown){cancel();const checked=await verifyPack(raw);setQuery({...checked.field.query,resolution:'display'});setField(checked.field);setUncertainty(checked.uncertainty);setPack(checked.pack);setOffline(true);setDepth(0);setSection(Math.floor(checked.field.latitude.length/2));setProfile(null);setMode('slice');setError('');setStatus('Local regional pack. Checksum verified; use Verify replay online to confirm it against the server sources.');}
 async function openSaved(){try{const text=localStorage.getItem(STORAGE);if(!text)throw new Error('No regional pack is saved on this device.');await openPack(JSON.parse(text));}catch(e){setError(message(e));}}
 const cache=cacheStats();
 useLearningTool('wider',active,{
   tool:'wider',caseId:field?.dataset.id??'',status:error||catalog.error?'error':pending?'loading':field?'ready':'empty',title:'A bounded wider-source region',kind:field?.kind==='ml_derived'?'derived':'model',
   facts:[{label:'Dataset',value:field?.dataset.title??null},{label:'Source time (UTC)',value:field?.time??null},{label:'Available display samples',value:field?.valid_count??null},{label:'Vertical coordinate',value:field?`${field.dataset.vertical_name} (${field.dataset.vertical_units})`:null}],parameters:field?{...field.query}:{},sources:[{label:'Regional source catalogue and limits',href:'/api/wider/catalog'},...(field?[{label:'Original product reference',href:field.dataset.reference}]:[])],limits:field?.dataset.limitations.slice(0,2)??['Only supported, bounded source areas can be loaded.'],message:error||catalog.error?.message,
 },async(command,signal)=>{if(catalog.error){const retried=await catalog.refetch();if(retried.error)throw retried.error;return false;}if(command.action==='inspect')return true;if(command.action==='load'){if(!dataset)return false;signal.addEventListener('abort',cancel,{once:true});try{await load();return true;}finally{signal.removeEventListener('abort',cancel);}}throw new Error('This regional action is not supported.');});
 return <section className="wide-workspace" aria-label="Wider ocean coverage">
 <header className="wide-heading"><div><p className="eyebrow">REGIONAL DATA ACCESS</p><h1>Explore a wider ocean</h1><p>Choose a real source and a bounded area. Check its coverage before loading.</p></div><Globe2 size={34}/></header>
 <div className="wide-layout"><form className="wide-controls" onSubmit={e=>{e.preventDefault();void load();}}>
 <h2>1. Choose your data</h2>{catalog.isPending&&<p role="status">Loading source availability...</p>}{catalog.isError&&<p role="status">The source catalogue is unavailable. You can still open a saved regional pack.</p>}
 <label>Data source<select aria-label="Data source" value={query.dataset} onChange={e=>selectSource(e.target.value as WideQuery['dataset'])} disabled={!catalog.data}>{(catalog.data?.datasets??(dataset?[dataset]:[])).map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label>
 {dataset&&<><label>Regional variable<select aria-label="Regional variable" value={query.variable} onChange={e=>setQuery(q=>({...q,variable:e.target.value as WideQuery['variable']}))}>{Object.entries(dataset.variables).map(([id,v])=><option key={id} value={id}>{v!.label} ({v!.units})</option>)}</select></label><label>Regional month<select aria-label="Regional month" value={query.time_index} onChange={e=>setQuery(q=>({...q,time_index:Number(e.target.value)}))}>{dataset.times.map((t,i)=><option key={t} value={i}>{t.slice(0,7)}</option>)}</select></label><p className="wide-muted">Monthly mean: {dataset.intervals[query.time_index]?.[0].slice(0,10)} to {dataset.intervals[query.time_index]?.[1].slice(0,10)} (end excluded).</p><div className="wide-source-note"><strong>{dataset.kind==='ml_derived'?'External ML-derived product':'Model analysis'}</strong><p>{dataset.variables[query.variable]?.definition}</p><p>Latitude: {latitudeLabel(dataset.latitude_range[0])} to {latitudeLabel(dataset.latitude_range[1])}. {dataset.vertical_name}: {dataset.level_range[0]} to {dataset.level_range[1]} {dataset.vertical_units}.</p><p>No observations are bundled for arbitrary regions. Original profiles remain in the curated cases.</p></div></>}
 <h2>2. Select an area</h2><div className="wide-presets">{catalog.data?.presets.map(p=><button type="button" key={p.id} onClick={()=>setQuery(q=>({...q,west:p.bounds[0],south:p.bounds[1],east:p.bounds[2],north:p.bounds[3]}))}>{p.label}</button>)}</div>
 <RegionLocator query={query} latitudeRange={dataset?.latitude_range}/><p className="wide-muted">{longitudeLabel(query.west)} to {longitudeLabel(query.east)}, {latitudeLabel(query.south)} to {latitudeLabel(query.north)}{query.east<query.west?' · crosses the date line':''}</p>
 <details><summary>Area and vertical limits</summary><div className="wide-number-grid">{(['west','east','south','north','level_min','level_max'] as const).map(k=><label key={k}>{({west:'West longitude',east:'East longitude',south:'South latitude',north:'North latitude',level_min:`Minimum ${dataset?.vertical_name.toLowerCase()??'level'}`,level_max:`Maximum ${dataset?.vertical_name.toLowerCase()??'level'}`})[k]}<input type="number" step="any" required value={Number.isFinite(query[k])?query[k]:''} onChange={e=>setQuery(q=>({...q,[k]:e.target.value===''?NaN:Number(e.target.value)}))}/></label>)}</div><p className="wide-muted">At most 90° longitude, 40° latitude and 120,000 native values per request. Unsupported grids or polar coverage are rejected.</p></details>
 <button className="primary-button wide-load" type="submit" disabled={!dataset||pending}>{pending?<LoaderCircle className="spin" size={17}/>:<MapPin size={17}/>}Load region</button>{(pending||saving)&&<button type="button" onClick={cancel}><X size={15}/>Cancel request</button>}
 <h2>Regional packs</h2><p className="wide-muted">A pack keeps the exact selected values and source information. The offline HTML opens without this website or an internet connection.</p><div className="wide-actions"><button type="button" onClick={openSaved}>Open saved regional pack</button><button type="button" onClick={()=>input.current?.click()}>Import regional JSON</button><button type="button" onClick={()=>{localStorage.removeItem(STORAGE);setStatus('The regional pack was removed from this device.');}}>Remove local pack</button></div><input ref={input} type="file" accept=".json,application/json" aria-label="Import regional pack file" hidden onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>4_500_000)throw new Error('Regional file exceeds 4.5 MB.');await openPack(JSON.parse(await f.text()));}catch(err){setError(message(err));}}}/>
 <p className="wide-muted">This tab caches at most 6 fields / 8 MiB. Current use: {(cache.bytes/1048576).toFixed(2)} MiB. Native exports keep their full precision.</p>
 </form><div className="wide-results" aria-busy={pending}>
 <div className="wide-status" role="status">{pending&&<LoaderCircle className="spin" size={16}/>}<span>{stage||status}</span></div>{error&&<div role="alert" className="wide-error">{error}</div>}
 {changed&&<p className="wide-change">Controls have changed. The view still shows its labelled applied selection until you load again.</p>}
 {!field?<div className="wide-empty"><Globe2 size={56}/><h2>Start with the North Atlantic</h2><button className="primary-button" disabled={!dataset||pending} onClick={()=>void load()}>Open selected region</button><p>Load its monthly water column, then inspect a depth slice or open the 3D view. Use the oxygen source to explore a separately labelled ML product and its uncertainty.</p><p>These requests extend beyond the five curated cases. Earlier scientific labs remain tied to their tested case sources.</p></div>:<>
 <header className="wide-result-heading"><div><p className="eyebrow">{offline?'LOCAL PACK':field.query.resolution==='preview'?'COARSE PREVIEW':'REGION LOADED'}</p><h2>{shown?.label}</h2><p>{field.dataset.provider} · {field.time.slice(0,7)} monthly mean</p><p>{longitudeLabel(field.longitude[0])} to {longitudeLabel(field.longitude.at(-1)!)}, {latitudeLabel(field.latitude[0])} to {latitudeLabel(field.latitude.at(-1)!)}</p></div></header>
 <div className="wide-view-tools"><div role="group" aria-label="Regional view mode">{(['slice','section','volume'] as const).map(m=><button key={m} onClick={()=>setMode(m)} aria-pressed={mode===m} disabled={(m!=='slice'&&field.levels.length<2)||(m==='volume'&&field.dataset.vertical_units!=='m')}>{m==='slice'?'Slice':m==='section'?'Section':'3D volume'}</button>)}</div><label>Display quality<select aria-label="Display quality" value={quality} onChange={e=>setQuality(e.target.value as 'auto'|'basic')}><option value="auto">Adaptive 3D</option><option value="basic">Basic view</option></select></label>{mode==='volume'&&<button aria-pressed={cutaway} onClick={()=>setCutaway(v=>!v)}>{cutaway?'Close cutaway':'Open cutaway'}</button>}</div>
 {field.dataset.vertical_units==='dbar'&&<p className="wide-muted">This product uses pressure in dbar. The depth-in-metres 3D renderer is unavailable.</p>}
 {mode==='slice'?<label className="wide-slider">{field.dataset.vertical_name}: {field.levels[depth]??field.levels[0]} {field.dataset.vertical_units}<input aria-label="Regional vertical level" type="range" min="0" max={field.levels.length-1} value={Math.min(depth,field.levels.length-1)} onChange={e=>setDepth(Number(e.target.value))}/></label>:mode==='section'?<label className="wide-slider">Section latitude: {latitudeLabel(field.latitude[Math.min(section,field.latitude.length-1)])}<input aria-label="Regional section latitude" type="range" min="0" max={field.latitude.length-1} value={Math.min(section,field.latitude.length-1)} onChange={e=>setSection(Number(e.target.value))}/></label>:null}
 <RegionalView field={field} mode={mode} depth={depth} section={section} paint={paint} cutaway={cutaway} quality={quality} onPick={pick} active={active}/>
 <p className="wide-resolution">Displayed grid: {[field.shape[0],Math.min(40,field.shape[1]),Math.min(40,field.shape[2])].join(' × ')}. Loaded grid: {field.shape.join(' × ')}. Native selected grid: {field.native_shape.join(' × ')}. {field.valid_count.toLocaleString()} valid loaded values; {field.values.length-field.valid_count} missing. This is coverage, not confidence.</p>
 {uncertainty&&<p className="wide-source-note">Provider uncertainty is loaded separately. Click a column to inspect its exact uncertainty values, or select Provider oxygen uncertainty to map the field.</p>}
 {profileBusy&&<p role="status">Reading the native water column...</p>}{profile&&<NativeProfile profile={profile} uncertainty={uncertaintyProfile}/>}
 <div className="wide-actions"><button disabled={pending||saving} onClick={()=>exportAs('json')}><Download size={15}/>Download native JSON</button><button disabled={pending||saving} onClick={()=>exportAs('html')}>Download offline viewer</button><button disabled={pending||saving} onClick={()=>exportAs('save')}>Save regional pack on device</button><button disabled={pending||saving} onClick={()=>exportAs('replay')}>Verify replay online</button></div>
 <details className="wide-provenance"><summary>Sources, scientific limits and method</summary><p>{field.dataset.version}</p><p>{field.dataset.citation}</p><a href={field.dataset.reference} target="_blank" rel="noreferrer">Open original source reference</a><p>{field.dataset.licence}</p>{field.dataset.model_version&&<p>{field.dataset.model_version}</p>}{field.dataset.uncertainty_definition&&<p>{field.dataset.uncertainty_definition}</p>}<ul>{field.dataset.limitations.map(t=><li key={t}>{t}</li>)}</ul><p>Method: {field.method}</p><p>Source manifest: <code>{field.source_sha256}</code></p><p>Original source index selections are retained in every pack. Individual missing values and independent uncertainty masks remain missing.</p></details>
 </>}
 </div></div></section>;
}
