"""P17 independent boundary checks, using labelled synthetic test fields only.

The expected values use vector geometry, Decimal arithmetic and whole-domain
shell integrals. They are not generated by the production matching/search code.
These tests establish numerical behavior, not oceanographic field validation.
"""
from decimal import Decimal, localcontext
from math import cos, fsum, pi, radians, sin, sqrt
from types import SimpleNamespace as NS

import numpy as np
import pytest

from science.evidence import compare, nearest_column
from science.evidence_contracts import MatchSettings
from science.feature_contracts import FeatureQuery
from science.features import analyze
from science.instruments import InstrumentProfile, Measurement, Parameter, Reading


TIME = '2024-01-07T00:00:00Z'


def make_profile(depths):
    parameter = Parameter(label='Temperature', units='\u00b0C',
                          definition='In-situ sea-water temperature',
                          source_field='synthetic_test_field', mode='R',
                          qc_scheme='declared', accepted_count=len(depths))
    levels = [Measurement(index=i, depth_m=z, pressure_dbar=None,
                          latitude=12.07, longitude=85.07, time=TIME,
                          coordinate_status='test coordinates', coordinate_eligible=True,
                          coordinate_qc={'scheme': 'declared', 'pressure': '1', 'position': '1', 'time': '1'},
                          readings={'temperature': Reading(value=20 + i, qc='1', accepted=True, reason='accepted')})
              for i, z in enumerate(depths)]
    return InstrumentProfile(id='p17-synthetic', instrument='argo', platform='test',
                             title='Synthetic audit fixture, not a source observation',
                             time=TIME, time_end=TIME, latitude=12.07, longitude=85.07,
                             samples=len(levels), depth_range_m=(min(depths), max(depths)),
                             parameters={'temperature': parameter}, source_url='',
                             source_file='test-fixture', source_sha256='a' * 64,
                             depth_method='Prescribed test metres', qc_policy='Prescribed test flags', levels=levels)


@pytest.mark.parametrize('seed', range(12))
def test_nearest_column_matches_unit_vector_angle_oracle_across_hemispheres(seed):
    rng = np.random.default_rng(seed)
    latitude = float(rng.uniform(-75, 75))
    longitude = float(rng.uniform(-179, 179))
    latitudes = tuple(sorted(rng.uniform(-80, 80, 5)))
    longitudes = tuple(sorted(rng.uniform(-180, 180, 7)))

    def vector(lat, lon):
        return np.array([cos(radians(lat)) * cos(radians(lon)),
                         cos(radians(lat)) * sin(radians(lon)), sin(radians(lat))])

    point = vector(latitude, longitude)
    expected = []
    for y, lat in enumerate(latitudes):
        for x, lon in enumerate(longitudes):
            other = vector(lat, lon)
            angle = np.arctan2(np.linalg.norm(np.cross(point, other)), np.dot(point, other))
            expected.append((float(angle) * 6371.0088, y, x))
    oracle = min(expected)
    actual = nearest_column(latitude, longitude, latitudes, longitudes)
    assert actual[1:] == oracle[1:]
    assert actual[0] == pytest.approx(oracle[0], abs=2e-9)


@pytest.mark.parametrize('masked_index', [None, 1, 2, 3])
def test_irregular_interpolation_exact_levels_masks_and_metrics_against_decimal(masked_index):
    native_depths = [0., 7., 39., 123., 500.]
    column = [30.13, 28.79, 25.37, 19.41, 12.83]
    samples = [0., 3., 7., 8., 39., 100., 123., 499., 500.]
    data = np.tile(np.array(column)[:, None, None], (1, 2, 2))
    if masked_index is not None:
        data[masked_index] = np.nan
    manifest = NS(case=NS(id='p17-synthetic'),
                  coordinates=NS(times=[TIME], depth_m=native_depths,
                                 latitude=[12., 12.1], longitude=[85., 85.1]),
                  variables=[NS(id='temperature', standard_name='sea_water_temperature', units='\u00b0C')])
    profile = make_profile(samples)
    result = compare(manifest, 'b' * 64, 'c' * 64, profile,
                     MatchSettings(time_index=0, distance_km=50, max_vertical_gap_m=500), data.ravel())
    residuals = []
    for row in result.rows:
        z = samples[row.sample_index]
        lo = max(i for i, depth in enumerate(native_depths) if depth <= z)
        hi = min(i for i, depth in enumerate(native_depths) if depth >= z)
        if masked_index in (lo, hi):
            assert not row.accepted and row.reason == 'masked_bracket'
            assert row.model is None and row.residual is None
            continue
        with localcontext() as context:
            context.prec = 40
            fraction = Decimal(0) if lo == hi else ((Decimal(str(z)) - Decimal(str(native_depths[lo]))) /
                                                    (Decimal(str(native_depths[hi])) - Decimal(str(native_depths[lo]))))
            model = Decimal(str(column[lo])) + fraction * (Decimal(str(column[hi])) - Decimal(str(column[lo])))
            residual = model - Decimal(20 + row.sample_index)
        assert row.accepted
        assert row.model == pytest.approx(float(model), abs=1e-12)
        assert row.residual == pytest.approx(float(residual), abs=1e-12)
        residuals.append(float(residual))
    assert result.matched_count == len(residuals)
    assert result.metrics.bias == pytest.approx(fsum(residuals) / len(residuals), abs=1e-12)
    assert result.metrics.mae == pytest.approx(fsum(abs(v) for v in residuals) / len(residuals), abs=1e-12)
    assert result.metrics.rmse == pytest.approx(sqrt(fsum(v * v for v in residuals) / len(residuals)), abs=1e-12)


@pytest.mark.parametrize('latitude', [[-61., -59.5, -55.], [4., 4.3, 8.]])
def test_full_connected_volume_matches_single_geometric_shell_integral(latitude):
    depths = [0., 7., 39., 123., 500.]
    longitudes = [80., 80.3, 82., 87.]
    field = np.full((len(depths), len(latitude), len(longitudes)), 25.)
    result = analyze(field, dict(depth_m=depths, latitude=latitude, longitude=longitudes),
                     FeatureQuery(threshold=24, depth_min_m=0, depth_max_m=500))
    with localcontext() as context:
        context.prec = 50
        radius = Decimal('6371008.8')
        radial_integral = (radius ** 3 - (radius - Decimal(500)) ** 3) / Decimal(3)
        # Angular factor is evaluated independently for the entire domain,
        # without using inferred production midpoint edges or cell volumes.
        angular_factor = (sin(radians(latitude[-1])) - sin(radians(latitude[0]))) * (longitudes[-1] - longitudes[0]) * pi / 180
        expected = float(radial_integral) * angular_factor / 1e9
    assert len(result['regions']) == 1
    assert result['regions'][0]['cell_count'] == field.size
    assert result['regions'][0]['estimated_volume_km3'] == pytest.approx(expected, rel=1e-13)
    # A missing entire plane splits the region instead of becoming cold water
    # or a bridge between disjoint supported source cells.
    field[2] = np.nan
    split = analyze(field, dict(depth_m=depths, latitude=latitude, longitude=longitudes),
                    FeatureQuery(threshold=24, depth_min_m=0, depth_max_m=500))
    assert len(split['regions']) == 2
    assert split['qualified_cells'] == field.size - len(latitude) * len(longitudes)
