import type { FeatureVariable, RegionSummary } from '../features/contracts';
import { featureVariables } from '../features/contracts';
import { count, equal, finite, hash, invalid, numbers, object, stamp, strings } from './shared';

export type EvolutionMethod = 'p14-native-overlap-v1' | 'p14-native-overlap-v2';
export const currentEvolutionMethod: EvolutionMethod = 'p14-native-overlap-v2';
export const supportedEvolutionMethod = (value: unknown): value is EvolutionMethod => value === 'p14-native-overlap-v1' || value === 'p14-native-overlap-v2';
export type EvolutionQuery = { variable: FeatureVariable; units: string; operator: 'at_least' | 'at_most' | 'between'; threshold: number; upper_threshold: number | null; depth_min_m: number; depth_max_m: number; start_index: number; end_index: number; frame_step: number; minimum_overlap: number; sensitivity_delta: number };
export type EvolutionRecipe = { mode: 'evolution'; case_id: string; query: EvolutionQuery; selected_node: string | null };
export type EvolutionNode = RegionSummary & { node_id: string; time_index: number; membership_sha256: string; footprint_indices: number[]; boundary_contacts: string[]; selection_depth_contacts: string[]; touches_domain_boundary: boolean; touches_missing_values: boolean };
export type EvolutionFrame = { time_index: number; time: string; qualified_cells: number; total_regions: number; estimated_volume_km3: number; regions: EvolutionNode[] };
export type EvolutionLink = { source_node_id: string; target_node_id: string; shared_cells: number; estimated_overlap_volume_km3: number; source_fraction: number; target_fraction: number; overlap_coefficient: number; classification: 'continuation' | 'split' | 'merge' | 'ambiguous' };
export type EvolutionTransition = { from_time_index: number; to_time_index: number; from_time: string; to_time: string; elapsed_hours: number; status: 'compared' | 'gap'; reason: string | null; links: EvolutionLink[]; appeared_node_ids: string[]; disappeared_node_ids: string[]; ambiguous_node_ids: string[]; source_unresolved_node_ids: string[]; target_unresolved_node_ids: string[]; split_count: number; merge_count: number; ambiguous_count: number; unmatched_details: { node_id: string; relation: 'no_successor' | 'no_predecessor'; reason: 'incomplete_support' | 'no_qualifying_overlap'; missing_counterpart_cells: number }[] };
export type EvolutionSummary = { frame_count: number; transition_count: number; compared_transitions: number; gap_count: number; node_count: number; link_count: number; appearance_count: number; disappearance_count: number; split_count: number; merge_count: number; ambiguous_count: number; unresolved_count: number };
export type EvolutionSensitivity = { offset: number; threshold: number; upper_threshold: number | null; summary: EvolutionSummary; frames: { time_index: number; time: string; region_count: number; qualified_cells: number; estimated_volume_km3: number }[]; transitions: { from_time_index: number; to_time_index: number; status: 'compared' | 'gap'; link_count: number; split_count: number; merge_count: number; ambiguous_count: number; appearance_count: number; disappearance_count: number }[] };
export type EvolutionAnalysis = { schema_version: '1'; kind: 'feature_evolution'; method_version: EvolutionMethod; case_id: string; manifest_sha256: string; observation_library_sha256: string; query: EvolutionQuery; coordinates: { latitude: number[]; longitude: number[] }; edges: { depth_m: number[]; latitude: number[]; longitude: number[] }; cadence_hours: number; frames: EvolutionFrame[]; transitions: EvolutionTransition[]; summary: EvolutionSummary; sensitivity: EvolutionSensitivity[]; methods: string[]; limitations: string[] };
export type EvolutionResult = EvolutionAnalysis;
export const sameEvolutionQuery = (a: unknown, b: unknown) => equal(a, b);
export function validEvolutionQuery(value: unknown): value is EvolutionQuery { return object(value) && typeof value.variable === 'string' && value.variable in featureVariables && value.units === featureVariables[value.variable as FeatureVariable].units && ['at_least', 'at_most', 'between'].includes(String(value.operator)) && finite(value.threshold) && (value.operator === 'between' ? finite(value.upper_threshold) && value.upper_threshold >= value.threshold : value.upper_threshold === null) && finite(value.depth_min_m) && finite(value.depth_max_m) && value.depth_min_m >= 0 && value.depth_min_m < value.depth_max_m && value.depth_max_m <= 5000 && count(value.start_index) && count(value.end_index) && value.end_index > value.start_index && value.end_index <= 6 && count(value.frame_step) && value.frame_step >= 1 && value.frame_step <= 6 && finite(value.minimum_overlap) && value.minimum_overlap > 0 && value.minimum_overlap <= 1 && finite(value.sensitivity_delta) && value.sensitivity_delta >= 0 && value.sensitivity_delta <= 100 && (value.end_index - value.start_index) % value.frame_step === 0; }
export function validEvolutionRecipe(value: unknown): value is EvolutionRecipe { return object(value) && value.mode === 'evolution' && typeof value.case_id === 'string' && validEvolutionQuery(value.query) && (value.selected_node === null || typeof value.selected_node === 'string' && /^t\d+:r\d+$/.test(value.selected_node)); }
const summaryKeys = ['frame_count', 'transition_count', 'compared_transitions', 'gap_count', 'node_count', 'link_count', 'appearance_count', 'disappearance_count', 'split_count', 'merge_count', 'ambiguous_count', 'unresolved_count'] as const;
const validSummary = (value: unknown): value is EvolutionSummary => object(value) && summaryKeys.every(key => count(value[key]));
const axis = (value: unknown, strict = true): value is number[] => numbers(value) && value.length >= 2 && value.every((item, index) => index === 0 || (strict ? item > value[index - 1] : item >= value[index - 1]));
const bounds = (value: unknown) => object(value) && ['west', 'south', 'east', 'north', 'depth_min_m', 'depth_max_m'].every(key => finite(value[key])) && Number(value.west) <= Number(value.east) && Number(value.south) <= Number(value.north) && Number(value.depth_min_m) <= Number(value.depth_max_m);
export function parseEvolution(raw: unknown): EvolutionAnalysis {
  const fail = () => invalid('feature evolution');
  if (!object(raw) || raw.schema_version !== '1' || raw.kind !== 'feature_evolution' || !supportedEvolutionMethod(raw.method_version) || typeof raw.case_id !== 'string' || !hash(raw.manifest_sha256) || !hash(raw.observation_library_sha256) || !validEvolutionQuery(raw.query) || !object(raw.coordinates) || !axis(raw.coordinates.latitude) || !axis(raw.coordinates.longitude) || !object(raw.edges) || !axis(raw.edges.depth_m, false) || !axis(raw.edges.latitude, false) || !axis(raw.edges.longitude, false) || raw.edges.latitude.length !== raw.coordinates.latitude.length + 1 || raw.edges.longitude.length !== raw.coordinates.longitude.length + 1 || raw.cadence_hours !== 12 || !Array.isArray(raw.frames) || raw.frames.length < 2 || raw.frames.length > 7 || !Array.isArray(raw.transitions) || raw.transitions.length !== raw.frames.length - 1 || !validSummary(raw.summary) || !Array.isArray(raw.sensitivity) || !strings(raw.methods) || !strings(raw.limitations)) throw fail();
  const result = raw as EvolutionAnalysis, allNodes = new Map<string, EvolutionNode>(), planeSize = result.coordinates.latitude.length * result.coordinates.longitude.length;
  for (const [index, frame] of result.frames.entries()) {
    if (!object(frame) || !count(frame.time_index) || frame.time_index < result.query.start_index || frame.time_index > result.query.end_index || !stamp(frame.time) || index > 0 && (frame.time_index <= result.frames[index - 1].time_index || Date.parse(frame.time) <= Date.parse(result.frames[index - 1].time)) || !count(frame.qualified_cells) || !count(frame.total_regions) || !Array.isArray(frame.regions) || frame.regions.length !== frame.total_regions) throw fail();
    let cells = 0;
    for (const node of frame.regions) {
      if (!object(node) || typeof node.id !== 'string' || !/^r\d+$/.test(node.id) || node.node_id !== `t${frame.time_index}:${node.id}` || node.time_index !== frame.time_index || allNodes.has(node.node_id) || !count(node.cell_count) || node.cell_count === 0 || !finite(node.estimated_volume_km3) || node.estimated_volume_km3 <= 0 || !bounds(node.center_bounds) || !bounds(node.cell_bounds) || !(['min', 'max', 'mean', 'volume_weighted_mean'] as const).every(key => finite(node[key])) || !hash(node.membership_sha256) || !strings(node.boundary_contacts) || !strings(node.selection_depth_contacts) || !node.selection_depth_contacts.every(contact => ['shallow', 'deep'].includes(contact)) || typeof node.touches_domain_boundary !== 'boolean' || typeof node.touches_missing_values !== 'boolean' || !count(node.eligible_samples) || !count(node.eligible_profiles) || !Array.isArray(node.observations) || node.observations.length !== node.eligible_profiles || !Array.isArray(node.footprint_indices) || !node.footprint_indices.every((cell, position) => count(cell) && cell < planeSize && (position === 0 || cell > node.footprint_indices[position - 1]))) throw fail();
      if (node.observations.some(observation => !object(observation) || typeof observation.profile_id !== 'string' || typeof observation.platform !== 'string' || !count(observation.sample_count) || observation.sample_count === 0) || node.observations.reduce((total, observation) => total + observation.sample_count, 0) !== node.eligible_samples) throw fail();
      cells += node.cell_count; allNodes.set(node.node_id, node);
    }
    if (cells !== frame.qualified_cells) throw fail();
  }
  for (const [index, transition] of result.transitions.entries()) {
    const from = result.frames[index], to = result.frames[index + 1];
    if (!object(transition) || transition.from_time_index !== from.time_index || transition.to_time_index !== to.time_index || transition.from_time !== from.time || transition.to_time !== to.time || transition.elapsed_hours !== (Date.parse(to.time) - Date.parse(from.time)) / 3600000 || !['compared', 'gap'].includes(transition.status) || !(transition.reason === null || typeof transition.reason === 'string') || !Array.isArray(transition.links) || !Array.isArray(transition.unmatched_details) || !count(transition.split_count) || !count(transition.merge_count) || !count(transition.ambiguous_count) || !(['appeared_node_ids', 'disappeared_node_ids', 'ambiguous_node_ids', 'source_unresolved_node_ids', 'target_unresolved_node_ids'] as const).every(key => strings(transition[key]) && (transition[key] as string[]).every(id => allNodes.has(id)))) throw fail();
    if (transition.status === 'gap' && (transition.links.length > 0 || !transition.reason) || transition.status === 'compared' && (transition.elapsed_hours !== result.cadence_hours || to.time_index !== from.time_index + 1)) throw fail();
    for (const detail of transition.unmatched_details) if (!object(detail) || !allNodes.has(detail.node_id) || !['no_successor', 'no_predecessor'].includes(detail.relation) || !['incomplete_support', 'no_qualifying_overlap'].includes(detail.reason) || !count(detail.missing_counterpart_cells)) throw fail();
    for (const link of transition.links) {
      if (!object(link)) throw fail();
      const source = allNodes.get(link.source_node_id), target = allNodes.get(link.target_node_id);
      if (!source || !target || source.time_index !== from.time_index || target.time_index !== to.time_index || !count(link.shared_cells) || link.shared_cells === 0 || link.shared_cells > Math.min(source.cell_count, target.cell_count) || !finite(link.estimated_overlap_volume_km3) || link.estimated_overlap_volume_km3 <= 0 || !(['source_fraction', 'target_fraction', 'overlap_coefficient'] as const).every(key => finite(link[key]) && Number(link[key]) > 0 && Number(link[key]) <= 1 + 1e-10) || link.overlap_coefficient < result.query.minimum_overlap - 1e-10 || !['continuation', 'split', 'merge', 'ambiguous'].includes(link.classification)) throw fail();
    }
  }
  const summary = result.summary;
  if (summary.frame_count !== result.frames.length || summary.transition_count !== result.transitions.length || summary.node_count !== allNodes.size || summary.link_count !== result.transitions.reduce((total, transition) => total + transition.links.length, 0) || summary.gap_count !== result.transitions.filter(transition => transition.status === 'gap').length || summary.compared_transitions + summary.gap_count !== summary.transition_count || result.sensitivity.length !== (result.query.sensitivity_delta === 0 ? 1 : 3)) throw fail();
  for (const sensitivity of result.sensitivity) {
    if (!object(sensitivity) || !finite(sensitivity.offset) || !finite(sensitivity.threshold) || sensitivity.threshold !== result.query.threshold + sensitivity.offset || !(sensitivity.upper_threshold === null || finite(sensitivity.upper_threshold)) || !validSummary(sensitivity.summary) || !Array.isArray(sensitivity.frames) || sensitivity.frames.length !== result.frames.length || !Array.isArray(sensitivity.transitions) || sensitivity.transitions.length !== result.transitions.length) throw fail();
    if (sensitivity.frames.some((frame, index) => !object(frame) || frame.time_index !== result.frames[index].time_index || frame.time !== result.frames[index].time || !count(frame.region_count) || !count(frame.qualified_cells) || !finite(frame.estimated_volume_km3) || frame.estimated_volume_km3 < 0)) throw fail();
  }
  return result;
}
