import { useEffect, useMemo, useRef, useState } from 'react';
import { useLearningTool, modelSource } from '../learning/bridge';
import { ArrowRight, Bookmark, GitBranch, Info, LoaderCircle, Square } from 'lucide-react';
import { ApiError, type CaseManifest } from '../contracts';
import type { SaveDraft } from '../investigations/contracts';
import { featureVariables, type FeatureVariable } from '../features/contracts';
import { latitudeLabel, longitudeLabel } from '../geography';
import { AnalysisError } from './AnalysisNotice';
import { EvolutionGraph } from './EvolutionGraph';
import { RegionExtent } from './RegionExtent';
import { currentEvolutionMethod, parseEvolution, sameEvolutionQuery, validEvolutionQuery, type EvolutionAnalysis, type EvolutionQuery, type EvolutionRecipe } from './contracts';
import { invalid, number, postAnalysis, utc } from './shared';
import './evolution.css';

type Props = { manifest: CaseManifest; active: boolean; restore?: EvolutionRecipe; restoredAnalysis?: EvolutionAnalysis; onSave: (draft: SaveDraft) => void; onObservation: (id: string) => void; onCase: (id: string) => void };
type Fields = { variable: FeatureVariable; operator: EvolutionQuery['operator']; threshold: string; upper: string; depthMin: string; depthMax: string; start: number; end: number; step: number; overlap: string; sensitivity: string };
const defaultQuery = (manifest: CaseManifest): EvolutionQuery => ({ variable: 'temperature', units: '°C', operator: 'at_least', threshold: 26, upper_threshold: null, depth_min_m: manifest.coordinates.depth_m[0], depth_max_m: 300, start_index: 0, end_index: manifest.coordinates.times.length - 1, frame_step: 1, minimum_overlap: .1, sensitivity_delta: .25 });
const fields = (query: EvolutionQuery): Fields => ({ variable: query.variable, operator: query.operator, threshold: String(query.threshold), upper: String(query.upper_threshold ?? query.threshold + 2), depthMin: String(query.depth_min_m), depthMax: String(query.depth_max_m), start: query.start_index, end: query.end_index, step: query.frame_step, overlap: String(query.minimum_overlap), sensitivity: String(query.sensitivity_delta) });
const queryOf = (value: Fields): EvolutionQuery => ({ variable: value.variable, units: featureVariables[value.variable].units, operator: value.operator, threshold: Number(value.threshold), upper_threshold: value.operator === 'between' ? Number(value.upper) : null, depth_min_m: Number(value.depthMin), depth_max_m: Number(value.depthMax), start_index: value.start, end_index: value.end, frame_step: value.step, minimum_overlap: Number(value.overlap), sensitivity_delta: Number(value.sensitivity) });
const condition = (query: EvolutionQuery) => `${featureVariables[query.variable].label} ${query.operator === 'at_least' ? 'at least' : query.operator === 'at_most' ? 'at most' : 'between'} ${number(query.threshold)}${query.upper_threshold === null ? '' : ` and ${number(query.upper_threshold)}`} ${query.units}, ${number(query.depth_min_m)} to ${number(query.depth_max_m)} m`;

export function EvolutionWorkspace({ manifest, active, restore, restoredAnalysis, onSave, onObservation, onCase }: Props) {
  const [draft, setDraft] = useState<Fields>(() => fields(restore?.query ?? defaultQuery(manifest)));
  const [result, setResult] = useState<EvolutionAnalysis | null>(restoredAnalysis ?? null), [busy, setBusy] = useState(false), [error, setError] = useState<Error | null>(null), [notice, setNotice] = useState('');
  const [selection, setSelection] = useState(restore?.selected_node ?? ''), [frameIndex, setFrameIndex] = useState(restore?.selected_node ? Number(restore.selected_node.split(':')[0].slice(1)) : 0);
  const generation = useRef(0), controller = useRef<AbortController | null>(null), initialized = useRef(Boolean(restoredAnalysis)), pending = useRef<EvolutionQuery | null>(null);
  const query = useMemo(() => queryOf(draft), [draft]), changed = Boolean(result && !sameEvolutionQuery(result.query, query));
  const frame = result?.frames.find(item => item.time_index === frameIndex) ?? result?.frames[0];
  const selected = frame?.regions.find(node => node.node_id === selection) ?? frame?.regions[0];
  const relatedTransitions = result?.transitions.filter(transition => transition.from_time_index === selected?.time_index || transition.to_time_index === selected?.time_index) ?? [];
  const links = relatedTransitions.flatMap(transition => transition.links).filter(link => link.source_node_id === selected?.node_id || link.target_node_id === selected?.node_id);
  useLearningTool('evolution',active,{
    tool:'evolution',caseId:manifest.case.id,status:error?'error':busy||!result?'loading':'ready',title:'How threshold regions change',kind:'derived',
    facts:[{label:'Source frames',value:result?.summary.frame_count??null},{label:'Overlap links',value:result?.summary.link_count??null},{label:'Splits',value:result?.summary.split_count??null},{label:'Merges',value:result?.summary.merge_count??null}],parameters:result?{threshold:result.query.threshold,minimum_overlap:result.query.minimum_overlap,start_index:result.query.start_index,end_index:result.query.end_index}:{},sources:[modelSource(manifest.case.id)],limits:['Links mean native-region overlap under a stated rule. They do not trace the same water.','Splits, merges, missing support and sensitivity remain explicit.'],message:error?.message,
  },command=>{if(command.action==='inspect'){if(error&&!busy)void calculate(pending.current??defaultQuery(manifest));return true;}throw new Error('This evolution action is not supported.');});
  useEffect(() => () => { generation.current++; controller.current?.abort(); }, []);
  useEffect(() => { if (active && !initialized.current) { initialized.current = true; void calculate(restore?.query ?? defaultQuery(manifest)); } }, [active]);
  async function calculate(request: EvolutionQuery) {
    const current = ++generation.current, abort = new AbortController();
    controller.current?.abort(); controller.current = abort; pending.current = request;
    setBusy(true); setError(null); setNotice('');
    try {
      const analysis = await postAnalysis(`/api/cases/${encodeURIComponent(manifest.case.id)}/evolution/run`, request, parseEvolution, abort.signal);
      if (current !== generation.current) return;
      if (analysis.method_version !== currentEvolutionMethod) throw new ApiError('The evolution service returned an earlier scientific method. Reload the workspace before calculating again. Your previous verified result is kept.', undefined, 'update');
      if (analysis.case_id !== manifest.case.id || !sameEvolutionQuery(analysis.query, request) || analysis.frames.some(item => item.time !== manifest.coordinates.times[item.time_index]) || JSON.stringify(analysis.coordinates.latitude) !== JSON.stringify(manifest.coordinates.latitude) || JSON.stringify(analysis.coordinates.longitude) !== JSON.stringify(manifest.coordinates.longitude)) throw invalid('feature evolution');
      setResult(analysis); setDraft(current => sameEvolutionQuery(queryOf(current), request) ? fields(analysis.query) : current);
      const available = analysis.frames.flatMap(item => item.regions), preferred = available.find(node => node.node_id === restore?.selected_node) ?? available.find(node => node.node_id === analysis.transitions.flatMap(item => item.links).find(link => link.classification === 'split' || link.classification === 'merge' || link.classification === 'ambiguous')?.source_node_id) ?? available[0];
      setSelection(preferred?.node_id ?? ''); setFrameIndex(preferred?.time_index ?? analysis.frames[0].time_index);
      setNotice('Evolution updated. Every link uses the displayed overlap rule and original source times.');
    } catch (caught) { if (current === generation.current) setError(caught instanceof Error ? caught : new Error('Feature evolution could not finish.')); }
    finally { if (current === generation.current) { setBusy(false); controller.current = null; } }
  }
  function cancel() { generation.current++; controller.current?.abort(); controller.current = null; setBusy(false); setNotice('Calculation cancelled. Your completed evolution is kept.'); }
  function update<K extends keyof Fields>(key: K, value: Fields[K]) { setDraft(current => ({ ...current, [key]: value })); setError(null); }
  function chooseNode(id: string) { const node = result?.frames.flatMap(item => item.regions).find(item => item.node_id === id); if (node) { setSelection(id); setFrameIndex(node.time_index); } }
  function run(event: React.FormEvent) {
    event.preventDefault();
    if (![draft.threshold, draft.depthMin, draft.depthMax, draft.overlap, draft.sensitivity, ...(draft.operator === 'between' ? [draft.upper] : [])].every(value => value.trim() !== '') || !validEvolutionQuery(query) || query.depth_min_m < manifest.coordinates.depth_m[0] || query.depth_max_m > manifest.coordinates.depth_m.at(-1)! || (query.end_index - query.start_index) % query.frame_step !== 0) { setError(new Error('Choose finite values, increasing depths and at least two available frames. The frame step must reach the end frame exactly.')); return; }
    void calculate(query);
  }
  const save = () => result && onSave({ recipe: { mode: 'evolution', case_id: manifest.case.id, query: result.query, selected_node: selected?.node_id ?? null }, expected_model_sha256: result.manifest_sha256, expected_observation_library_sha256: result.observation_library_sha256 });
  return <section className="p14-workspace" aria-label="Feature evolution workspace">
    <header className="p14-heading"><div><span className="eyebrow">FOLLOW STRUCTURES / HISTORICAL MODEL</span><h2>See how a structure changes with time</h2><p>Keep one threshold and compare the native regions in successive snapshots. Inspect branches, disappearing regions and gaps, then check what a nearby threshold changes.</p></div><button className="secondary-button" onClick={save} disabled={!result || busy || changed || Boolean(error)}><Bookmark size={16}/>Save investigation</button></header>
    <div className="p14-scope"><Info size={19}/><p>Regions are connected cells meeting a condition. Their overlap is a correspondence rule, not proof that the same water moved between them. The historical model and original observations retain separate roles.</p></div>
    <div className="p14-content"><div className="p14-steps"><span><b>1</b>Set the condition</span><span><b>2</b>Follow the branches</span><span><b>3</b>Test the threshold</span></div>
      {manifest.case.id !== 'arabian-sea-2024-01' && <div className="p14-applied"><p>The Bay case can remain one connected region under this condition. The Arabian Sea case has real split and merge examples using the same 26 °C threshold.</p><button className="secondary-button" onClick={() => onCase('arabian-sea-2024-01')}>Open Arabian Sea branching case <ArrowRight size={15}/></button></div>}
      <form className="p14-form" onSubmit={run} aria-label="Feature evolution settings">
        <label>Variable<select aria-label="Evolution variable" value={draft.variable} onChange={event => { const variable = event.target.value as FeatureVariable; setDraft(current => ({ ...current, variable, threshold: String(featureVariables[variable].threshold), upper: String(featureVariables[variable].threshold + 1), sensitivity: variable === 'temperature' ? '.25' : variable === 'salinity' ? '.1' : '.01' })); }}>{Object.entries(featureVariables).filter(([id]) => id === 'horizontal_kinetic_energy' || manifest.case.variables.includes(id as 'temperature')).map(([id, variable]) => <option value={id} key={id}>{variable.label}</option>)}</select></label>
        <label>Condition<select aria-label="Evolution threshold condition" value={draft.operator} onChange={event => update('operator', event.target.value as Fields['operator'])}><option value="at_least">At least</option><option value="at_most">At most</option><option value="between">Between, inclusive</option></select></label>
        <label>{draft.operator === 'between' ? 'Lower threshold' : 'Threshold'} ({featureVariables[draft.variable].units})<input aria-label="Evolution threshold" type="number" step="any" value={draft.threshold} onChange={event => update('threshold', event.target.value)} required/></label>
        {draft.operator === 'between' && <label>Upper threshold ({featureVariables[draft.variable].units})<input aria-label="Evolution upper threshold" type="number" step="any" value={draft.upper} onChange={event => update('upper', event.target.value)} required/></label>}
        <label>First source frame<select aria-label="Evolution first frame" value={draft.start} onChange={event => update('start', Number(event.target.value))}>{manifest.coordinates.times.map((time, index) => <option key={time} value={index}>{utc(time)}</option>)}</select></label>
        <label>Last source frame<select aria-label="Evolution last frame" value={draft.end} onChange={event => update('end', Number(event.target.value))}>{manifest.coordinates.times.map((time, index) => <option key={time} value={index}>{utc(time)}</option>)}</select></label>
        <label>Nearby threshold difference ({featureVariables[draft.variable].units})<input aria-label="Evolution threshold sensitivity" type="number" min="0" max="100" step="any" value={draft.sensitivity} onChange={event => update('sensitivity', event.target.value)} required/></label>
        <details><summary>Depth limits, overlap rule and time gaps</summary><div className="p14-advanced-grid"><label>Minimum depth (m)<input aria-label="Evolution minimum depth" type="number" step="any" value={draft.depthMin} onChange={event => update('depthMin', event.target.value)} required/></label><label>Maximum depth (m)<input aria-label="Evolution maximum depth" type="number" step="any" value={draft.depthMax} onChange={event => update('depthMax', event.target.value)} required/></label><label>Minimum overlap fraction<input aria-label="Evolution minimum overlap" type="number" min="0.000001" max="1" step="any" value={draft.overlap} onChange={event => update('overlap', event.target.value)} required/></label><label>Selected frame spacing<select aria-label="Evolution frame spacing" value={draft.step} onChange={event => update('step', Number(event.target.value))}><option value="1">Every source frame, 12 hours</option><option value="2">Every second frame, 24 hours</option><option value="3">Every third frame, 36 hours</option><option value="6">First and last, 72 hours</option></select></label><p className="p14-note">Overlap is the shared estimated cell volume divided by the smaller region's volume. A value of 0.1 means at least 10% under this rule, not a confidence score. Skipped source frames create explicit gaps; the method does not bridge them.</p></div></details>
        <div className="p14-actions"><button className="primary-button" type="submit" disabled={busy}>{busy ? <LoaderCircle className="spin" size={16}/> : <GitBranch size={16}/>}Compare source frames</button></div>
      </form>
      {changed && <p className="p14-applied" role="status">The controls differ from the completed analysis. Compare source frames to apply them. The diagram and numerical results below still use their printed condition.</p>}
      {busy && <div className="p14-progress" role="status"><LoaderCircle className="spin" size={19}/><span>Finding native regions and checking their overlaps at the selected threshold choices. Your completed result stays visible.</span><button className="secondary-button" onClick={cancel}><Square size={14}/>Cancel calculation</button></div>}
      {notice && <p className="p14-note" role="status">{notice}</p>}{error && <AnalysisError error={error} retry={() => void calculate(pending.current ?? query)}/>}
      {!result && !busy && !error && <div className="p14-empty"><h3>Choose a condition to follow</h3><p>The graph will retain source timestamps, branches and missing intervals.</p></div>}
      {result && <>
        <section className="p14-card" aria-label="Applied feature evolution"><div className="p14-card-heading"><div><h3>Follow the selected region</h3><p>{condition(result.query)}<br/>{utc(result.frames[0].time)} to {utc(result.frames.at(-1)!.time)}<br/>Minimum overlap: {number(result.query.minimum_overlap * 100)}% of the smaller estimated region volume.</p></div><span className="p14-badge">Native grid · {result.frames.length} snapshots</span></div>
          <dl className="p14-inline-metrics"><div><dt>Split groups</dt><dd>{result.summary.split_count}</dd></div><div><dt>Merge groups</dt><dd>{result.summary.merge_count}</dd></div><div><dt>Ambiguous groups</dt><dd>{result.summary.ambiguous_count}</dd></div><div><dt>Unbridged time gaps</dt><dd>{result.summary.gap_count}</dd></div></dl>
          <EvolutionGraph result={result} selected={selected?.node_id ?? ''} onSelect={chooseNode}/>
          <div className="p14-picker"><label>Inspect source frame<select aria-label="Inspect evolution frame" value={frame?.time_index ?? ''} onChange={event => { const value = Number(event.target.value); setFrameIndex(value); setSelection(result.frames.find(item => item.time_index === value)?.regions[0]?.node_id ?? ''); }}>{result.frames.map(item => <option key={item.time_index} value={item.time_index}>{utc(item.time)} · {item.total_regions} {item.total_regions === 1 ? 'region' : 'regions'}</option>)}</select></label><label>Inspect native region<select aria-label="Inspect evolution region" value={selected?.node_id ?? ''} disabled={!frame?.regions.length} onChange={event => chooseNode(event.target.value)}>{!frame?.regions.length && <option value="">No regions meet this condition</option>}{frame?.regions.map(node => <option key={node.node_id} value={node.node_id}>{node.node_id} · {number(node.cell_count, 0)} {node.cell_count === 1 ? 'cell' : 'cells'} · {number(node.estimated_volume_km3)} km³</option>)}</select></label></div>
        </section>
        {selected && <div className="p14-two-columns"><section className="p14-card" aria-label="Evolution region extent"><div className="p14-card-heading"><div><h3>Where this region exists</h3><p>{selected.node_id} · {utc(frame!.time)}</p></div></div><RegionExtent result={result} node={selected}/><div className="p14-card-body"><dl className="p14-facts"><div><dt>Native-centre depths</dt><dd>{number(selected.center_bounds.depth_min_m)} to {number(selected.center_bounds.depth_max_m)} m</dd></div><div><dt>Estimated cell volume</dt><dd>{number(selected.estimated_volume_km3)} km³</dd></div><div><dt>Variable range</dt><dd>{number(selected.min)} to {number(selected.max)} {result.query.units}</dd></div><div><dt>Centre longitude span</dt><dd>{longitudeLabel(selected.center_bounds.west, 3)} to {longitudeLabel(selected.center_bounds.east, 3)}</dd></div><div><dt>Centre latitude span</dt><dd>{latitudeLabel(selected.center_bounds.south, 3)} to {latitudeLabel(selected.center_bounds.north, 3)}</dd></div><div><dt>Eligible observation samples</dt><dd>{selected.eligible_samples} in {selected.eligible_profiles} {selected.eligible_profiles === 1 ? 'profile' : 'profiles'}</dd></div></dl>{(selected.touches_domain_boundary || selected.touches_missing_values) && <p className="p14-applied">This region touches {selected.touches_domain_boundary ? 'the supplied domain boundary' : ''}{selected.touches_domain_boundary && selected.touches_missing_values ? ' and ' : ''}{selected.touches_missing_values ? 'missing source values' : ''}. Its full extent outside the available field is unknown.</p>}{selected.selection_depth_contacts.length > 0 && <p className="p14-note">Touches the {selected.selection_depth_contacts.join(" and ")} depth limit of this query. Selected depth limits are separate from the supplied data boundary.</p>}</div></section>
          <section className="p14-card" aria-label="Evolution link inspector"><div className="p14-card-heading"><div><h3>Why it connects, or stops</h3><p>Inspect each accepted candidate link. Region names are frame-specific.</p></div></div><div className="p14-card-body"><ul className="p14-detail-list">{links.map(link => <li key={`${link.source_node_id}/${link.target_node_id}`}><span className={`p14-badge ${link.classification === 'ambiguous' ? 'uncertain' : ''}`}>{link.classification}</span><p><strong>{link.source_node_id} → {link.target_node_id}</strong><br/>{number(link.shared_cells, 0)} shared native {link.shared_cells === 1 ? 'cell' : 'cells'}; {number(link.estimated_overlap_volume_km3)} km³ estimated overlap.<br/>{number(link.source_fraction * 100, 2)}% of the source region and {number(link.target_fraction * 100, 2)}% of the target region.</p><button className="secondary-button" onClick={() => chooseNode(link.source_node_id === selected.node_id ? link.target_node_id : link.source_node_id)}>Inspect connected region <ArrowRight size={14}/></button></li>)}</ul>{links.length === 0 && <p className="p14-note">This region has no accepted links in the selected window.</p>}{relatedTransitions.map(transition => { const details = transition.unmatched_details.filter(detail => detail.node_id === selected.node_id); return transition.status === 'gap' ? <p className="p14-applied" key={`${transition.from_time_index}-${transition.to_time_index}`}>{number(transition.elapsed_hours)}-hour gap between {utc(transition.from_time)} and {utc(transition.to_time)}. {transition.reason}</p> : details.map(detail => <p className="p14-applied" key={`${transition.from_time_index}-${detail.node_id}`}><strong>{detail.relation === 'no_successor' ? 'No successor' : 'No predecessor'} under this rule.</strong> {detail.reason === 'incomplete_support' ? `${detail.missing_counterpart_cells} counterpart cells are missing. Correspondence is unresolved; disappearance is not established.` : 'No region in the adjacent frame passes the overlap threshold. This does not prove physical destruction or transport.'}</p>); })}<h4>Observations at this frame</h4><p className="p14-note">Eligible under the existing QC and matching gates. Association is context, not independent model validation.</p>{selected.observations.length ? <ul className="p14-detail-list">{selected.observations.map(observation => <li key={observation.profile_id}><strong>{observation.platform}</strong><br/>{observation.sample_count} eligible {observation.sample_count === 1 ? 'sample' : 'samples'}<button className="secondary-button" onClick={() => onObservation(observation.profile_id)}>Inspect original profile <ArrowRight size={14}/></button></li>)}</ul> : <p className="p14-note">No eligible observation samples are associated with this region at this model time.</p>}</div></section></div>}
        <section className="p14-card" aria-label="Evolution sensitivity comparison"><div className="p14-card-heading"><div><h3>Does a nearby threshold change the story?</h3><p>Each row reruns every selected frame. Branch counts depend on the chosen condition and overlap rule.</p></div></div><div className="p14-table-scroll" tabIndex={0} role="region" aria-label="Threshold sensitivity results"><table><thead><tr><th scope="col">Threshold ({result.query.units})</th><th scope="col">Region instances</th><th scope="col">Split groups</th><th scope="col">Merge groups</th><th scope="col">Ambiguous groups</th><th scope="col">Appearances / disappearances</th></tr></thead><tbody>{result.sensitivity.map(trial => <tr key={trial.offset} aria-selected={trial.offset === 0}><th scope="row">{number(trial.threshold)}{trial.upper_threshold === null ? '' : ` to ${number(trial.upper_threshold)}`}<small>{trial.offset === 0 ? 'Applied threshold' : `${trial.offset > 0 ? '+' : ''}${number(trial.offset)} ${result.query.units}`}</small></th><td>{trial.summary.node_count}</td><td>{trial.summary.split_count}</td><td>{trial.summary.merge_count}</td><td>{trial.summary.ambiguous_count}</td><td>{trial.summary.appearance_count} / {trial.summary.disappearance_count}</td></tr>)}</tbody></table></div><p className="p14-chart-caption">Unmatched regions with missing counterpart values are reported as unresolved. Time gaps are never bridged. These counts are rule-dependent outcomes, not probabilities.</p></section>
        <details className="p14-methods"><summary>Inspect every transition, sources and scientific method</summary><div className="p14-table-scroll" tabIndex={0} role="region" aria-label="All source transitions"><table><thead><tr><th scope="col">From (UTC)</th><th scope="col">To (UTC)</th><th scope="col">Elapsed</th><th scope="col">Result</th><th scope="col">Unresolved endpoints</th></tr></thead><tbody>{result.transitions.map(transition => <tr key={transition.from_time_index}><td>{utc(transition.from_time)}</td><td>{utc(transition.to_time)}</td><td>{number(transition.elapsed_hours)} h</td><td>{transition.status === 'gap' ? 'Gap: no inferred links' : `${transition.links.length} accepted overlap links`}</td><td>{transition.source_unresolved_node_ids.length + transition.target_unresolved_node_ids.length}</td></tr>)}</tbody></table></div><ul>{result.methods.map(method => <li key={method}>{method}</li>)}</ul><ul>{result.limitations.map(limit => <li key={limit}>{limit}</li>)}</ul><p>Model: {manifest.case.source_label}<br/>Method: {result.method_version}</p><p>Model manifest SHA-256: <code>{result.manifest_sha256}</code><br/>Observation library SHA-256: <code>{result.observation_library_sha256}</code></p></details>
      </>}
    </div>
  </section>;
}
