import { useEffect, useMemo, useRef, useState } from 'react';
import { useLearningTool, modelSource } from '../learning/bridge';
import { ArrowRight, Bookmark, Info, LoaderCircle, Radio, RotateCcw, Square } from 'lucide-react';
import type { CaseManifest } from '../contracts';
import type { SaveDraft } from '../investigations/contracts';
import type { MatchSettings } from '../evidence/contracts';
import { reasonLabel } from '../evidence/contracts';
import type { InstrumentSummary } from '../instruments/contracts';
import { AnalysisError } from '../evolution/AnalysisNotice';
import { invalid, number, postAnalysis, utc } from '../evolution/shared';
import { BlackoutDepths } from './BlackoutDepths';
import { clearExclusions, parseBlackout, sameBlackoutQuery, type BlackoutAnalysis, type BlackoutQuery, type BlackoutRecipe } from './contracts';
import '../evolution/evolution.css';

type Props = { manifest: CaseManifest; active: boolean; restore?: BlackoutRecipe; restoredAnalysis?: BlackoutAnalysis; onSave: (draft: SaveDraft) => void; onObservation: (id: string) => void };
const instrumentNames: Record<InstrumentSummary['instrument'], string> = { argo: 'Argo floats', bgc: 'BGC Argo floats', ctd: 'Ship CTD profiles', glider: 'Glider profiles' };
const defaultQuery = (manifest: CaseManifest): BlackoutQuery => ({ settings: { variable: 'temperature', time_index: Math.min(1, manifest.coordinates.times.length - 1), time_window_hours: 6, distance_km: 5, max_vertical_gap_m: 500, qc: 'good_probably_good' }, excluded_profile_ids: [], excluded_instruments: [], excluded_platforms: [], excluded_collections: [] });
type SelectionKey = 'excluded_profile_ids' | 'excluded_instruments' | 'excluded_platforms' | 'excluded_collections';
const selector = (query: BlackoutQuery, profile: InstrumentSummary) => query.excluded_profile_ids.includes(profile.id) || query.excluded_instruments.includes(profile.instrument) || query.excluded_platforms.includes(profile.platform) || query.excluded_collections.includes(profile.collection);

export function BlackoutWorkspace({ manifest, active, restore, restoredAnalysis, onSave, onObservation }: Props) {
  const [draft, setDraft] = useState<BlackoutQuery>(restore?.query ?? defaultQuery(manifest));
  const [result, setResult] = useState<BlackoutAnalysis | null>(restoredAnalysis ?? null), [busy, setBusy] = useState(false), [error, setError] = useState<Error | null>(null), [notice, setNotice] = useState('');
  const generation = useRef(0), controller = useRef<AbortController | null>(null), initialized = useRef(Boolean(restoredAnalysis)), pending = useRef<BlackoutQuery | null>(null);
  const changed = Boolean(result && !sameBlackoutQuery(result.query, draft)), profiles = result?.baseline.profiles ?? [];
  const groups = useMemo(() => ({ instruments: [...new Set(profiles.map(profile => profile.profile.instrument))].sort(), platforms: [...new Set(profiles.map(profile => profile.profile.platform))].sort(), collections: [...new Set(profiles.map(profile => profile.profile.collection))].sort() }), [result]);
  const affected = result?.profile_effects.filter(effect => effect.excluded_by_user) ?? [];
  const selectedCount = profiles.filter(profile => selector(draft, profile.profile)).length;
  const monthly = manifest.representations?.temporal_support?.kind === 'calendar_month_mean';
  function modelTime(index: number) { const interval = manifest.representations?.temporal_support?.intervals[index]; return monthly && interval ? `${utc(interval[0])} to ${utc(interval[1])} (end exclusive)` : utc(manifest.coordinates.times[index]); }
  useEffect(() => () => { generation.current++; controller.current?.abort(); }, []);
  useEffect(() => { if (active && !initialized.current) { initialized.current = true; void calculate(restore?.query ?? defaultQuery(manifest)); } }, [active]);
  async function calculate(query: BlackoutQuery) {
    const current = ++generation.current, abort = new AbortController();
    controller.current?.abort(); controller.current = abort; pending.current = query;
    setBusy(true); setError(null); setNotice('');
    try {
      const analysis = await postAnalysis(`/api/cases/${encodeURIComponent(manifest.case.id)}/blackout/run`, query, parseBlackout, abort.signal);
      if (current !== generation.current) return;
      if (analysis.case_id !== manifest.case.id || !sameBlackoutQuery(analysis.query, query) || analysis.baseline.model_time !== manifest.coordinates.times[query.settings.time_index]) throw invalid('observation blackout');
      setResult(analysis); setDraft(current => sameBlackoutQuery(current, query) ? analysis.query : current);
      setNotice(analysis.removed_profiles ? 'Rehearsal updated. Only the selected observation evidence changed; the model and source quality flags are unchanged.' : 'Original evidence loaded. Choose an instrument or profile to rehearse its absence.');
    } catch (caught) { if (current === generation.current) setError(caught instanceof Error ? caught : new Error('The observation blackout could not finish.')); }
    finally { if (current === generation.current) { setBusy(false); controller.current = null; } }
  }
  function cancel() { generation.current++; controller.current?.abort(); controller.current = null; setBusy(false); setNotice('Calculation cancelled. Your completed rehearsal is kept.'); }
  function setting<K extends keyof MatchSettings>(key: K, value: MatchSettings[K]) { setDraft(current => ({ ...current, settings: { ...current.settings, [key]: value } })); setError(null); }
  function toggle(key: SelectionKey, id: string, checked: boolean) { setDraft(current => ({ ...current, [key]: (checked ? [...new Set([...current[key], id])] : current[key].filter(item => item !== id)).sort() })); setError(null); }
  function save(original = false) { if (result) onSave({ recipe: { mode: 'blackout', case_id: manifest.case.id, query: original ? clearExclusions(result.query) : result.query }, expected_model_sha256: result.manifest_sha256, expected_observation_library_sha256: result.observation_library_sha256 }); }
  const eligibleExample = profiles.find(profile => profile.matched_count > 0);
  useLearningTool('blackout',active,{
    tool:'blackout',caseId:manifest.case.id,status:error?'error':busy||!result?'loading':'ready',title:'Evidence with one profile removed',kind:'derived',
    facts:[{label:'Original eligible pairs',value:result?.baseline.matched_samples??null},{label:'Remaining eligible pairs',value:result?.modified.matched_samples??null},{label:'Lost eligible pairs',value:result?.removed_eligible_samples??null},{label:'Excluded profiles',value:result?.removed_profiles??null}],parameters:{excluded_profiles:result?.excluded_profile_ids.join(', ')??'',model_unchanged:true},sources:[modelSource(manifest.case.id)],limits:['Only observation evidence is excluded. The historical model is unchanged.','Losing comparison coverage does not measure forecast degradation.'],message:error?.message,
  },async(command,signal)=>{
    if(command.action==='inspect')return true;
    if(command.action==='exclude'){
      if(!result&&error&&!busy){await calculate(defaultQuery(manifest));return false;}
      if(!result||busy)return false;if(!eligibleExample)throw new Error('No eligible profile can be excluded in this example.');
      const q={...clearExclusions(result.query),excluded_profile_ids:[eligibleExample.profile.id]};setDraft(q);
      signal.addEventListener('abort',cancel,{once:true});try{await calculate(q);return true;}finally{signal.removeEventListener('abort',cancel);}
    }
    throw new Error('This blackout action is not supported.');
  });
  return <section className="p14-workspace" aria-label="Observation blackout workspace">
    <header className="p14-heading"><div><span className="eyebrow">REHEARSE MISSING OBSERVATIONS</span><h2>What evidence disappears if a sensor is missing?</h2><p>Exclude an instrument, platform or original profile. Compare the eligible evidence before and after, and inspect exactly which sample comparisons disappear.</p></div><button className="secondary-button" disabled={!result || busy || changed || Boolean(error)} onClick={() => save()}><Bookmark size={16}/>Save investigation</button></header>
    <div className="p14-scope"><Info size={19}/><p>This is an evidence exclusion rehearsal. It does not rerun the ocean model or remove observations previously assimilated into that model. Source files, quality flags and the historical field remain unchanged.</p></div>
    <div className="p14-content"><div className="p14-steps"><span><b>1</b>Choose the source time</span><span><b>2</b>Exclude observations</span><span><b>3</b>Inspect lost evidence</span></div>
      <form className="p14-form" aria-label="Observation blackout settings" onSubmit={event => { event.preventDefault(); void calculate(draft); }}>
        <label>Comparison variable<select aria-label="Blackout variable" value={draft.settings.variable} onChange={event => setting('variable', event.target.value as MatchSettings['variable'])}><option value="temperature">{manifest.representations?.temporal_support?.kind === "calendar_month_mean" ? "Temperature comparison" : "In-situ temperature"}</option><option value="salinity" disabled={!manifest.case.variables.includes("salinity")}>Practical salinity{!manifest.case.variables.includes("salinity") ? " (not supplied by model)" : ""}</option></select></label>
        <label>{monthly ? 'Model averaging period (UTC)' : 'Model snapshot (UTC)'}<select aria-label={monthly ? 'Blackout model period' : 'Blackout model snapshot'} value={draft.settings.time_index} onChange={event => setting('time_index', Number(event.target.value))}>{manifest.coordinates.times.map((time, index) => <option key={time} value={index}>{modelTime(index)}</option>)}</select></label>
        <label>Quality flags<select aria-label="Blackout quality flags" value={draft.settings.qc} onChange={event => setting('qc', event.target.value as MatchSettings['qc'])}><option value="good_probably_good">Good or probably good</option><option value="good">Good only</option></select></label>
        <details><summary>Matching rules</summary><div className="p14-advanced-grid"><label>Time window, plus or minus (h)<input aria-label="Blackout time window" type="number" min="0" max="72" step="any" value={draft.settings.time_window_hours} onChange={event => setting('time_window_hours', Number(event.target.value))} required/></label><label>Maximum column distance (km)<input aria-label="Blackout distance limit" type="number" min="0" max="50" step="any" value={draft.settings.distance_km} onChange={event => setting('distance_km', Number(event.target.value))} required/></label><label>Maximum vertical bracket (m)<input aria-label="Blackout vertical gap" type="number" min="1" max="1000" step="any" value={draft.settings.max_vertical_gap_m} onChange={event => setting('max_vertical_gap_m', Number(event.target.value))} required/></label><p className="p14-note">The original and modified results use the same physical definitions, time, distance, depth and QC gates. Removing a profile that has no eligible comparisons cannot reduce the eligible-pair total.</p></div></details>
        {result && <fieldset><legend>Exclude instrument groups</legend><div className="p14-choice-grid">{groups.instruments.map(instrument => <label className="p14-check p14-choice" key={instrument}><input aria-label={`Exclude ${instrumentNames[instrument]}`} type="checkbox" checked={draft.excluded_instruments.includes(instrument)} onChange={event => toggle('excluded_instruments', instrument, event.target.checked)}/><span><strong>{instrumentNames[instrument]}</strong><small>{profiles.filter(profile => profile.profile.instrument === instrument).length} original {profiles.filter(profile => profile.profile.instrument === instrument).length === 1 ? 'profile' : 'profiles'}</small></span></label>)}</div><p className="p14-note">Checked means excluded from this rehearsal. Overlapping selections remove a profile only once.</p></fieldset>}
        {result && <details><summary>Choose individual profiles, platforms or collections</summary><h4>Original profiles</h4><div className="p14-choice-grid">{profiles.map(profile => <label className="p14-check p14-choice" key={profile.profile.id}><input aria-label={`Exclude profile ${profile.profile.id}`} type="checkbox" checked={draft.excluded_profile_ids.includes(profile.profile.id)} onChange={event => toggle('excluded_profile_ids', profile.profile.id, event.target.checked)}/><span><strong>{profile.profile.instrument.toUpperCase()} {profile.profile.platform}</strong><small>{utc(profile.profile.time)}{profile.profile.time_end !== profile.profile.time ? ` to ${utc(profile.profile.time_end)}` : ''}<br/>{profile.matched_count} eligible pairs under the last applied matching rules.{selector(draft, profile.profile) && !draft.excluded_profile_ids.includes(profile.profile.id) ? ' Selected through a group.' : ''}</small></span></label>)}</div><h4>Platforms</h4><div className="p14-choice-grid">{groups.platforms.map(platform => <label className="p14-check p14-choice" key={platform}><input aria-label={`Exclude platform ${platform}`} type="checkbox" checked={draft.excluded_platforms.includes(platform)} onChange={event => toggle('excluded_platforms', platform, event.target.checked)}/><span>{platform}</span></label>)}</div><h4>Source collections</h4><div className="p14-choice-grid">{groups.collections.map(collection => <label className="p14-check p14-choice" key={collection}><input aria-label={`Exclude collection ${collection}`} type="checkbox" checked={draft.excluded_collections.includes(collection)} onChange={event => toggle('excluded_collections', collection, event.target.checked)}/><span>{collection}</span></label>)}</div></details>}
        <div className="p14-actions"><button className="primary-button" type="submit" disabled={busy}>{busy ? <LoaderCircle className="spin" size={16}/> : <Radio size={16}/>}Apply observation blackout</button><button className="secondary-button" type="button" disabled={busy || !result} onClick={() => { setDraft(clearExclusions(draft)); setError(null); }}><RotateCcw size={15}/>Clear exclusions</button>{eligibleExample && <button className="secondary-button" type="button" disabled={busy} onClick={() => { setDraft({ ...clearExclusions(draft), excluded_profile_ids: [eligibleExample.profile.id] }); setNotice(`Selected ${eligibleExample.profile.platform}. Apply observation blackout to recompute evidence.`); }}>Select one contributing profile</button>}</div>
        {result && <p className="p14-note" aria-label="Draft blackout selection">{selectedCount} of {profiles.length} original profiles selected for exclusion. Apply to update the evidence.</p>}
      </form>
      {monthly && <p className="p14-applied" aria-label="Monthly blackout quantity limits">This model supplies monthly potential temperature. It is not directly comparable with instantaneous in-situ temperature observations. Original Argo profiles remain inspectable, but this case has no eligible temperature residuals under the stated matching rules. Excluding a profile does not make these quantities compatible.</p>}
      {changed && <p className="p14-applied" role="status">The controls differ from the completed rehearsal. Apply observation blackout to update the results below.</p>}
      {busy && <div className="p14-progress" role="status"><LoaderCircle className="spin" size={19}/><span>Checking original eligibility and recomputing coverage for the retained observations. Your completed result stays visible.</span><button className="secondary-button" onClick={cancel}><Square size={14}/>Cancel calculation</button></div>}
      {notice && <p className="p14-note" role="status">{notice}</p>}{error && <AnalysisError error={error} retry={() => void calculate(pending.current ?? draft)}/>}
      {result && <>
        <section className="p14-card" aria-label="Applied observation blackout"><div className="p14-card-heading"><div><h3>Same model, different available evidence</h3><p>{monthly ? 'Monthly potential-temperature model field' : result.query.settings.variable === 'temperature' ? 'In-situ temperature' : 'Practical salinity'} · {modelTime(result.query.settings.time_index)}<br/>Matching: ±{number(result.query.settings.time_window_hours)} h, {number(result.query.settings.distance_km)} km, depth brackets up to {number(result.query.settings.max_vertical_gap_m)} m.</p></div><span className="p14-badge">Model unchanged</span></div><div className="p14-card-body"><div className="p14-stat-pair"><div><span>Original eligible pairs</span><strong aria-label="Original eligible pairs">{result.baseline.matched_samples}</strong><small>From {result.baseline.matched_profiles} eligible {result.baseline.matched_profiles === 1 ? 'profile' : 'profiles'} in the checked library.</small></div><div><span>Remaining eligible pairs</span><strong aria-label="Remaining eligible pairs">{result.modified.matched_samples}</strong><small>{result.removed_eligible_samples} eligible {result.removed_eligible_samples === 1 ? 'pair' : 'pairs'} removed from {result.removed_eligible_profiles} contributing {result.removed_eligible_profiles === 1 ? 'profile' : 'profiles'}.</small></div></div><p className="p14-note">Excluded {result.removed_profiles} original {result.removed_profiles === 1 ? 'profile' : 'profiles'} containing {result.removed_samples} source {result.removed_samples === 1 ? 'sample' : 'samples'}. {result.removed_eligible_samples} of those source samples {result.removed_eligible_samples === 1 ? 'was an eligible model comparison' : 'were eligible model comparisons'}. User exclusions are kept separate from scientific QC and matching exclusions.</p><div className="p14-actions"><button className="secondary-button" disabled={busy || changed || Boolean(error)} onClick={() => save(true)}><Bookmark size={15}/>Save original evidence</button><button className="secondary-button" disabled={busy || changed || Boolean(error)} onClick={() => save()}><Bookmark size={15}/>Save modified evidence</button></div></div></section>
        <section className="p14-card" aria-label="Blackout eligible depths"><div className="p14-card-heading"><div><h3>Which measured depths lose evidence?</h3><p>Original accepted sample positions are retained. Excluded profiles are marked in amber.</p></div></div><BlackoutDepths result={result}/></section>
        <section className="p14-card" aria-label="Removed eligible comparisons"><div className="p14-card-heading"><div><h3>Exactly what disappears</h3><p>Each excluded profile keeps its original identity, date and quality context. Zero lost pairs means the profile was already ineligible at this model time.</p></div></div>{affected.length ? <div className="p14-table-scroll" tabIndex={0} role="region" aria-label="Excluded profile comparison effects"><table><thead><tr><th scope="col">Original profile and time</th><th scope="col">Eligible pairs, before → after</th><th scope="col">Why selected</th><th scope="col">Removed source sample indices</th></tr></thead><tbody>{affected.map(effect => { const profile = profiles.find(item => item.profile.id === effect.profile_id)!; return <tr key={effect.profile_id}><th scope="row"><button onClick={() => onObservation(effect.profile_id)}>{profile.profile.instrument.toUpperCase()} {profile.profile.platform}</button><small>{utc(profile.profile.time)}{profile.profile.time_end !== profile.profile.time ? ` to ${utc(profile.profile.time_end)}` : ''}</small></th><td>{effect.baseline_matched_samples} → {effect.remaining_matched_samples}<small>{effect.removed_eligible_samples} eligible comparisons lost</small></td><td>{effect.selected_by.join('; ')}</td><td><details className="p14-source-indices"><summary>{effect.removed_sample_indices.length} original sample indices</summary><p>{effect.removed_sample_indices.length ? effect.removed_sample_indices.join(', ') : 'No eligible source samples were removed.'}</p></details></td></tr>; })}</tbody></table></div> : <p className="p14-empty-inline">No profiles are excluded in the applied result. Select an instrument or profile, then apply the rehearsal.</p>}</section>
        <div className="p14-two-columns"><section className="p14-card" aria-label="Blackout affected statements"><div className="p14-card-heading"><div><h3>Which statements change?</h3><p>These statements describe checked samples under the applied gates.</p></div></div><div className="p14-card-body">{result.statements.map(statement => <div className="p14-statement" key={statement.id}><div><small>Original evidence</small><p>{statement.baseline}</p></div><div><small>{statement.changed ? 'After exclusion: changed' : 'After exclusion: unchanged'}</small><p>{statement.modified}</p></div></div>)}</div></section>
          <section className="p14-card" aria-label="Blackout residual summaries"><div className="p14-card-heading"><div><h3>Residuals on the remaining sample set</h3><p>Model minus observation, in {result.units}. These sets can contain different samples.</p></div></div><div className="p14-table-scroll" tabIndex={0} role="region" aria-label="Original and modified residual metrics"><table><thead><tr><th scope="col">Metric</th><th scope="col">Original</th><th scope="col">Modified</th></tr></thead><tbody>{([['count', 'Eligible pairs'], ['bias', 'Mean residual'], ['rmse', 'Root mean square error'], ['mae', 'Mean absolute error']] as const).map(([key, title]) => <tr key={key}><th scope="row">{title}</th><td>{number(result.baseline_metrics[key], key === 'count' ? 0 : 4)}</td><td>{number(result.modified_metrics[key], key === 'count' ? 0 : 4)}</td></tr>)}</tbody></table></div><p className="p14-chart-caption">Removing difficult comparisons can reduce an error statistic without improving the model. Adjacent depths are not independent samples. No forecast improvement or operational observing-system impact is established here.</p></section></div>
        <details className="p14-methods"><summary>Original QC exclusions, sources and scientific method</summary><div className="p14-table-scroll" tabIndex={0} role="region" aria-label="Original library quality and eligibility"><table><thead><tr><th scope="col">Profile</th><th scope="col">Original eligible pairs</th><th scope="col">Original scientific exclusions</th><th scope="col">Rehearsal status</th></tr></thead><tbody>{profiles.map(profile => <tr key={profile.profile.id}><th scope="row"><button onClick={() => onObservation(profile.profile.id)}>{profile.profile.instrument.toUpperCase()} {profile.profile.platform} <ArrowRight size={12}/></button><small>{utc(profile.profile.time)}</small></th><td>{profile.matched_count} / {profile.total_samples}</td><td>{Object.entries(profile.exclusion_counts).map(([reason, total]) => <div key={reason}>{reasonLabel(reason)}: {total}</div>)}{profile.excluded_count === 0 && 'None'}</td><td>{result.excluded_profile_ids.includes(profile.profile.id) ? 'Excluded by this rehearsal' : 'Retained'}</td></tr>)}</tbody></table></div><ul>{result.methods.map(method => <li key={method}>{method}</li>)}</ul><ul>{result.caveats.map(caveat => <li key={caveat}>{caveat.startsWith('Comparisons currently use the checked observation library.')?'This rehearsal uses the bundled library. Imported comparisons are available separately in Compare.':caveat}</li>)}</ul><p>Model: {manifest.case.source_label}<br/>Method: {result.method_version}</p><p>Model manifest SHA-256: <code>{result.manifest_sha256}</code><br/>Observation library SHA-256: <code>{result.observation_library_sha256}</code></p></details>
      </>}
    </div>
  </section>;
}
