import { type Coverage, type MatchSettings, type SampleMetrics, parseCoverage } from '../evidence/contracts';
import { count, equal, finite, hash, invalid, object, strings } from '../evolution/shared';
import type { InstrumentSummary } from '../instruments/contracts';

export const currentBlackoutMethod = 'p14-blackout-v1';
export const supportedBlackoutMethod = (value: unknown): value is typeof currentBlackoutMethod => value === currentBlackoutMethod;
export type BlackoutQuery = { settings: MatchSettings; excluded_profile_ids: string[]; excluded_instruments: InstrumentSummary['instrument'][]; excluded_platforms: string[]; excluded_collections: string[] };
export type BlackoutRecipe = { mode: 'blackout'; case_id: string; query: BlackoutQuery };
export type ProfileEffect = { profile_id: string; excluded_by_user: boolean; selected_by: string[]; baseline_matched_samples: number; remaining_matched_samples: number; removed_eligible_samples: number; removed_sample_indices: number[]; original_metrics: SampleMetrics };
export type BlackoutAnalysis = { schema_version: '1'; kind: 'observation_blackout'; method_version: typeof currentBlackoutMethod; case_id: string; query: BlackoutQuery; units: string; manifest_sha256: string; observation_library_sha256: string; baseline: Coverage; modified: Coverage; baseline_metrics: SampleMetrics; modified_metrics: SampleMetrics; profile_effects: ProfileEffect[]; excluded_profile_ids: string[]; removed_profiles: number; removed_eligible_profiles: number; removed_samples: number; removed_eligible_samples: number; statements: { id: string; baseline: string; modified: string; changed: boolean }[]; model_unchanged: true; source_qc_unchanged: true; methods: string[]; caveats: string[] };
export type BlackoutResult = BlackoutAnalysis;
const uniqueStrings = (value: unknown): value is string[] => strings(value) && value.length <= 1000 && new Set(value).size === value.length && value.every(item => item.length > 0 && item.length <= 300);
function settings(value: unknown): value is MatchSettings { return object(value) && ['temperature', 'salinity'].includes(String(value.variable)) && count(value.time_index) && value.time_index <= 6 && finite(value.time_window_hours) && value.time_window_hours >= 0 && value.time_window_hours <= 72 && finite(value.distance_km) && value.distance_km >= 0 && value.distance_km <= 50 && finite(value.max_vertical_gap_m) && value.max_vertical_gap_m >= 1 && value.max_vertical_gap_m <= 1000 && ['good', 'good_probably_good'].includes(String(value.qc)); }
export function validBlackoutQuery(value: unknown): value is BlackoutQuery { return object(value) && settings(value.settings) && uniqueStrings(value.excluded_profile_ids) && uniqueStrings(value.excluded_instruments) && value.excluded_instruments.every(item => ['argo', 'bgc', 'ctd', 'glider'].includes(item)) && uniqueStrings(value.excluded_platforms) && uniqueStrings(value.excluded_collections); }
export function validBlackoutRecipe(value: unknown): value is BlackoutRecipe { return object(value) && value.mode === 'blackout' && typeof value.case_id === 'string' && validBlackoutQuery(value.query); }
export const sameBlackoutQuery = (a: unknown, b: unknown) => equal(a, b);
export const clearExclusions = (query: BlackoutQuery): BlackoutQuery => ({ ...query, excluded_profile_ids: [], excluded_instruments: [], excluded_platforms: [], excluded_collections: [] });
function metrics(value: unknown, size: number): value is SampleMetrics { return object(value) && value.count === size && ['bias', 'rmse', 'mae', 'maximum_abs_residual'].every(key => size === 0 ? value[key] === null : finite(value[key])) && (size === 0 || Number(value.rmse) >= 0 && Number(value.mae) >= 0 && Number(value.maximum_abs_residual) >= 0); }
export function parseBlackout(raw: unknown): BlackoutAnalysis {
  const fail = () => invalid('observation blackout');
  if (!object(raw) || raw.schema_version !== '1' || raw.kind !== 'observation_blackout' || !supportedBlackoutMethod(raw.method_version) || typeof raw.case_id !== 'string' || !validBlackoutQuery(raw.query) || !hash(raw.manifest_sha256) || !hash(raw.observation_library_sha256) || raw.model_unchanged !== true || raw.source_qc_unchanged !== true || !strings(raw.methods) || !strings(raw.caveats) || !uniqueStrings(raw.excluded_profile_ids) || !['removed_profiles', 'removed_eligible_profiles', 'removed_samples', 'removed_eligible_samples'].every(key => count(raw[key])) || !Array.isArray(raw.profile_effects) || !Array.isArray(raw.statements)) throw fail();
  const baseline = parseCoverage(raw.baseline), modified = parseCoverage(raw.modified);
  if (raw.units !== (raw.query.settings.variable === 'temperature' ? '°C' : 'psu')) throw fail();
  for (const coverage of [baseline, modified]) if (coverage.case_id !== raw.case_id || coverage.manifest_sha256 !== raw.manifest_sha256 || coverage.observation_library_sha256 !== raw.observation_library_sha256 || !equal(coverage.settings, raw.query.settings)) throw fail();
  if (baseline.model_time !== modified.model_time || !metrics(raw.baseline_metrics, baseline.matched_samples) || !metrics(raw.modified_metrics, modified.matched_samples)) throw fail();
  const result = raw as BlackoutAnalysis, removed = new Set(result.excluded_profile_ids), profiles = new Map(baseline.profiles.map(profile => [profile.profile.id, profile]));
  if (result.removed_profiles !== removed.size || result.removed_profiles !== baseline.total_profiles - modified.total_profiles || result.removed_eligible_profiles !== baseline.matched_profiles - modified.matched_profiles || result.removed_samples !== baseline.total_samples - modified.total_samples || result.removed_eligible_samples !== baseline.matched_samples - modified.matched_samples || result.profile_effects.length !== baseline.total_profiles || new Set(result.profile_effects.map(effect => effect.profile_id)).size !== baseline.total_profiles || modified.profiles.some(profile => removed.has(profile.profile.id) || !profiles.has(profile.profile.id))) throw fail();
  for (const effect of result.profile_effects) {
    const profile = profiles.get(effect.profile_id);
    if (!profile || typeof effect.excluded_by_user !== 'boolean' || effect.excluded_by_user !== removed.has(effect.profile_id) || !strings(effect.selected_by) || effect.baseline_matched_samples !== profile.matched_count || !count(effect.remaining_matched_samples) || effect.remaining_matched_samples !== (effect.excluded_by_user ? 0 : profile.matched_count) || effect.removed_eligible_samples !== effect.baseline_matched_samples - effect.remaining_matched_samples || !Array.isArray(effect.removed_sample_indices) || effect.removed_sample_indices.length !== effect.removed_eligible_samples || new Set(effect.removed_sample_indices).size !== effect.removed_eligible_samples || !effect.removed_sample_indices.every(index => count(index)) || !metrics(effect.original_metrics, profile.matched_count)) throw fail();
  }
  if (result.profile_effects.reduce((total, effect) => total + effect.removed_eligible_samples, 0) !== result.removed_eligible_samples || result.statements.some(statement => !object(statement) || typeof statement.id !== 'string' || typeof statement.baseline !== 'string' || typeof statement.modified !== 'string' || typeof statement.changed !== 'boolean' || statement.changed !== (statement.id === 'residual_statistics' ? !equal(result.baseline_metrics, result.modified_metrics) : statement.baseline !== statement.modified))) throw fail();
  return result;
}
