import { ApiError,appVersion,type CaseManifest } from '../contracts';
export type SamplingVariable='temperature'|'salinity';
export type PlanQuery={variable:SamplingVariable;depth_index:number;budget:number;min_spacing_km:number;objective:'gradient'|'coverage';seed:number};
export type SurveyQuery={variable:SamplingVariable;depth_index:number;time_index:number;start:[number,number];end:[number,number];stations:number};
export type ExpeditionRecipe={mode:'expedition';case_id:string;query:PlanQuery;survey:SurveyQuery|null;experiment:boolean};
export type Candidate={id:string;longitude:number;latitude:number;x_index:number;y_index:number;prior_value:number;gradient_per_km:number|null};
export type Station=Candidate&{order:number;nearest_station_km:number|null;rationale:string};
export type ExpeditionMethod='p10-sampling-v1'|'p10-sampling-v2';
export const currentExpeditionMethod:ExpeditionMethod='p10-sampling-v2';
export const supportedExpeditionMethod=(v:unknown):v is ExpeditionMethod=>v==='p10-sampling-v1'||v==='p10-sampling-v2';
type Common={schema_version:'1';method_version:ExpeditionMethod;case_id:string;manifest_sha256:string;units:string;variable:SamplingVariable;depth_m:number;prior_time:string;methods:string[];limitations:string[]};
export type StationPlan=Common&{kind:'station_plan';query:PlanQuery;bounds:[number,number,number,number];candidate_count:number;evaluation_count:number;fulfilled:boolean;reason:string|null;stations:Station[];candidates:Candidate[];background:{longitude:number[];latitude:number[];values:(number|null)[];shape:[number,number]}};
export type SurveySample={order:number;requested_longitude:number;requested_latitude:number;longitude:number;latitude:number;x_index:number;y_index:number;distance_km:number;offset_km:number;value:number|null};
export type VirtualSurvey=Common&{kind:'virtual_survey';query:SurveyQuery;model_time:string;samples:SurveySample[];simulated:true;unique_columns:number};
export type Strategy='selected'|'uniform'|'random'|'persistence';
export type ExperimentRun={strategy:Strategy;seed:number|null;time_index:number;model_time:string;status:'ok'|'failed';reason:string|null;budget:number;station_ids:string[];evaluation_count:number;rmse:number|null;mae:number|null;bias:number|null};
export type StrategySummary={strategy:Strategy;successful_runs:number;failed_runs:number;mean_rmse:number|null;min_rmse:number|null;max_rmse:number|null};
export type SamplingExperiment=Common&{kind:'sampling_experiment';query:PlanQuery;plan:StationPlan;evaluation_count:number;runs:ExperimentRun[];summary:StrategySummary[];random_seeds:number[];held_out_times:string[];evaluation_coordinates:{longitude:number;latitude:number}[]};
export const defaultPlan:PlanQuery={variable:'temperature',depth_index:0,budget:8,min_spacing_km:30,objective:'gradient',seed:26067};
export const strategyLabels:Record<Strategy,string>={selected:'Your selected design',uniform:'Uniform baseline',random:'Random baseline',persistence:'Unchanged prior'};
export const variableLabels:Record<SamplingVariable,string>={temperature:'Temperature',salinity:'Practical salinity'};
export const unitsFor=(v:SamplingVariable)=>v==='temperature'?'°C':'psu';
const object=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v);
const count=(v:unknown):v is number=>finite(v)&&Number.isInteger(v)&&v>=0;
const nullable=(v:unknown)=>v===null||finite(v);
const strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.every(x=>typeof x==='string');
const date=(v:unknown):v is string=>typeof v==='string'&&v.endsWith('Z')&&Number.isFinite(Date.parse(v));
const numbers=(v:unknown):v is number[]=>Array.isArray(v)&&v.every(finite);
const axis=(v:unknown):v is number[]=>numbers(v)&&v.length>=2&&v.every((x,i)=>i===0||x>v[i-1]);
const fail=()=>new ApiError('The expedition response could not be verified. Only previously verified results are kept.',undefined,'response');
const position=(v:unknown)=>object(v)&&finite(v.longitude)&&Math.abs(v.longitude)<=180&&finite(v.latitude)&&Math.abs(v.latitude)<=90;
export function equalQuery(a:unknown,b:unknown):boolean{if(!object(a)||!object(b))return false;return Object.keys(a).length===Object.keys(b).length&&Object.entries(a).every(([k,v])=>Array.isArray(v)?JSON.stringify(v)===JSON.stringify(b[k]):v===b[k]);}
function validPlan(q:unknown):q is PlanQuery{return object(q)&&['temperature','salinity'].includes(String(q.variable))&&count(q.depth_index)&&q.depth_index<=32&&count(q.budget)&&q.budget>=3&&q.budget<=16&&finite(q.min_spacing_km)&&q.min_spacing_km>=0&&q.min_spacing_km<=150&&['gradient','coverage'].includes(String(q.objective))&&count(q.seed)&&q.seed<=2147483647;}
function validSurvey(q:unknown):q is SurveyQuery{return object(q)&&['temperature','salinity'].includes(String(q.variable))&&count(q.depth_index)&&q.depth_index<=32&&count(q.time_index)&&q.time_index<=6&&numbers(q.start)&&q.start.length===2&&numbers(q.end)&&q.end.length===2&&JSON.stringify(q.start)!==JSON.stringify(q.end)&&count(q.stations)&&q.stations>=2&&q.stations<=81;}
export function validExpeditionRecipe(v:unknown):v is ExpeditionRecipe{return object(v)&&v.mode==='expedition'&&typeof v.case_id==='string'&&validPlan(v.query)&&typeof v.experiment==='boolean'&&(v.survey===null||validSurvey(v.survey)&&v.survey.variable===v.query.variable&&v.survey.depth_index===v.query.depth_index);}
function common(v:unknown):v is Common&Record<string,unknown>{return object(v)&&v.schema_version==='1'&&supportedExpeditionMethod(v.method_version)&&typeof v.case_id==='string'&&typeof v.manifest_sha256==='string'&&/^[a-f0-9]{64}$/.test(v.manifest_sha256)&&['temperature','salinity'].includes(String(v.variable))&&v.units===unitsFor(v.variable as SamplingVariable)&&finite(v.depth_m)&&v.depth_m>=0&&v.depth_m<=1000&&date(v.prior_time)&&strings(v.methods)&&strings(v.limitations);}
function candidate(v:unknown):v is Candidate{return position(v)&&object(v)&&typeof v.id==='string'&&v.id.length>0&&count(v.x_index)&&count(v.y_index)&&finite(v.prior_value)&&nullable(v.gradient_per_km)&&(v.gradient_per_km===null||Number(v.gradient_per_km)>=0);}
export function parsePlan(v:unknown):StationPlan{
  if(!common(v)||v.kind!=='station_plan'||!validPlan(v.query)||v.variable!==v.query.variable||!numbers(v.bounds)||v.bounds.length!==4||v.bounds[0]>=v.bounds[2]||v.bounds[1]>=v.bounds[3]||!count(v.candidate_count)||!count(v.evaluation_count)||typeof v.fulfilled!=='boolean'||!(v.reason===null||typeof v.reason==='string')||!Array.isArray(v.candidates)||v.candidates.length!==v.candidate_count||!v.candidates.every(candidate)||!Array.isArray(v.stations)||v.stations.length>v.query.budget||!object(v.background)||!axis(v.background.longitude)||!axis(v.background.latitude)||!numbers(v.background.shape)||v.background.shape.length!==2||!Array.isArray(v.background.values)||!v.background.values.every(nullable))throw fail();
  const r=v as StationPlan,b=r.background;if(b.shape[0]!==b.latitude.length||b.shape[1]!==b.longitude.length||b.values.length!==b.shape[0]*b.shape[1]||b.values.length>100000||new Set(r.candidates.map(c=>c.id)).size!==r.candidate_count||new Set(r.stations.map(c=>c.id)).size!==r.stations.length||r.fulfilled!== (r.stations.length===r.query.budget)||!r.fulfilled&&!r.reason)throw fail();
  if(r.candidates.some(c=>c.longitude<r.bounds[0]||c.longitude>r.bounds[2]||c.latitude<r.bounds[1]||c.latitude>r.bounds[3]))throw fail();
  for(const [i,s] of r.stations.entries()){if(!candidate(s)||s.order!==i+1||typeof s.rationale!=='string'||!(i===0?s.nearest_station_km===null:finite(s.nearest_station_km)&&s.nearest_station_km+1e-8>=r.query.min_spacing_km))throw fail();const c=r.candidates.find(c=>c.id===s.id);if(!c||(['longitude','latitude','x_index','y_index','prior_value','gradient_per_km'] as const).some(k=>c[k]!==s[k]))throw fail();}return r;
}
export function parseSurvey(v:unknown):VirtualSurvey{
  if(!common(v)||v.kind!=='virtual_survey'||!validSurvey(v.query)||v.variable!==v.query.variable||!date(v.model_time)||v.simulated!==true||!count(v.unique_columns)||!Array.isArray(v.samples)||v.samples.length!==v.query.stations)throw fail();
  const r=v as VirtualSurvey;if(!r.samples.every((s,i)=>position(s)&&object(s)&&s.order===i+1&&['requested_longitude','requested_latitude','distance_km','offset_km'].every(k=>finite(s[k as keyof SurveySample]))&&s.distance_km>=0&&s.offset_km>=0&&count(s.x_index)&&count(s.y_index)&&nullable(s.value)&&(i===0?s.distance_km===0:s.distance_km>r.samples[i-1].distance_km))||new Set(r.samples.map(s=>`${s.x_index},${s.y_index}`)).size!==r.unique_columns)throw fail();return r;
}
export function parseExperiment(v:unknown):SamplingExperiment{
  if(!common(v)||v.kind!=='sampling_experiment'||!validPlan(v.query)||v.variable!==v.query.variable||!count(v.evaluation_count)||!Array.isArray(v.runs)||v.runs.length!==24||!Array.isArray(v.summary)||v.summary.length!==4||!Array.isArray(v.random_seeds)||v.random_seeds.length!==5||!v.random_seeds.every(count)||!Array.isArray(v.held_out_times)||v.held_out_times.length!==3||!v.held_out_times.every(date)||!Array.isArray(v.evaluation_coordinates)||v.evaluation_coordinates.length!==v.evaluation_count||!v.evaluation_coordinates.every(position))throw fail();
  const r=v as SamplingExperiment;parsePlan(r.plan);if(!equalQuery(r.plan.query,r.query)||r.plan.method_version!==r.method_version||r.plan.manifest_sha256!==r.manifest_sha256||r.plan.case_id!==r.case_id||r.plan.evaluation_count!==r.evaluation_count||new Set(r.summary.map(s=>s.strategy)).size!==4)throw fail();
  for(const run of r.runs){if(!object(run)||!(run.strategy in strategyLabels)||![2,4,6].includes(run.time_index)||run.model_time!==r.held_out_times[[2,4,6].indexOf(run.time_index)]||!['ok','failed'].includes(run.status)||!count(run.budget)||!strings(run.station_ids)||!count(run.evaluation_count)||!nullable(run.seed)||!['rmse','mae','bias'].every(k=>nullable(run[k as keyof ExperimentRun])))throw fail();if(run.status==='ok'?(run.evaluation_count>r.evaluation_count||run.evaluation_count===0||!finite(run.rmse)||run.rmse<0||!finite(run.mae)||run.mae<0||!finite(run.bias)):(run.rmse!==null||run.mae!==null||run.bias!==null||typeof run.reason!=='string'))throw fail();if(run.strategy==='persistence'?(run.budget!==0||run.station_ids.length!==0):(run.budget!==run.station_ids.length||run.budget>r.query.budget||run.status==='ok'&&run.station_ids.length!==r.query.budget))throw fail();}
  for(const s of r.summary){if(!object(s)||!(s.strategy in strategyLabels)||!count(s.successful_runs)||!count(s.failed_runs))throw fail();const runs=r.runs.filter(x=>x.strategy===s.strategy),ok=runs.filter(x=>x.status==='ok');if(s.successful_runs!==ok.length||s.failed_runs!==runs.length-ok.length)throw fail();if(ok.length){const values=ok.map(x=>x.rmse!),mean=values.reduce((a,b)=>a+b,0)/values.length;if(!finite(s.mean_rmse)||Math.abs(s.mean_rmse-mean)>1e-8*Math.max(1,mean)||s.min_rmse!==Math.min(...values)||s.max_rmse!==Math.max(...values))throw fail();}else if(s.mean_rmse!==null||s.min_rmse!==null||s.max_rmse!==null)throw fail();}return r;
}
export function verifyExpedition<T extends StationPlan|VirtualSurvey|SamplingExperiment>(result:T,query:PlanQuery|SurveyQuery,manifest:CaseManifest):T{if(result.method_version!==currentExpeditionMethod||result.case_id!==manifest.case.id||!equalQuery(result.query,query)||result.prior_time!==manifest.coordinates.times[0]||result.depth_m!==manifest.coordinates.depth_m[query.depth_index]||result.kind==='virtual_survey'&&result.model_time!==manifest.coordinates.times[result.query.time_index])throw fail();return result;}
export async function expeditionRequest<T>(path:string,body:unknown,parse:(v:unknown)=>T,signal?:AbortSignal):Promise<T>{const controller=new AbortController(),abort=()=>controller.abort();if(signal?.aborted)abort();signal?.addEventListener('abort',abort,{once:true});const timer=setTimeout(abort,40000);try{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(body),signal:controller.signal,cache:'no-store'});if(response.headers.get('X-Ocean-App-Version')!==appVersion)throw new ApiError('The workspace has been updated. Reload before continuing this expedition.',undefined,'update');const payload:unknown=await response.json();if(!response.ok){const error=object(payload)&&object(payload.error)?payload.error:null;throw new ApiError(error&&typeof error.message==='string'?error.message:'The expedition service could not finish. Try again.');}return parse(payload);}catch(error){if(error instanceof ApiError||signal?.aborted)throw error;throw new ApiError(controller.signal.aborted?'The expedition request timed out. Your verified results are kept.':'Could not reach the expedition service. Try again.');}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}}
export const number=(v:number|null,digits=3)=>v===null?'Not available':v!==0&&Math.abs(v)<10**(-digits)?v.toPrecision(3):v.toLocaleString('en-US',{maximumFractionDigits:digits});
export const utc=(v:string)=>v.replace('T',' ').replace(/:00Z$/,' UTC');
