import { enterWorkspace, openTool } from './ux-helpers';
import { test,expect,type Page } from '@playwright/test';
import { readFile,readFileSync } from 'node:fs';
import { promisify } from 'node:util';
const read=promisify(readFile),version=JSON.parse(readFileSync(new URL('../../api/release.json',import.meta.url),'utf8')).version;
async function open(page:Page){await page.addInitScript(()=>Object.defineProperty(navigator,'connection',{value:{saveData:true},configurable:true}));await enterWorkspace(page);await openTool(page,'Open Drift Lab');await expect(page.getByLabel('Drift Lab',{exact:true})).toBeVisible();await expect(page.locator('.drift-map-top')).toContainText('2024-01-07 00:00 UTC',{timeout:25000});}
async function run(page:Page,label='A'){const response=page.waitForResponse(r=>r.url().endsWith('/drift/stream')&&r.request().method()==='POST');await page.getByRole('button',{name:`Calculate run ${label}`,exact:true}).click();const r=await response;expect(r.ok()).toBeTruthy();await expect(page.getByLabel(`Applied drift run ${label}`,{exact:true})).toBeVisible({timeout:30000});await expect(page.getByRole('button',{name:'Cancel calculation',exact:true})).toHaveCount(0);const expected=await page.request.post(r.url().replace('/stream','/run'),{data:r.request().postDataJSON()});expect(expected.ok()).toBeTruthy();return expected.json();}
async function small(page:Page){await page.getByLabel('Drift particle count',{exact:true}).fill('6');await page.getByLabel('Drift duration hours',{exact:true}).fill('6');}

test('initial drift archives stay readable and identify a changed method on replay',async({page})=>{
  test.setTimeout(60000);await open(page);
  const fixture=JSON.parse(await read(new URL('../../docs/evidence/p11-api-local-records.json',import.meta.url),'utf8')),record=fixture.records[0];
  expect(record.replay.sources.methods.drift).toBe('p11-drift-v1');await page.getByRole('button',{name:'Open saved investigations'}).click();
  await page.getByLabel('Open investigation file',{exact:true}).setInputFiles({name:'initial-drift.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(record))});
  await expect(page.getByLabel('Selected saved investigation')).toContainText(record.replay.title);
  const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Investigation JSON',exact:true}).click();const retained=JSON.parse(await read((await(await downloaded).path())!,'utf8'));expect(retained.document_sha256).toBe(record.document_sha256);expect(retained.result_sha256).toBe(record.result_sha256);
  await page.getByRole('button',{name:'Recalculate and reopen',exact:true}).click();await expect(page.getByRole('alert')).toContainText('different scientific method version');await expect(page.getByRole('dialog')).toBeVisible();
});

test('real historical drift works in both cases and preserves source depth and dates',async({page})=>{
  test.setTimeout(90000);await open(page);const a=await run(page);expect(a.simulated).toBe(true);expect(a.particles).toHaveLength(24);expect(a.start_time).toBe('2024-01-07T00:00:00Z');expect(a.depth_m).toBe(0);await page.getByLabel('Inspect drift particle',{exact:true}).selectOption('4');await expect(page.getByLabel('Drift particle inspector')).toContainText(a.particles[3].distance_km.toLocaleString('en-US',{maximumFractionDigits:6}));
  await page.getByLabel('Study case',{exact:true}).selectOption('arabian-sea-2024-01');await openTool(page,'Open Drift Lab');await small(page);await page.getByLabel('Drift depth',{exact:true}).selectOption('32');await page.getByLabel('Drift start snapshot',{exact:true}).selectOption('2');const b=await run(page);expect(b.case_id).toBe('arabian-sea-2024-01');expect(b.depth_m).toBe(1000);expect(b.start_time).toBe('2024-01-08T00:00:00Z');await expect(page.getByLabel('Applied drift run A')).toContainText('1,000 m fixed depth');
});

test('playback, elapsed-time scrubbing and navigation preserve applied scientific paths',async({page})=>{
  test.setTimeout(60000);await page.emulateMedia({reducedMotion:'reduce'});await open(page);await small(page);await run(page);await expect(page.getByLabel('Drift elapsed readout')).toContainText('6 h after release');await expect(page.getByRole('button',{name:'Play paths',exact:true})).toBeVisible();await page.getByRole('slider',{name:'Drift elapsed time',exact:true}).fill('3600');await expect(page.getByLabel('Drift elapsed readout')).toContainText('1 h after release');await page.getByRole('button',{name:'Play paths',exact:true}).click();await expect(page.getByRole('button',{name:'Pause paths',exact:true})).toBeVisible();await page.getByRole('button',{name:'Pause paths',exact:true}).click();await page.getByLabel('Show drift trails',{exact:true}).uncheck();expect(await page.locator('.drift-map-scroll polyline').count()).toBe(0);await openTool(page,'Ocean explorer');await expect(page.getByLabel('Drift Lab',{exact:true})).toBeHidden();await openTool(page,'Open Drift Lab');await expect(page.getByLabel('Applied drift run A')).toContainText('6 simulated particles');await expect(page.getByRole('button',{name:'Play paths',exact:true})).toBeVisible();
});

test('point particles coincide and arrival counts retain the requested denominator',async({page})=>{
  test.setTimeout(60000);await open(page);await small(page);await page.getByLabel('Drift release geometry').selectOption('point');await page.getByText('Release coordinates',{exact:true}).click();await page.getByLabel('Drift release longitude',{exact:true}).fill('87');await page.getByLabel('Drift release latitude',{exact:true}).fill('13');await expect(page.getByLabel('Drift Lab',{exact:true})).toContainText('Identical particles at one point follow the same path');await page.getByText('Target box and numerical settings',{exact:true}).click();await page.getByLabel('Enable drift target box').check();for(const [side,value] of [['west','86'],['south','12.5'],['east','88'],['north','14']])await page.getByLabel(`Drift target ${side}`,{exact:true}).fill(value);const r=await run(page);expect(r.summary.arrived).toBe(6);expect(r.summary.arrival_fraction).toBe(1);expect(r.particles.every((p:{points:unknown[];arrival_elapsed_seconds:number})=>JSON.stringify(p.points)===JSON.stringify(r.particles[0].points)&&p.arrival_elapsed_seconds===0)).toBe(true);await expect(page.getByLabel('Applied drift run A')).toContainText('6 of 6 released particles reached the target');
});

test('forcing exhaustion is explained and draft changes never replace the applied run',async({page})=>{
  test.setTimeout(60000);await open(page);await small(page);await run(page);await page.getByLabel('Drift start snapshot',{exact:true}).selectOption('6');await page.getByRole('button',{name:'Calculate run A',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Only 0 hours of forcing remain');await expect(page.getByLabel('Applied drift run A')).toContainText('2024-01-07 00:00 UTC');await expect(page.locator('.drift-map-top')).toContainText('2024-01-07 00:00 UTC');await page.getByRole('button',{name:'Save drift experiment',exact:true}).click();await page.getByRole('button',{name:'Save on this browser',exact:true}).click();await expect(page.getByLabel('Selected saved investigation')).toBeVisible({timeout:30000});const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Investigation JSON',exact:true}).click();const record=JSON.parse(await read((await(await downloaded).path())!,'utf8'));expect(record.replay.recipe.query.start_time_index).toBe(0);expect(record.results[0].output.query.start_time_index).toBe(0);
});

test('comparison saves and reopens both complete calculated runs in another browser context',async({page,browser})=>{
  test.setTimeout(90000);await open(page);await small(page);const a=await run(page);await page.getByRole('button',{name:'Compare another release',exact:true}).click();await page.getByRole('button',{name:'Calculate run B',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Change at least one setting');await page.getByLabel('Drift start snapshot',{exact:true}).selectOption('2');const b=await run(page,'B');expect(b.start_time).not.toBe(a.start_time);await expect(page.getByLabel('Applied drift runs')).toContainText('Run A');await expect(page.getByLabel('Applied drift runs')).toContainText('Run B');await page.getByRole('button',{name:'Save drift experiment',exact:true}).click();await page.getByLabel('Investigation name',{exact:true}).fill('Drift release comparison');await page.getByRole('button',{name:'Save on this browser',exact:true}).click();await expect(page.getByLabel('Selected saved investigation')).toContainText('Drift release comparison',{timeout:30000});const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Investigation JSON',exact:true}).click();const record=JSON.parse(await read((await(await downloaded).path())!,'utf8'));expect(record.results.map((m:{module:string})=>m.module)).toEqual(['drift_run','reference_drift_run']);expect(record.results[1].output.particles).toEqual(b.particles);
  const context=await browser.newContext(),other=await context.newPage();await enterWorkspace(other,page.url());await other.getByRole('button',{name:'Open saved investigations'}).click();await other.getByLabel('Open investigation file',{exact:true}).setInputFiles({name:'drift.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(record))});await expect(other.getByLabel('Selected saved investigation')).toContainText('Drift release comparison');await other.getByRole('button',{name:'Recalculate and reopen',exact:true}).click();await expect(other.getByRole('dialog')).toHaveCount(0,{timeout:30000});await expect(other.getByLabel('Applied drift run A')).toBeVisible();await expect(other.getByLabel('Applied drift run B')).toContainText('2024-01-08 00:00 UTC');await context.close();
});

test('cancel and failed requests preserve completed results and reject corrupt trajectories',async({page})=>{
  test.setTimeout(90000);await open(page);await small(page);await run(page);let unblock!:()=>void;const gate=new Promise<void>(r=>unblock=r);await page.route('**/drift/stream',async route=>{await gate;await route.abort().catch(()=>undefined);});await page.getByLabel('Drift duration hours').fill('7');await page.getByRole('button',{name:'Calculate run A',exact:true}).click();await expect(page.getByRole('button',{name:'Cancel calculation',exact:true})).toBeVisible();await page.getByRole('button',{name:'Cancel calculation',exact:true}).click();await expect(page.getByLabel('Drift Lab',{exact:true})).toContainText('Calculation cancelled');await expect(page.getByLabel('Applied drift run A')).toContainText('6 hours');unblock();await page.unroute('**/drift/stream');
  await page.route('**/drift/stream',route=>route.fulfill({status:503,headers:{'X-Ocean-App-Version':version},contentType:'application/json',body:JSON.stringify({error:{message:'Drift service temporarily unavailable.'}})}));await page.getByRole('button',{name:'Calculate run A',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Drift service temporarily unavailable');await expect(page.getByLabel('Applied drift run A')).toContainText('6 hours');await page.unroute('**/drift/stream');await page.route('**/drift/stream',async route=>{const response=await route.fetch(),events=(await response.text()).trim().split('\n').map(line=>JSON.parse(line));events.find(e=>e.type==='result').result.particles[0].points[0].elapsed_seconds=9;await route.fulfill({response,body:events.map(e=>JSON.stringify(e)).join('\n')+'\n'});});await page.getByRole('button',{name:'Calculate run A',exact:true}).click();await expect(page.getByRole('alert')).toContainText('could not be verified');await expect(page.getByLabel('Applied drift run A')).toContainText('6 hours');
});

test('320-pixel and enlarged layouts retain keyboard controls without document overflow',async({page})=>{
  test.setTimeout(90000);await page.setViewportSize({width:320,height:850});await open(page);await small(page);await page.getByRole('button',{name:'Draw release box',exact:true}).click();const svg=page.getByRole('group',{name:'Drift trajectory map',exact:true});for(const p of [[360,180],[480,260]]){await svg.scrollIntoViewIfNeeded();const point=await svg.evaluate((el,[x,y])=>{const s=el as SVGSVGElement,container=s.parentElement!,bounds=container.getBoundingClientRect(),p=new DOMPoint(x,y).matrixTransform(s.getScreenCTM()!);if(p.x>bounds.right-20)container.scrollLeft+=p.x-bounds.right+20;if(p.x<bounds.left+20)container.scrollLeft+=p.x-bounds.left-20;const shown=new DOMPoint(x,y).matrixTransform(s.getScreenCTM()!);return {x:shown.x,y:shown.y};},p);await page.mouse.click(point.x,point.y);}await run(page);await page.getByLabel('Inspect drift particle').selectOption('3');await expect(page.getByLabel('Drift particle inspector')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.setViewportSize({width:900,height:1000});await page.addStyleTag({content:'html{font-size:200% !important}'});await expect(page.getByLabel('Inspect drift particle')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});

test('failed draft current context is explicit during drawing and keeps the completed run',async({page})=>{
  test.setTimeout(60000);await open(page);await small(page);await run(page);
  await page.route('**/drift/context?**',route=>route.fulfill({status:503,headers:{'X-Ocean-App-Version':version},contentType:'application/json',body:JSON.stringify({error:{message:'Draft current context unavailable.'}})}));
  await page.getByLabel('Drift depth',{exact:true}).selectOption('1');await page.getByRole('button',{name:'Draw release box',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Draft current context unavailable');await expect(page.locator('.drift-map-top')).toContainText('Current context unavailable');await expect(page.getByLabel('Applied drift run A')).toContainText('0 m fixed depth');await page.getByRole('button',{name:'Cancel drawing',exact:true}).click();await expect(page.locator('.drift-map-top')).toContainText('Run A start-snapshot currents: 0 m');await expect(page.getByRole('alert')).toHaveCount(0);
});
