import { enterWorkspace, openTool } from './ux-helpers';
import { expect,test,type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
const version=JSON.parse(readFileSync(new URL('../../api/release.json',import.meta.url),'utf8')).version;
const bay='bay-bengal-2024-01';

test('initial expedition records stay readable and explicitly reject a changed method on replay',async({page})=>{
  test.setTimeout(60000);await open(page);
  const records=JSON.parse(await readFile(new URL('../../docs/evidence/p10-public-v1-records.json',import.meta.url),'utf8'));
  const record=records[0];await page.getByRole('button',{name:'Open saved investigations'}).click();
  await page.getByLabel('Open investigation file',{exact:true}).setInputFiles({name:'initial-expedition.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(record))});
  await expect(page.getByLabel('Selected saved investigation')).toContainText(record.replay.title);
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Investigation JSON',exact:true}).click();
  const retained=JSON.parse(await readFile((await (await download).path())!,'utf8'));expect(retained.document_sha256).toBe(record.document_sha256);
  await page.getByRole('button',{name:'Recalculate and reopen',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('different scientific method version');
  await expect(page.getByRole('dialog')).toBeVisible();
});
async function open(page:Page){await page.addInitScript(()=>Object.defineProperty(navigator,'connection',{value:{saveData:true},configurable:true}));await enterWorkspace(page);await openTool(page,'Open Virtual Expedition');await expect(page.getByLabel('Applied expedition plan',{exact:true})).toContainText('8 of 8 stations',{timeout:20000});}
async function update(page:Page){const response=page.waitForResponse(r=>r.url().endsWith('/expedition/plan')&&r.request().method()==='POST');await page.getByRole('button',{name:'Update station plan',exact:true}).click();const r=await response;expect(r.ok()).toBeTruthy();return r.json();}
async function experiment(page:Page){await page.getByRole('button',{name:'Compare strategies',exact:true}).click();const response=page.waitForResponse(r=>r.url().endsWith('/expedition/experiment'));await page.getByRole('button',{name:'Run reconstruction test',exact:true}).click();const r=await response;expect(r.ok()).toBeTruthy();await expect(page.getByLabel('Sampling strategy results',{exact:true})).toBeVisible({timeout:20000});return r.json();}

test('station design obeys applied budgets, preserves fixed prior and supports both cases',async({page})=>{
  test.setTimeout(60000);await open(page);await page.getByLabel('Station budget',{exact:true}).fill('5');const r=await update(page);await expect(page.getByLabel('Applied expedition plan')).toContainText('5 of 5 stations');expect(r.prior_time).toBe('2024-01-07T00:00:00Z');expect(r.stations).toHaveLength(5);for(const station of r.stations.slice(1))expect(station.nearest_station_km).toBeGreaterThanOrEqual(30-1e-8);
  await page.getByLabel('Selected expedition station').selectOption(r.stations[2].id);await expect(page.locator('.expedition-station-value')).toContainText(r.stations[2].prior_value.toLocaleString('en-US',{maximumFractionDigits:6}));
  await page.getByRole('button',{name:'Sample a route',exact:true}).click();await page.getByLabel('Virtual survey snapshot').selectOption('6');await expect(page.getByLabel('Applied expedition plan')).toContainText('2024-01-07 00:00 UTC');
  const cases=await page.getByLabel('Study case',{exact:true}).locator('option').evaluateAll(options=>options.map(o=>(o as HTMLOptionElement).value));const other=cases.find(id=>id!==bay)!;await page.getByLabel('Study case',{exact:true}).selectOption(other);await openTool(page,'Open Virtual Expedition');await expect(page.getByLabel('Applied expedition plan')).toContainText('8 of 8 stations');await expect(page.locator('.expedition-methods')).toContainText(other);
});

test('virtual route samples retain actual timestamps, native coordinates and source values',async({page})=>{
  test.setTimeout(60000);await open(page);await page.getByLabel('Expedition depth').selectOption('7');await update(page);await page.getByRole('button',{name:'Sample a route',exact:true}).click();await page.getByLabel('Virtual survey snapshot').selectOption('2');await page.getByLabel('Survey start longitude').fill('86');await page.getByLabel('Survey start latitude').fill('13');await page.getByLabel('Survey end longitude').fill('89');await page.getByLabel('Survey end latitude').fill('14');
  const response=page.waitForResponse(r=>r.url().endsWith('/expedition/survey'));await page.getByRole('button',{name:'Sample virtual route',exact:true}).click();const r=await (await response).json();await expect(page.getByLabel('Simulated survey results')).toContainText('2024-01-08 00:00 UTC');await page.getByLabel('Virtual survey sample',{exact:true}).selectOption('8');const sample=r.samples[8];await expect(page.getByLabel('Virtual survey source value')).toContainText(sample.value.toLocaleString('en-US',{maximumFractionDigits:6}));
  const subset=await (await page.request.get(`/api/cases/${bay}/subset?variable=temperature&time_index=2&representation=analytical&operation=depth_slice&depth_index=7`)).json();expect(sample.value).toBe(subset.values[sample.y_index*subset.longitude.length+sample.x_index]);expect(sample.longitude).toBe(subset.longitude[sample.x_index]);expect(sample.latitude).toBe(subset.latitude[sample.y_index]);expect(r.simulated).toBe(true);
});

test('benchmark reports negative findings, deterministic baselines and incomplete designs honestly',async({page})=>{
  test.setTimeout(60000);await open(page);const r=await experiment(page);expect(r.runs).toHaveLength(24);expect(r.random_seeds).toEqual([26067,26068,26069,26070,26071]);await expect(page.locator('.expedition-outcome')).toContainText('larger mean reconstruction error');expect(r.summary.find((s:{strategy:string})=>s.strategy==='selected').mean_rmse).toBeGreaterThan(r.summary.find((s:{strategy:string})=>s.strategy==='uniform').mean_rmse);
  await page.getByLabel('Station planning objective').selectOption('coverage');await update(page);await experiment(page);await expect(page.locator('.expedition-outcome')).toContainText('same design');
  await page.getByLabel('Station budget',{exact:true}).fill('16');await page.getByLabel('Station minimum spacing').fill('150');const limited=await update(page);expect(limited.fulfilled).toBe(false);await expect(page.getByLabel('Virtual Expedition',{exact:true})).toContainText('Only');const failed=await experiment(page);expect(failed.runs.filter((r:{strategy:string;status:string})=>r.strategy==='selected'&&r.status==='failed')).toHaveLength(3);await expect(page.getByLabel('Sampling strategy results')).toContainText('Some selected or uniform runs failed');
});

test('pending route retains the verified map line and draft plan cannot silently replace saved settings',async({page})=>{
  test.setTimeout(60000);await open(page);await page.getByRole('button',{name:'Sample a route',exact:true}).click();await page.getByRole('button',{name:'Sample virtual route',exact:true}).click();await expect(page.getByLabel('Virtual survey source value')).toBeVisible();const oldLine=await page.locator('.expedition-route-identity').innerText();let release!:()=>void;const gate=new Promise<void>(r=>release=r);await page.route('**/expedition/survey',async route=>{await gate;await route.continue();});await page.getByLabel('Survey end longitude').fill('88');await page.getByRole('button',{name:'Sample virtual route',exact:true}).click();await expect(page.locator('.expedition-route-identity')).toHaveText(oldLine,{useInnerText:true});await expect(page.locator('.expedition-map')).toContainText('B: 90, 13.5');release();await expect(page.locator('.expedition-route-identity')).toContainText('B: 88° E');await page.getByLabel('Station budget',{exact:true}).fill('4');await page.getByRole('button',{name:'Save expedition',exact:true}).click();await page.getByRole('button',{name:'Save on this browser',exact:true}).click();await expect(page.getByLabel('Selected saved investigation')).toBeVisible({timeout:25000});const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Investigation JSON',exact:true}).click();const data=JSON.parse(await readFile((await (await dl).path())!,'utf8'));expect(data.replay.recipe.query.budget).toBe(8);expect(data.replay.recipe.survey.end).toEqual([88,13.5]);
});

test('complete expedition saves, exports and replays in a fresh browser context',async({page,browser})=>{
  test.setTimeout(90000);await open(page);await page.getByRole('button',{name:'Sample a route',exact:true}).click();await page.getByLabel('Virtual survey snapshot').selectOption('4');await page.getByRole('button',{name:'Sample virtual route',exact:true}).click();await expect(page.getByLabel('Virtual survey source value')).toBeVisible();const benchmark=await experiment(page);await page.getByRole('button',{name:'Save expedition',exact:true}).click();await page.getByLabel('Investigation name',{exact:true}).fill('Sampling evidence');await page.getByRole('button',{name:'Save on this browser',exact:true}).click();await expect(page.getByLabel('Selected saved investigation')).toContainText('Sampling evidence',{timeout:25000});const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Investigation JSON',exact:true}).click();const record=JSON.parse(await readFile((await (await dl).path())!,'utf8'));expect(record.results.map((m:{module:string})=>m.module)).toEqual(['station_plan','virtual_survey','sampling_experiment']);expect(record.results[2].random_seed).toBe(26067);expect(record.results[2].output.summary).toEqual(benchmark.summary);
  const context=await browser.newContext(),other=await context.newPage();await enterWorkspace(other,page.url());await other.getByRole('button',{name:'Open saved investigations'}).click();await other.getByLabel('Open investigation file',{exact:true}).setInputFiles({name:'expedition.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(record))});await expect(other.getByLabel('Selected saved investigation')).toContainText('Sampling evidence');await other.getByRole('button',{name:'Recalculate and reopen',exact:true}).click();await expect(other.getByRole('dialog')).toHaveCount(0,{timeout:30000});await expect(other.getByLabel('Sampling strategy results')).toBeVisible({timeout:20000});await other.getByRole('button',{name:'Sample a route',exact:true}).click();await expect(other.getByLabel('Virtual survey snapshot')).toHaveValue('4');await expect(other.getByLabel('Simulated survey results')).toContainText('2024-01-09 00:00 UTC');await context.close();
});

test('malformed plan is rejected and service failure preserves a verified plan',async({page})=>{
  test.setTimeout(60000);await open(page);await page.route('**/expedition/plan',route=>route.fulfill({status:503,headers:{'X-Ocean-App-Version':version},contentType:'application/json',body:JSON.stringify({error:{message:'Expedition service unavailable.'}})}));await page.getByLabel('Station budget').fill('5');await page.getByRole('button',{name:'Update station plan',exact:true}).click();await expect(page.getByLabel('Virtual Expedition',{exact:true})).toContainText('Expedition service unavailable.');await expect(page.getByLabel('Applied expedition plan')).toContainText('8 of 8 stations');await page.unroute('**/expedition/plan');await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByLabel('Applied expedition plan')).toContainText('5 of 5 stations');
  await page.route('**/expedition/plan',async route=>{const response=await route.fetch(),r=await response.json();r.stations[0].prior_value+=100;await route.fulfill({response,json:r});});await page.getByLabel('Station budget').fill('6');await page.getByRole('button',{name:'Update station plan',exact:true}).click();await expect(page.getByLabel('Virtual Expedition',{exact:true})).toContainText('could not be verified');await expect(page.getByLabel('Applied expedition plan')).toContainText('5 of 5 stations');
});

test('route drawing and numbered station controls remain usable on narrow and enlarged layouts',async({page})=>{
  test.setTimeout(60000);await page.setViewportSize({width:320,height:850});await open(page);await page.getByRole('button',{name:'Select suggested station 3',exact:true}).click();await expect(page.locator('.expedition-station-value')).toContainText('Station 3');await page.getByRole('button',{name:'Sample a route',exact:true}).click();await page.getByRole('button',{name:'Draw a virtual route',exact:true}).click();const svg=page.getByRole('group',{name:'Expedition station map',exact:true});await svg.scrollIntoViewIfNeeded();for(const point of [[160,110],[490,245]]){const p=await svg.evaluate((el,[x,y])=>{const svg=el as SVGSVGElement,scroller=svg.parentElement!,bounds=scroller.getBoundingClientRect(),p=new DOMPoint(x,y).matrixTransform(svg.getScreenCTM()!);if(p.x>bounds.right-20)scroller.scrollLeft+=p.x-bounds.right+20;if(p.x<bounds.left+20)scroller.scrollLeft+=p.x-bounds.left-20;const shown=new DOMPoint(x,y).matrixTransform(svg.getScreenCTM()!);return {x:shown.x,y:shown.y};},point);await page.mouse.click(p.x,p.y);}await expect(page.getByLabel('Virtual survey source value')).toBeVisible({timeout:20000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.setViewportSize({width:768,height:1000});await page.addStyleTag({content:'html{font-size:200% !important}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await expect(page.getByLabel('Virtual survey sample',{exact:true})).toBeVisible();
});
