import {enterWorkspace,openTool} from './ux-helpers';
﻿import {test,expect,type Page} from '@playwright/test';
async function open(page:Page){await enterWorkspace(page);await openTool(page,'Open wider ocean coverage');await expect(page.getByRole('combobox',{name:'Data source',exact:true})).toBeEnabled();}
async function load(page:Page){await page.getByRole('button',{name:'Load region',exact:true}).click();await expect(page.locator('.wide-status')).toContainText(/Region loaded|bounded cache/,{timeout:25000});await expect(page.locator('.wide-error')).toHaveCount(0);}
async function point(page:Page){const canvas=page.locator('.wide-data-view canvas');await canvas.click({position:{x:170,y:140}});await expect(page.getByRole('heading',{name:'Native water column',exact:true})).toBeVisible();}

test('source availability, progressive loading, native profile and saved pack',async({page})=>{await open(page);await expect(page.locator('.wide-source-note').first()).toContainText('No observations');await load(page);await expect(page.locator('.wide-change')).toHaveCount(0);await expect(page.locator('.wide-resolution')).toContainText('Native selected grid');await point(page);await page.getByRole('button',{name:'Save regional pack on device',exact:true}).click();await expect(page.locator('.wide-status')).toContainText('Saved one regional pack');await page.getByRole('button',{name:'Verify replay online',exact:true}).click();await expect(page.locator('.wide-status')).toContainText('Server replay matched');await page.getByRole('button',{name:'Open saved regional pack',exact:true}).click();await expect(page.locator('.wide-result-heading')).toContainText('LOCAL PACK');await page.getByRole('button',{name:'Verify replay online',exact:true}).click();await expect(page.locator('.wide-status')).toContainText('Server replay matched');});

test('GODAS salinity preserves units and a second month',async({page})=>{await open(page);await page.getByRole('combobox',{name:'Regional variable',exact:true}).selectOption('source_salinity');await page.getByRole('combobox',{name:'Regional month',exact:true}).selectOption('1');await load(page);await expect(page.locator('.wide-result-heading')).toContainText('Source salinity');await expect(page.locator('.wide-colorbar')).toContainText('g/kg');await expect(page.locator('.wide-result-heading')).toContainText('2022-10');});

test('dateline and southern coverage use actual coordinates',async({page})=>{await open(page);await page.getByRole('button',{name:'Across the date line',exact:true}).click();await load(page);await expect(page.locator('.wide-result-heading')).toContainText('170.50° E');await expect(page.locator('.wide-result-heading')).toContainText('170.50° W');await page.getByRole('button',{name:'Southern Indian Ocean',exact:true}).click();await expect(page.locator('.wide-change')).toBeVisible();await load(page);await expect(page.locator('.wide-result-heading')).toContainText('S');});

test('ML product keeps pressure, exact uncertainty and original source labels',async({page})=>{await open(page);await page.getByRole('combobox',{name:'Data source',exact:true}).selectOption('gobai-v2.2');await load(page);await expect(page.getByRole('button',{name:'3D volume',exact:true})).toBeDisabled();await expect(page.locator('.wide-source-note').last()).toContainText('Provider uncertainty');await point(page);await page.getByText('Exact values and source indices',{exact:true}).click();await expect(page.getByRole('columnheader',{name:'Provider uncertainty',exact:true})).toBeVisible();await expect(page.getByRole('columnheader',{name:'dbar',exact:true})).toBeVisible();await page.getByText('Sources, scientific limits and method',{exact:true}).click();await expect(page.locator('.wide-provenance')).toContainText('archive release 4.4');await expect(page.locator('.wide-provenance')).toContainText('CC0');});

test('all-missing land selection is explicit',async({page})=>{await open(page);await page.getByText('Area and vertical limits',{exact:true}).click();for(const [label,value] of [['West longitude','10'],['East longitude','20'],['South latitude','15'],['North latitude','25']])await page.getByRole('spinbutton',{name:label,exact:true}).fill(value);await load(page);await expect(page.locator('.wide-resolution')).toContainText('0 valid loaded values');});

test('oversized and polar requests are explained',async({page})=>{await open(page);await page.getByText('Area and vertical limits',{exact:true}).click();for(const [label,value] of [['West longitude','0'],['East longitude','90'],['South latitude','-20'],['North latitude','20']])await page.getByRole('spinbutton',{name:label,exact:true}).fill(value);await page.getByRole('button',{name:'Load region',exact:true}).click();await expect(page.getByRole('alert')).toContainText('120,000');await page.getByRole('spinbutton',{name:'South latitude',exact:true}).fill('70');await page.getByRole('spinbutton',{name:'North latitude',exact:true}).fill('80');await page.getByRole('button',{name:'Load region',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Polar coverage');});

test('cancel ignores late data and edits survive a pending response',async({page})=>{await open(page);await page.route('**/api/wider/subset',async route=>{await new Promise(r=>setTimeout(r,700));await route.continue().catch(()=>{});});await page.getByRole('button',{name:'Load region',exact:true}).click();await expect(page.getByRole('button',{name:'Cancel request',exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Regional month',exact:true}).selectOption('1');await page.getByRole('button',{name:'Cancel request',exact:true}).click();await expect(page.locator('.wide-status')).toContainText('Cancelled');await expect(page.getByRole('combobox',{name:'Regional month',exact:true})).toHaveValue('1');await expect(page.locator('.wide-result-heading')).toHaveCount(0);});

test('browser cache reuses a completed field',async({page})=>{await open(page);await load(page);let subsets=0;page.on('request',r=>{if(r.url().endsWith('/api/wider/subset'))subsets++;});await load(page);await expect(page.locator('.wide-status')).toContainText('bounded cache');expect(subsets).toBe(0);});

test('offline pack opens with the network disabled',async({page,context})=>{await open(page);await load(page);await page.getByRole('button',{name:'Save regional pack on device',exact:true}).click();await expect(page.locator('.wide-status')).toContainText('Saved one regional pack');await context.setOffline(true);await page.getByRole('button',{name:'Open saved regional pack',exact:true}).click();await expect(page.locator('.wide-status')).toContainText('Checksum verified');await point(page);await expect(page.locator('.wide-error')).toHaveCount(0);await context.setOffline(false);});

test('tampered regional pack is rejected locally',async({page})=>{await open(page);await load(page);await page.getByRole('button',{name:'Save regional pack on device',exact:true}).click();await expect(page.locator('.wide-status')).toContainText('Saved one regional pack');await page.evaluate(()=>{const p=JSON.parse(localStorage.getItem('ocean-regional-pack-v1')!);p.payload_text+=' ';localStorage.setItem('ocean-regional-pack-v1',JSON.stringify(p));});await page.getByRole('button',{name:'Open saved regional pack',exact:true}).click();await expect(page.getByRole('alert')).toContainText('checksum');});

test('return to existing workspace and legal pages remains available',async({page})=>{await open(page);await expect(page.locator('.current-activity')).toHaveText('More regions');await openTool(page,'Ocean explorer');await expect(page.getByRole('region',{name:'Scientific ocean explorer',exact:true})).toBeVisible();await page.getByRole('link',{name:'Privacy Policy',exact:true}).click();await expect(page.getByRole('heading',{name:'Wider regional requests and offline packs',exact:true})).toBeVisible();});

test('native downloads carry a portable offline viewer',async({page})=>{await open(page);await load(page);const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download offline viewer',exact:true}).click();const file=await pending;expect(file.suggestedFilename()).toBe('ocean-region-offline.html');const stream=await file.createReadStream();const chunks=[];for await(const c of stream!)chunks.push(c);const text=Buffer.concat(chunks).toString();expect(text).toContain('p15-native-subset-v1');expect(text).not.toContain('<script src=');});

 test('single native level keeps sections and 3D unavailable',async({page})=>{await open(page);await page.getByText('Area and vertical limits',{exact:true}).click();await page.getByRole('spinbutton',{name:'Maximum depth',exact:true}).fill('5');await load(page);await expect(page.getByRole('button',{name:'Section',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'3D volume',exact:true})).toBeDisabled();await point(page);});


test('pressure axis text fits the canvas and picking follows its actual margin',async({page})=>{
 await page.addInitScript(()=>{const original=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text:string,x:number,y:number,...rest:[]){const width=this.measureText(text).width;if(this.textAlign==='right'&&text.endsWith(' dbar')&&x-width<0)throw new Error('Pressure axis label clipped');return original.call(this,text,x,y,...rest);};});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await open(page);await page.getByRole('combobox',{name:'Data source',exact:true}).selectOption('gobai-v2.2');await page.getByRole('button',{name:'Southern Indian Ocean',exact:true}).click();await load(page);await page.getByRole('button',{name:'Section',exact:true}).click();const canvas=page.locator('.wide-data-view canvas');const rect=await canvas.boundingBox();const response=page.waitForRequest(r=>r.url().endsWith('/api/wider/profile')&&r.postDataJSON().query.variable==='oxygen');await canvas.click({position:{x:86+(rect!.width-86-30)/2,y:130}});const request=await response;expect(request.postDataJSON().longitude).toBeCloseTo(70,1);await expect(page.getByRole('heading',{name:'Native water column',exact:true})).toBeVisible();expect(errors).toEqual([]);
});
