import { ApiError,appVersion } from '../contracts';

export const featureVariables={temperature:{label:'Temperature',units:'°C',threshold:26},salinity:{label:'Practical salinity',units:'psu',threshold:34},eastward_velocity:{label:'Eastward velocity',units:'m/s',threshold:.1},northward_velocity:{label:'Northward velocity',units:'m/s',threshold:.1},horizontal_kinetic_energy:{label:'Horizontal kinetic energy',units:'m²/s²',threshold:.05}} as const;
export type FeatureVariable=keyof typeof featureVariables;
export type FeatureQuery={variable:FeatureVariable;units:string;time_index:number;operator:'at_least'|'at_most'|'between';threshold:number;upper_threshold:number|null;depth_min_m:number;depth_max_m:number;order:'volume'|'observations'};
export type Axes={depth_m:number[];latitude:number[];longitude:number[]};
export type Bounds={west:number;south:number;east:number;north:number;depth_min_m:number;depth_max_m:number};
export type RegionSummary={id:string;cell_count:number;estimated_volume_km3:number;center_bounds:Bounds;cell_bounds:Bounds;min:number;max:number;mean:number;volume_weighted_mean:number;eligible_samples:number;eligible_profiles:number;observations:{profile_id:string;platform:string;sample_count:number}[]};
type Common={schema_version:'1';method_version:'p07-native-regions-v1';case_id:string;manifest_sha256:string;model_time:string;query:FeatureQuery;units:string;methods:string[];limitations:string[]};
export type FeatureSearch=Common&{kind:'threshold_regions';shape:[number,number,number];coordinates:Axes;edges:Axes;qualified_cells:number;total_regions:number;returned_regions:number;regions:RegionSummary[];footprint:{shape:[number,number];region_ids:(string|null)[]}};
export type FeatureRegion=Common&{kind:'threshold_region';region:RegionSummary;edges:Axes;faces:[number,number,number,number,number,number,number][];face_count:number|null;mesh_available:boolean;footprint_indices:number[]};
export type SectionRequest={query:FeatureQuery;start:[number,number];end:[number,number];stations:number};
export type FeatureSection=Common&{kind:'native_transect';start:[number,number];end:[number,number];stations:{longitude:number;latitude:number;distance_km:number;model_longitude:number;model_latitude:number;offset_km:number}[];depth_m:number[];shape:[number,number];values:(number|null)[];region_ids:(string|null)[];observations:{profile_id:string;platform:string;sample_index:number;depth_m:number;observed:number;station_index:number;distance_to_station_km:number}[]};
const object=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v);
const integer=(v:unknown):v is number=>finite(v)&&Number.isInteger(v)&&v>=0;
const strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.every(x=>typeof x==='string');
const numbers=(v:unknown):v is number[]=>Array.isArray(v)&&v.every(finite);
const regionId=(v:unknown):v is string=>typeof v==='string'&&/^r[0-9]{1,7}$/.test(v);
const fail=()=>new ApiError('The structure result could not be verified. Unverified values are not displayed.',undefined,'response');
const close=(a:number,b:number)=>Math.abs(a-b)<=1e-8*Math.max(1,Math.abs(a),Math.abs(b));
export function sameQuery(a:FeatureQuery,b:FeatureQuery){return Object.keys(a).every(k=>a[k as keyof FeatureQuery]===b[k as keyof FeatureQuery])&&Object.keys(a).length===Object.keys(b).length;}
function validQuery(v:unknown):v is FeatureQuery{return object(v)&&typeof v.variable==='string'&&v.variable in featureVariables&&v.units===featureVariables[v.variable as FeatureVariable].units&&integer(v.time_index)&&v.time_index<=6&&['at_least','at_most','between'].includes(String(v.operator))&&finite(v.threshold)&&finite(v.depth_min_m)&&finite(v.depth_max_m)&&v.depth_min_m>=0&&v.depth_max_m<=5000&&v.depth_min_m<v.depth_max_m&&['volume','observations'].includes(String(v.order))&&(v.operator==='between'?finite(v.upper_threshold)&&v.upper_threshold>=v.threshold:v.upper_threshold===null);}
function axes(v:unknown,strict:boolean):v is Axes{return object(v)&&['depth_m','latitude','longitude'].every(k=>numbers(v[k])&&(v[k] as number[]).length>0&&(v[k] as number[]).every((x,i,a)=>i===0||(strict?x>a[i-1]:x>=a[i-1])));}
function bounds(v:unknown):v is Bounds{return object(v)&&['west','south','east','north','depth_min_m','depth_max_m'].every(k=>finite(v[k]))&&Number(v.west)<=Number(v.east)&&Number(v.south)<=Number(v.north)&&Number(v.depth_min_m)<=Number(v.depth_max_m);}
function summary(v:unknown):v is RegionSummary{
  if(!object(v)||!regionId(v.id)||!integer(v.cell_count)||v.cell_count<1||!finite(v.estimated_volume_km3)||v.estimated_volume_km3<=0||!bounds(v.center_bounds)||!bounds(v.cell_bounds)||!['min','max','mean','volume_weighted_mean'].every(k=>finite(v[k]))||Number(v.min)>Number(v.max)||Number(v.mean)<Number(v.min)-1e-9||Number(v.mean)>Number(v.max)+1e-9||Number(v.volume_weighted_mean)<Number(v.min)-1e-9||Number(v.volume_weighted_mean)>Number(v.max)+1e-9||!integer(v.eligible_samples)||!integer(v.eligible_profiles)||!Array.isArray(v.observations)||v.observations.length!==v.eligible_profiles)return false;
  return v.observations.every(o=>object(o)&&typeof o.profile_id==='string'&&typeof o.platform==='string'&&integer(o.sample_count)&&o.sample_count>0)&&v.observations.reduce((n,o)=>n+o.sample_count,0)===v.eligible_samples;
}
function common(v:unknown):v is Common&Record<string,unknown>{return object(v)&&v.schema_version==='1'&&v.method_version==='p07-native-regions-v1'&&typeof v.case_id==='string'&&typeof v.manifest_sha256==='string'&&/^[a-f0-9]{64}$/.test(v.manifest_sha256)&&typeof v.model_time==='string'&&v.model_time.endsWith('Z')&&Number.isFinite(Date.parse(v.model_time))&&validQuery(v.query)&&v.units===v.query.units&&strings(v.methods)&&strings(v.limitations);}
export function parseSearch(v:unknown):FeatureSearch{
  if(!common(v)||v.kind!=='threshold_regions'||!Array.isArray(v.shape)||v.shape.length!==3||!v.shape.every(integer)||!axes(v.coordinates,true)||!axes(v.edges,false)||!['qualified_cells','total_regions','returned_regions'].every(k=>integer(v[k]))||!Array.isArray(v.regions)||v.regions.length!==v.returned_regions||v.regions.length>50||!v.regions.every(summary)||Number(v.returned_regions)>Number(v.total_regions)||!object(v.footprint)||!numbers(v.footprint.shape)||v.footprint.shape.length!==2||!Array.isArray(v.footprint.region_ids))throw fail();
  const r=v as FeatureSearch,n=r.shape.reduce((a,b)=>a*b,1);if(r.qualified_cells>n||r.total_regions>r.qualified_cells||r.footprint.shape[0]!==r.shape[1]||r.footprint.shape[1]!==r.shape[2]||r.footprint.region_ids.length!==r.shape[1]*r.shape[2]||!r.footprint.region_ids.every(x=>x===null||regionId(x))||new Set(r.regions.map(x=>x.id)).size!==r.regions.length||r.regions.reduce((s,x)=>s+x.cell_count,0)>r.qualified_cells)throw fail();
  if(r.returned_regions===r.total_regions&&r.regions.reduce((s,x)=>s+x.cell_count,0)!==r.qualified_cells||r.total_regions===0&&r.footprint.region_ids.some(x=>x!==null))throw fail();
  (['depth_m','latitude','longitude'] as const).forEach((k,i)=>{if(r.coordinates[k].length!==r.shape[i]||r.edges[k].length!==r.shape[i]+1)throw fail();});return r;
}
export function parseRegion(v:unknown):FeatureRegion{
  if(!common(v)||v.kind!=='threshold_region'||!summary(v.region)||!axes(v.edges,false)||typeof v.mesh_available!=='boolean'||!Array.isArray(v.faces)||(v.mesh_available?(!integer(v.face_count)||v.faces.length!==v.face_count):(v.face_count!==null||v.faces.length!==0))||v.faces.length>100000||!Array.isArray(v.footprint_indices)||!v.footprint_indices.every(integer))throw fail();
  const r=v as FeatureRegion,dimensions=[r.edges.depth_m.length,r.edges.latitude.length,r.edges.longitude.length];if(r.footprint_indices.some(i=>i>=(dimensions[1]-1)*(dimensions[2]-1))||new Set(r.footprint_indices).size!==r.footprint_indices.length)throw fail();
  for(const f of r.faces){if(!numbers(f)||f.length!==7||!f.slice(0,6).every(integer)||![0,1,2].includes(f[0])||![-1,1].includes(f[6]))throw fail();const other=[0,1,2].filter(a=>a!==f[0]);if(f[1]>=dimensions[f[0]]||f[2]>=f[3]||f[4]>=f[5]||f[3]>=dimensions[other[0]]||f[5]>=dimensions[other[1]])throw fail();}return r;
}
export function parseSection(v:unknown):FeatureSection{
  if(!common(v)||v.kind!=='native_transect'||!numbers(v.start)||v.start.length!==2||!numbers(v.end)||v.end.length!==2||!numbers(v.depth_m)||!numbers(v.shape)||v.shape.length!==2||!v.shape.every(integer)||!Array.isArray(v.stations)||v.stations.length<2||v.stations.length>201||!Array.isArray(v.values)||!v.values.every(x=>x===null||finite(x))||!Array.isArray(v.region_ids)||!v.region_ids.every(x=>x===null||regionId(x))||!Array.isArray(v.observations))throw fail();
  const r=v as FeatureSection;if(r.shape[0]!==r.depth_m.length||r.shape[1]!==r.stations.length||r.values.length!==r.shape[0]*r.shape[1]||r.region_ids.length!==r.values.length||r.depth_m.some((d,i)=>d<r.query.depth_min_m||d>r.query.depth_max_m||i>0&&d<=r.depth_m[i-1]))throw fail();
  if(!r.stations.every((s,i)=>object(s)&&(['longitude','latitude','distance_km','model_longitude','model_latitude','offset_km'] as const).every(k=>finite(s[k]))&&s.distance_km>=0&&s.offset_km>=0&&(i===0?close(s.distance_km,0):s.distance_km>r.stations[i-1].distance_km)))throw fail();
  if(!r.observations.every(o=>object(o)&&typeof o.profile_id==='string'&&typeof o.platform==='string'&&integer(o.sample_index)&&integer(o.station_index)&&o.station_index<r.stations.length&&finite(o.depth_m)&&o.depth_m>=r.query.depth_min_m&&o.depth_m<=r.query.depth_max_m&&finite(o.observed)&&finite(o.distance_to_station_km)&&o.distance_to_station_km>=0&&o.distance_to_station_km<=5))throw fail();return r;
}
export function verifyFeature<T extends FeatureSearch|FeatureRegion|FeatureSection>(r:T,q:FeatureQuery,caseId:string,time:string,hash?:string):T{if(!sameQuery(r.query,q)||r.case_id!==caseId||r.model_time!==time||hash&&r.manifest_sha256!==hash)throw fail();return r;}
export async function postFeature<T>(path:string,body:unknown,parse:(v:unknown)=>T,signal?:AbortSignal):Promise<T>{
  const controller=new AbortController(),abort=()=>controller.abort();if(signal?.aborted)controller.abort();signal?.addEventListener('abort',abort,{once:true});const timer=window.setTimeout(abort,25000);
  try{const response=await fetch(path,{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',Accept:'application/json'},cache:'no-store',body:JSON.stringify(body)}),id=response.headers.get('X-Request-ID')??undefined,version=response.headers.get('X-Ocean-App-Version');if(version&&version!==appVersion)throw new ApiError('The workspace has been updated. Reload to use the current version.',id,'update');const text=await response.text();let payload:unknown;try{payload=JSON.parse(text);}catch{throw new ApiError('The service returned an unreadable structure result.',id,'response');}if(!response.ok){const error=object(payload)&&object(payload.error)?payload.error:null;throw new ApiError(error&&typeof error.message==='string'?error.message:'The structure service is unavailable. Please try again.',id);}return parse(payload);}
  catch(e){if(e instanceof ApiError||signal?.aborted)throw e;throw new ApiError(controller.signal.aborted?'The structure calculation took too long. Try the query again.':'Could not reach the structure service. Check your connection and try again.');}
  finally{window.clearTimeout(timer);signal?.removeEventListener('abort',abort);}
}
export const format=(v:number,digits=3)=>v!==0&&Math.abs(v)<10**(-digits)?v.toPrecision(3):v.toLocaleString('en-US',{maximumFractionDigits:digits});
export const timestamp=(v:string)=>v.replace('T',' ').replace(/:00Z$/,' UTC');
export function queryLabel(q:FeatureQuery){return `${featureVariables[q.variable].label} ${q.operator==='at_least'?'≥':q.operator==='at_most'?'≤':'from'} ${q.threshold}${q.operator==='between'?` to ${q.upper_threshold}`:''} ${q.units}, ${q.depth_min_m}–${q.depth_max_m} m`;}
