import { ObservationSupport,type SupportTutorialStatus } from './ObservationSupport';
import type { ImportSources } from '../instruments/imported';
import type { SupportRow } from './support';
import type { MatchSettings } from '../evidence/contracts';
import { longitudeLabel,latitudeLabel } from '../geography';
import type { FeatureRecipe,SaveDraft } from '../investigations/contracts';
import { lazy,Suspense,useEffect,useMemo,useState } from 'react';
import { useLearningTool, modelSource } from '../learning/bridge';
import { keepPreviousData,useQuery,useQueryClient } from '@tanstack/react-query';
import { ArrowRight,Download,Info,LoaderCircle,MapPin,RefreshCw,Search,Split } from 'lucide-react';
import { ApiError,appVersion,type CaseManifest } from '../contracts';
import { FeatureMap } from './FeatureMap';
import { SectionView } from './SectionView';
import { featureVariables,format,parseRegion,parseSearch,parseSection,postFeature,queryLabel,sameQuery,timestamp,verifyFeature,type FeatureQuery,type FeatureVariable,type SectionRequest,type FeatureSearch,type FeatureSection } from './contracts';
import './features.css';
const RegionMesh=lazy(()=>import('./RegionMesh'));
type Point=[number,number];
type Props={importSources:ImportSources;onSupportCompare:(row:SupportRow,settings:MatchSettings)=>void;manifest:CaseManifest;timeIndex:number;onTime:(i:number)=>void;active:boolean;onObservation:(id:string)=>void;restore?:FeatureRecipe;onSave?:(draft:SaveDraft)=>void};
const initial=(time:number,manifest:CaseManifest):FeatureQuery=>({variable:'temperature',units:'°C',time_index:time,operator:'at_least',threshold:26,upper_threshold:null,depth_min_m:manifest.coordinates.depth_m[0],depth_max_m:Math.min(300,manifest.coordinates.depth_m.at(-1)!),order:'volume'});
function ErrorNotice({error,retry}:{error:Error;retry:()=>void}){const reload=error instanceof ApiError&&error.kind!=='service';return <div className="feature-error" role="alert"><div><strong>{reload?'The response could not be verified.':'The calculation could not finish.'}</strong><p>{error.message}</p></div><button className="secondary-button" onClick={reload?()=>window.location.reload():retry}><RefreshCw size={15}/>{reload?'Reload workspace':'Try again'}</button></div>;}
function download(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function FeatureWorkspace({manifest,timeIndex,onTime,active,onObservation,restore,onSave,importSources,onSupportCompare}:Props){
  const queryClient=useQueryClient();
  const [supportTutorial,setSupportTutorial]=useState<{action:string;id:number}|null>(null),[supportStatus,setSupportStatus]=useState<SupportTutorialStatus>();
  const [cancelled,setCancelled]=useState(false);
  function cancelWork(){setCancelled(true);for(const name of ['features-search','feature-region','feature-section'])void queryClient.cancelQueries({queryKey:[name,appVersion,manifest.case.id]});}
  const [variable,setVariable]=useState<FeatureVariable>(restore?.query.variable??'temperature'),[operator,setOperator]=useState<FeatureQuery['operator']>(restore?.query.operator??'at_least'),[threshold,setThreshold]=useState(String(restore?.query.threshold??26)),[upper,setUpper]=useState(String(restore?.query.upper_threshold??28)),[depthMin,setDepthMin]=useState(String(restore?.query.depth_min_m??manifest.coordinates.depth_m[0])),[depthMax,setDepthMax]=useState(String(restore?.query.depth_max_m??Math.min(300,manifest.coordinates.depth_m.at(-1)!))),[order,setOrder]=useState<FeatureQuery['order']>(restore?.query.order??'volume'),[submitted,setSubmitted]=useState<FeatureQuery|null>(restore?.query??null),[selected,setSelected]=useState(restore?.selected_region??''),[formError,setFormError]=useState(''),[drawing,setDrawing]=useState(false),[start,setStart]=useState<Point|null>(restore?.section?.start??null),[end,setEnd]=useState<Point|null>(restore?.section?.end??null),[sectionRequest,setSectionRequest]=useState<SectionRequest|null>(restore?.section??null),[sectionError,setSectionError]=useState(''),[graphics,setGraphics]=useState<'3d'|'basic'>(restore?.graphics??'3d');
  const [sectionSelection,setSectionSelection]=useState({pick:restore?.section_pick??0,showObservations:restore?.show_observations??true}),[exaggeration,setExaggeration]=useState<FeatureRecipe["exaggeration"]>(restore?.exaggeration??1000);
  const [verifiedSearch,setVerifiedSearch]=useState<FeatureSearch>(),[verifiedSection,setVerifiedSection]=useState<FeatureSection>();
  const labelQuery=(query:FeatureQuery)=>manifest.representations?.temporal_support?.kind==='calendar_month_mean'?queryLabel(query).replace(featureVariables[query.variable].label,manifest.variables.find(item=>item.id===query.variable)?.label??featureVariables[query.variable].label):queryLabel(query);
  const c=manifest.coordinates,caseId=manifest.case.id,base=`/api/cases/${encodeURIComponent(caseId)}/features`;
  const [aLon,setALon]=useState(String(restore?.section?.start[0]??c.longitude[0])),[aLat,setALat]=useState(String(restore?.section?.start[1]??(c.latitude[0]+c.latitude.at(-1)!)/2)),[bLon,setBLon]=useState(String(restore?.section?.end[0]??c.longitude.at(-1)!)),[bLat,setBLat]=useState(String(restore?.section?.end[1]??(c.latitude[0]+c.latitude.at(-1)!)/2));
  useEffect(()=>{if(active&&!submitted)setSubmitted(initial(timeIndex,manifest));},[active,submitted,timeIndex]);
  const searchQuery=useQuery({queryKey:['features-search',appVersion,caseId,submitted],queryFn:({signal})=>postFeature(`${base}/search`,submitted,v=>{const r=verifyFeature(parseSearch(v),submitted!,caseId,c.times[submitted!.time_index]);for(const k of ['depth_m','latitude','longitude'] as const)if(JSON.stringify(r.coordinates[k])!==JSON.stringify(c[k]))throw new ApiError('The search grid does not match this case.',undefined,'response');return r;},signal),enabled:active&&!cancelled&&Boolean(submitted),placeholderData:keepPreviousData,staleTime:Infinity,gcTime:600000});
  useEffect(()=>{if(searchQuery.data&&!searchQuery.isPlaceholderData)setVerifiedSearch(searchQuery.data);},[searchQuery.data,searchQuery.isPlaceholderData]);
  const result=searchQuery.data??verifiedSearch,selectedId=result?.regions.some(r=>r.id===selected)?selected:result?.regions[0]?.id??'',chosen=result?.regions.find(r=>r.id===selectedId);
  const regionQuery=useQuery({queryKey:['feature-region',appVersion,caseId,result?.query,selectedId],queryFn:({signal})=>postFeature(`${base}/region`,{query:result!.query,region_id:selectedId},v=>{const r=verifyFeature(parseRegion(v),result!.query,caseId,result!.model_time,result!.manifest_sha256);if(r.region.id!==selectedId||chosen&&(['cell_count','estimated_volume_km3','min','max','mean','volume_weighted_mean','eligible_samples','eligible_profiles'] as const).some(k=>r.region[k]!==chosen[k]))throw new ApiError('The selected region does not match the returned boundary.',undefined,'response');return r;},signal),enabled:active&&!cancelled&&Boolean(result&&selectedId),staleTime:Infinity,gcTime:600000});
  const sectionQuery=useQuery({queryKey:['feature-section',appVersion,caseId,sectionRequest],queryFn:({signal})=>postFeature(`${base}/section`,sectionRequest,v=>{const r=verifyFeature(parseSection(v),sectionRequest!.query,caseId,c.times[sectionRequest!.query.time_index],result?.manifest_sha256);if(JSON.stringify(r.start)!==JSON.stringify(sectionRequest!.start)||JSON.stringify(r.end)!==JSON.stringify(sectionRequest!.end)||r.stations.length!==sectionRequest!.stations)throw new ApiError('The section does not match the requested line.',undefined,'response');return r;},signal),enabled:active&&!cancelled&&Boolean(sectionRequest),placeholderData:keepPreviousData,staleTime:Infinity,gcTime:600000});
  useEffect(()=>{if(sectionQuery.data&&!sectionQuery.isPlaceholderData)setVerifiedSection(sectionQuery.data);},[sectionQuery.data,sectionQuery.isPlaceholderData]);
  const draft=useMemo<FeatureQuery>(()=>({variable,units:featureVariables[variable].units,time_index:timeIndex,operator,threshold:Number(threshold),upper_threshold:operator==='between'?Number(upper):null,depth_min_m:Number(depthMin),depth_max_m:Number(depthMax),order}),[variable,timeIndex,operator,threshold,upper,depthMin,depthMax,order]);
  const changed=Boolean(result&&!sameQuery(draft,result.query)),previous=Boolean(result&&submitted&&!sameQuery(submitted,result.query)),section=sectionQuery.data??verifiedSection,sectionMatches=Boolean(section&&result&&sameQuery(section.query,result.query));
  useLearningTool('features',active,{
    tool:'features',caseId,status:searchQuery.error||supportTutorial&&supportStatus?.error?'error':searchQuery.isFetching||!result||supportTutorial&&(!supportStatus||supportStatus.busy)?'loading':'ready',title:'Water matching your rule',kind:'derived',
    facts:supportTutorial?[{label:'Eligible samples in region',value:supportStatus?.pairs??null},{label:'Supported native cells',value:supportStatus?.cells??null},{label:'Time window either side',value:supportStatus?.hours??null,unit:'hours'}]:[{label:'Qualifying native cells',value:result?.qualified_cells??null},{label:'Connected regions',value:result?.total_regions??null},{label:'Threshold',value:result?.query.threshold??null,unit:result?.query.units},{label:'Model time (UTC)',value:result?.model_time??null}],parameters:result?{variable:result.query.variable,threshold:result.query.threshold,depth_min_m:result.query.depth_min_m,depth_max_m:result.query.depth_max_m}:{},
    sources:[modelSource(caseId)],limits:['A connected threshold region is not proof of an eddy or a tracked water parcel.','The search uses native model cells, not the display pixels.'],message:searchQuery.error?.message??supportStatus?.error,
  },command=>{if(command.action==='support'||command.action==='sensitivity'){setSupportStatus(undefined);setSupportTutorial({action:command.action,id:command.id});onTime(1);setSubmitted(initial(1,manifest));setSelected('');return true;}setSupportTutorial(null);if(command.action==='inspect'){if(searchQuery.error)void searchQuery.refetch();return true;}if(command.action==='run'){run();return true;}throw new Error('This structure action is not supported.');});
  function run(event?:React.FormEvent){event?.preventDefault();if(!threshold.trim()||!depthMin.trim()||!depthMax.trim()||operator==='between'&&!upper.trim()||![draft.threshold,draft.depth_min_m,draft.depth_max_m,...(draft.upper_threshold===null?[]:[draft.upper_threshold])].every(Number.isFinite)){setFormError('Enter a finite number in every query field.');return;}if(draft.depth_min_m<c.depth_m[0]||draft.depth_max_m>c.depth_m.at(-1)!||draft.depth_min_m>=draft.depth_max_m){setFormError(`Choose a minimum depth below the maximum, between ${c.depth_m[0]} and ${c.depth_m.at(-1)!.toLocaleString()} m.`);return;}if(draft.upper_threshold!==null&&draft.upper_threshold<draft.threshold){setFormError('The upper threshold must be at least the lower threshold.');return;}setFormError('');setCancelled(false);setSubmitted({...draft});setDrawing(false);if(submitted&&sameQuery(draft,submitted))void searchQuery.refetch();}
  function changeVariable(v:FeatureVariable){setVariable(v);setThreshold(String(featureVariables[v].threshold));setUpper(String(featureVariables[v].threshold+(v.includes('velocity')||v==='horizontal_kinetic_energy'?.1:1)));}
  function makeSection(a:Point,b:Point){if(!result)return;setCancelled(false);if(a.some(v=>!Number.isFinite(v))||b.some(v=>!Number.isFinite(v))||a[0]===b[0]&&a[1]===b[1]){setSectionError('Choose two different, finite positions for A and B.');return;}if([a,b].some(p=>p[0]<c.longitude[0]||p[0]>c.longitude.at(-1)!||p[1]<c.latitude[0]||p[1]>c.latitude.at(-1)!)){setSectionError('Both endpoints must be inside the displayed study area.');return;}setSectionError('');setStart(a);setEnd(b);setALon(String(a[0]));setALat(String(a[1]));setBLon(String(b[0]));setBLat(String(b[1]));setSectionSelection({pick:0,showObservations:true});setSectionRequest({query:result.query,start:a,end:b,stations:81});setDrawing(false);}
  function point(p:Point){if(!start){setStart(p);setEnd(null);setALon(String(p[0]));setALat(String(p[1]));}else makeSection(start,p);}
  function acrossSelected(){if(!chosen||!result)return;const b=chosen.center_bounds,lat=(b.south+b.north)/2;makeSection([c.longitude[0],lat],[c.longitude.at(-1)!,lat]);}
  const busy=searchQuery.isFetching;
  return <section className="feature-workspace" aria-label="Underwater structure search">
    <header className="feature-heading"><span className="eyebrow">FIND STRUCTURES / HISTORICAL MODEL</span><h2>Ask where the water meets a condition</h2><p>Set a value and depth range. Inspect the connected regions, then draw a line to see what happens underneath.</p><div className="feature-steps"><span><b>1</b>Set a condition</span><ArrowRight size={14}/><span><b>2</b>Inspect a region</span><ArrowRight size={14}/><span><b>3</b>Draw a section</span></div></header>
    {onSave&&<div className="save-analysis"><button className="secondary-button" disabled={!result||busy||searchQuery.isError||sectionQuery.isFetching||changed} onClick={()=>result&&onSave({expected_model_sha256:result.manifest_sha256,recipe:{mode:"features",case_id:caseId,query:result.query,selected_region:selectedId||null,section:section&&sectionMatches?{query:section.query,start:section.start,end:section.end,stations:section.stations.length}:null,section_pick:section&&sectionMatches?sectionSelection.pick:0,show_observations:sectionSelection.showObservations,graphics,exaggeration}})}>Save investigation</button></div>}
    <form className="feature-query" onSubmit={run} aria-label="Structure search query"><label>Find in<select aria-label="Structure variable" value={variable} onChange={e=>changeVariable(e.target.value as FeatureVariable)}>{Object.entries(featureVariables).filter(([id])=>id==='horizontal_kinetic_energy'?manifest.case.variables.includes('eastward_velocity')&&manifest.case.variables.includes('northward_velocity'):manifest.case.variables.includes(id as 'temperature'|'salinity'|'eastward_velocity'|'northward_velocity')).map(([key,v])=><option value={key} key={key}>{manifest.variables.find(variable=>variable.id===key)?.label??v.label}</option>)}</select></label><label>Condition<select aria-label="Threshold condition" value={operator} onChange={e=>setOperator(e.target.value as FeatureQuery['operator'])}><option value="at_least">At least (≥)</option><option value="at_most">At most (≤)</option><option value="between">Between (inclusive)</option></select></label><label>{operator==='between'?'Lower value':'Value'} ({featureVariables[variable].units})<input aria-label="Structure threshold" type="number" step="any" value={threshold} onChange={e=>setThreshold(e.target.value)} required/></label>{operator==='between'&&<label>Upper value ({featureVariables[variable].units})<input aria-label="Structure upper threshold" type="number" step="any" value={upper} onChange={e=>setUpper(e.target.value)} required/></label>}<label>From depth (m)<input aria-label="Minimum search depth" type="number" min={c.depth_m[0]} max={c.depth_m.at(-1)!} step="any" value={depthMin} onChange={e=>setDepthMin(e.target.value)} required/></label><label>To depth (m)<input aria-label="Maximum search depth" type="number" min={c.depth_m[0]} max={c.depth_m.at(-1)!} step="any" value={depthMax} onChange={e=>setDepthMax(e.target.value)} required/></label><label className="feature-time-field">Model snapshot (UTC)<select aria-label="Structure model snapshot" value={timeIndex} onChange={e=>onTime(Number(e.target.value))}>{c.times.map((t,i)=><option value={i} key={t}>{timestamp(t)}</option>)}</select></label><label className="feature-order-field">Order regions by<select aria-label="Order regions by" value={order} onChange={e=>setOrder(e.target.value as FeatureQuery['order'])}><option value="volume">Largest estimated volume</option><option value="observations">Most eligible samples</option></select></label><button className="primary-button feature-run" type="submit" disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:<Search size={17}/>} {busy?'Finding regions…':'Find regions'}</button><p className="feature-query-hint">Values on the boundary are included. Source date: {timestamp(c.times[timeIndex])}. Search uses the full native grid. {manifest.variables.find(item=>item.id===variable)?.definition}</p>{formError&&<p className="feature-error" role="alert">{formError}</p>}</form>
    {(busy||sectionQuery.isFetching||regionQuery.isFetching)&&<div className="feature-notice" role="status">Calculating from the native grid. <button className="secondary-button" onClick={cancelWork}>Cancel calculation</button></div>}
    {cancelled&&<p className="feature-notice" role="status">Calculation cancelled. Any previous result keeps its original settings. Choose Find regions to run the current query.</p>}
    {searchQuery.error&&<ErrorNotice error={searchQuery.error} retry={()=>void searchQuery.refetch()}/>}
    {!result&&busy&&<div className="feature-initial" role="status"><LoaderCircle className="spin" size={26}/><h3>Checking the native water column</h3><p>Testing your condition and joining cells that share a face.</p></div>}
    {result&&<div className="feature-results" aria-label="Structure search results"><div className="feature-result-header"><div><span className="eyebrow">{previous?'PREVIOUS VERIFIED RESULT':'VERIFIED QUERY RESULT'}</span><h3>{result.total_regions===0?'No regions meet this condition':`${result.total_regions} connected ${result.total_regions===1?'region':'regions'}`}</h3><p>{labelQuery(result.query)}<br/>{timestamp(result.model_time)}</p></div><button className="secondary-button" onClick={()=>download({app_version:appVersion,result,selected_region:regionQuery.data??null,section:sectionMatches?section:null},`ocean-structures-${result.query.variable}-${result.model_time.slice(0,10)}.json`)}><Download size={15}/>Export query results</button></div>
      {(changed||previous)&&<p className="feature-notice" role="status">{busy?'The new query is calculating. The verified result below still uses the condition and timestamp printed above.':'The controls have changed. Select Find regions to update the results below.'}</p>}
      <div className="feature-method-strip"><Info size={17}/><p>These are neighbouring cells that meet your condition, not automatically identified eddies or moving water parcels. Volume is estimated from coordinate midpoint bins because the source does not supply cell boundaries.</p></div>
      {result.total_regions===0?<div className="feature-empty"><h3>Try a wider condition or depth range</h3><p>Missing cells are excluded. An empty result does not prove that the condition is absent outside this study area or between sampled levels.</p></div>:<>
        <div className="feature-overview"><div className="feature-map-panel"><div className="feature-panel-heading"><h3>2. Inspect a region</h3><span>{format(result.qualified_cells,0)} qualifying native cells</span></div><FeatureMap result={result} region={regionQuery.data} selected={selectedId} onSelect={setSelected} drawing={drawing} onPoint={point} start={start} end={end}/><div className="feature-map-actions"><button className="primary-button" aria-pressed={drawing} onClick={()=>{setDrawing(!drawing);setStart(null);setEnd(null);}}><Split size={16}/>{drawing?'Cancel drawing':'Draw a section'}</button><button className="secondary-button" onClick={acrossSelected}>Section through selected region</button></div>{drawing&&<p className="feature-notice" role="status">{start?'Now select B, the end of your line.':'Select A on the plan view, then B. You can also enter coordinates below.'}</p>}<p className="feature-note">Mint: other qualifying regions. Amber: selected region. Dark blue: no qualifying cells in that column.</p></div>
        <div className="feature-inspector" aria-label="Selected structure inspector"><div className="feature-panel-heading"><h3>Selected region</h3><label>View<select aria-label="Structure graphics" value={graphics} onChange={e=>setGraphics(e.target.value as '3d'|'basic')}><option value="3d">3D boundary</option><option value="basic">Plan and numbers</option></select></label></div>{chosen&&<><p className="feature-region-id">{chosen.id} · {format(chosen.cell_count,0)} native cells</p>{graphics==='3d'&&(regionQuery.data?<Suspense fallback={<p className="feature-note">Preparing the 3D boundary…</p>}><RegionMesh result={regionQuery.data} active={active} exaggerationValue={exaggeration} onExaggeration={n=>setExaggeration(n as FeatureRecipe["exaggeration"])}/></Suspense>:<p className="feature-note" role="status">Loading the selected boundary…</p>)}{regionQuery.error&&<ErrorNotice error={regionQuery.error} retry={()=>void regionQuery.refetch()}/>}<dl className="feature-facts"><div><dt>Estimated volume</dt><dd>{format(chosen.estimated_volume_km3,3)} km³</dd></div><div><dt>Native-centre depth span</dt><dd>{format(chosen.center_bounds.depth_min_m)} to {format(chosen.center_bounds.depth_max_m)} m</dd></div><div><dt>Value range</dt><dd>{format(chosen.min,4)} to {format(chosen.max,4)} {result.units}</dd></div><div><dt>Volume-weighted mean</dt><dd>{format(chosen.volume_weighted_mean,4)} {result.units}</dd></div><div><dt>Longitude span</dt><dd>{longitudeLabel(chosen.center_bounds.west,4)} to {longitudeLabel(chosen.center_bounds.east,4)}</dd></div><div><dt>Latitude span</dt><dd>{latitudeLabel(chosen.center_bounds.south,4)} to {latitudeLabel(chosen.center_bounds.north,4)}</dd></div></dl><div className="feature-observation-links"><h4>{chosen.eligible_samples} eligible samples in {chosen.eligible_profiles} profiles</h4><p>{manifest.representations?.science_compatibility?.direct_observation_residual===false?'Observation association is unavailable for this monthly potential-temperature field. Original in-situ profiles remain inspectable in Instruments.':'Under fixed comparison rules: ±6 hours, 5 km, depth bracket up to 500 m and accepted quality flags. An observation occupies a qualifying cell in its matched column; its measured value may differ from the threshold.'}</p>{chosen.observations.map(p=><button className="secondary-button" key={p.profile_id} onClick={()=>onObservation(p.profile_id)}><MapPin size={14}/>{p.platform} · {p.sample_count} samples</button>)}{chosen.eligible_samples===0&&<p>{result.query.variable==='temperature'||result.query.variable==='salinity'?(manifest.representations?.science_compatibility?.direct_observation_residual===false?'No direct comparison is calculated between these different quantities.':'No bundled observations meet these association rules for this region and timestamp.'):'The library has no comparable velocity or kinetic-energy observations.'}</p>}</div></>}</div></div>
        <ObservationSupport tutorial={supportTutorial} onTutorialStatus={setSupportStatus} key={JSON.stringify(result.query)+selectedId} result={result} regionId={selectedId} importSources={importSources} active={active&&!busy&&!previous&&!cancelled} onCompare={onSupportCompare}/>
        <div className="feature-region-list" aria-label="Connected region results"><div className="feature-panel-heading"><h3>Choose a connected region</h3><span>{result.returned_regions<result.total_regions?`Showing the first ${result.returned_regions} of ${result.total_regions}`:`${result.returned_regions} ${result.returned_regions===1?'result':'results'}`} · {result.query.order==='volume'?'largest volume first':'most eligible samples first'}</span></div><div className="feature-table-scroll"><table><thead><tr><th scope="col">Region</th><th scope="col">Est. volume (km³)</th><th scope="col">Depth centres (m)</th><th scope="col">Eligible samples</th></tr></thead><tbody>{result.regions.map((r,i)=><tr key={r.id} className={r.id===selectedId?'selected':''}><th scope="row"><button aria-pressed={r.id===selectedId} onClick={()=>setSelected(r.id)}>Select region {i+1}<span>{r.id}</span></button></th><td>{format(r.estimated_volume_km3,2)}</td><td>{format(r.center_bounds.depth_min_m)} to {format(r.center_bounds.depth_max_m)}</td><td>{r.eligible_samples} in {r.eligible_profiles} profiles</td></tr>)}</tbody></table></div></div>
      </>}
      <section className="feature-transect" aria-label="Draw a question"><div className="feature-panel-heading"><h3>3. Draw a question</h3><span>A line through the native water column</span></div><p>Draw two points in the plan view or enter A and B here. The section shows all source values along the line, including values outside your condition.</p><form className="feature-line-form" onSubmit={e=>{e.preventDefault();makeSection([Number(aLon),Number(aLat)],[Number(bLon),Number(bLat)]);}}><fieldset><legend>A · start</legend><label>Longitude (° E)<input aria-label="Section start longitude" type="number" step="any" min={c.longitude[0]} max={c.longitude.at(-1)!} value={aLon} onChange={e=>setALon(e.target.value)} required/></label><label>Latitude (° N)<input aria-label="Section start latitude" type="number" step="any" min={c.latitude[0]} max={c.latitude.at(-1)!} value={aLat} onChange={e=>setALat(e.target.value)} required/></label></fieldset><fieldset><legend>B · end</legend><label>Longitude (° E)<input aria-label="Section end longitude" type="number" step="any" min={c.longitude[0]} max={c.longitude.at(-1)!} value={bLon} onChange={e=>setBLon(e.target.value)} required/></label><label>Latitude (° N)<input aria-label="Section end latitude" type="number" step="any" min={c.latitude[0]} max={c.latitude.at(-1)!} value={bLat} onChange={e=>setBLat(e.target.value)} required/></label></fieldset><button className="primary-button" disabled={sectionQuery.isFetching} type="submit">{sectionQuery.isFetching?<LoaderCircle className="spin" size={16}/>:<Split size={16}/>}Build section</button></form>{sectionError&&<p role="alert" className="feature-error">{sectionError}</p>}{sectionQuery.error&&<ErrorNotice error={sectionQuery.error} retry={()=>void sectionQuery.refetch()}/>}<p className="feature-note">81 stations along a straight longitude/latitude line. Each uses the nearest native column by great-circle distance. No values are interpolated or filled across missing water.</p>{section&&sectionMatches&&<><p className="feature-section-status" role="status">Section at {timestamp(section.model_time)}{sectionQuery.isPlaceholderData?' · A new line is loading; the section below still shows the previous verified line.':''}</p><p className="feature-note">{[Number(aLon),Number(aLat),Number(bLon),Number(bLat)].some((v,i)=>v!==[...section.start,...section.end][i])?'The endpoint controls differ from the displayed section. Build section to apply them.':'The displayed section uses the A and B coordinates printed below.'}</p><SectionView key={`${JSON.stringify(section.query)}-${JSON.stringify(section.start)}-${JSON.stringify(section.end)}`} result={section} search={result} selected={selectedId} onObservation={onObservation} selection={sectionSelection} onSelectionChange={setSectionSelection}/></>}{section&&!sectionMatches&&<p className="feature-notice">The earlier section belongs to a different query. Build a section for the current result to show it here.</p>}</section>
      <details className="feature-methods"><summary>Methods, source identity and limitations</summary><h4>How this query was calculated</h4><ul>{result.methods.map(m=><li key={m}>{m}</li>)}</ul><h4>What this result can and cannot show</h4><ul>{result.limitations.map(m=><li key={m}>{m}</li>)}</ul>{sectionMatches&&section&&<><h4>Section method</h4><ul>{section.methods.filter(m=>!result.methods.includes(m)).map(m=><li key={m}>{m}</li>)}</ul></>}<p>Method: {result.method_version}<br/>Case: {result.case_id}<br/>Manifest SHA-256: <code>{result.manifest_sha256}</code></p><p>Export contains numerical query results and source identity. Use Save investigation to retain this query and section for verified replay.</p></details>
    </div>}
  </section>;
}
