import { useMemo } from 'react';
import type { FeatureSearch,FeatureRegion } from './contracts';
import { longitudeLabel,latitudeLabel } from '../geography';

type Point=[number,number];
export function FeatureMap({result,region,selected,onSelect,drawing,onPoint,start,end}:{result:FeatureSearch;region?:FeatureRegion;selected:string;onSelect:(id:string)=>void;drawing:boolean;onPoint:(p:Point)=>void;start:Point|null;end:Point|null}){
  const width=640,height=390,left=64,right=22,top=22,bottom=58,plotW=width-left-right,plotH=height-top-bottom,e=result.edges,lon=e.longitude,lat=e.latitude,x=(v:number)=>left+(v-lon[0])/(lon.at(-1)!-lon[0])*plotW,y=(v:number)=>top+(lat.at(-1)!-v)/(lat.at(-1)!-lat[0])*plotH;
  const selectable=new Set(result.regions.map(r=>r.id)),selectedCells=useMemo(()=>new Set(region?.region.id===selected?region.footprint_indices:[]),[region,selected]);
  const paths=useMemo(()=>{const groups=new Map<string,string>();for(let j=0;j<lat.length-1;j++)for(let i=0;i<lon.length-1;i++){const index=j*(lon.length-1)+i,id=result.footprint.region_ids[index];if(!id)continue;const key=selectedCells.has(index)?'selected':id;const path=`M${x(lon[i]).toFixed(2)},${y(lat[j+1]).toFixed(2)}h${(x(lon[i+1])-x(lon[i])).toFixed(2)}v${(y(lat[j])-y(lat[j+1])).toFixed(2)}h-${(x(lon[i+1])-x(lon[i])).toFixed(2)}Z`;groups.set(key,(groups.get(key)??'')+path);}for(const index of selectedCells){if(result.footprint.region_ids[index])continue;const i=index%(lon.length-1),j=Math.floor(index/(lon.length-1));groups.set('selected',(groups.get('selected')??'')+`M${x(lon[i])},${y(lat[j+1])}h${x(lon[i+1])-x(lon[i])}v${y(lat[j])-y(lat[j+1])}h-${x(lon[i+1])-x(lon[i])}Z`);}return [...groups];},[result,selectedCells]);
  function choose(event:React.MouseEvent<SVGSVGElement>){const transform=event.currentTarget.getScreenCTM();if(!transform)return;const point=new DOMPoint(event.clientX,event.clientY).matrixTransform(transform.inverse()),px=point.x,py=point.y;if(px<left||px>width-right||py<top||py>height-bottom)return;const longitude=lon[0]+(px-left)/plotW*(lon.at(-1)!-lon[0]),latitude=lat.at(-1)!-(py-top)/plotH*(lat.at(-1)!-lat[0]);if(drawing){const c=result.coordinates;onPoint([Math.max(c.longitude[0],Math.min(c.longitude.at(-1)!,longitude)),Math.max(c.latitude[0],Math.min(c.latitude.at(-1)!,latitude))]);return;}const ix=lon.findIndex(v=>v>longitude),iy=lat.findIndex(v=>v>latitude),i=Math.max(0,ix<0?lon.length-2:ix-1),j=Math.max(0,iy<0?lat.length-2:iy-1),index=j*(lon.length-1)+i,id=selectedCells.has(index)?selected:result.footprint.region_ids[index];if(id&&selectable.has(id))onSelect(id);}
  return <div className="feature-plan"><div className="feature-chart-scroll feature-map-scroll" tabIndex={0} role="region" aria-label="Structure plan view, scroll horizontally to see the full chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Plan view of qualifying regions and section line" onClick={choose} className={drawing?'drawing':''}><rect x={left} y={top} width={plotW} height={plotH} fill="#102c38" stroke="#496775"/>{paths.map(([id,path])=><path key={id} d={path} fill={id==='selected'||id===selected?'#e9b986':'#76bfae'} fillOpacity={id==='selected'||id===selected?1:.55}/>)}{[0,.25,.5,.75,1].map(t=><g key={t}><line x1={left+t*plotW} x2={left+t*plotW} y1={top} y2={top+plotH} stroke="#527585" opacity=".25"/><line x1={left} x2={left+plotW} y1={top+t*plotH} y2={top+t*plotH} stroke="#527585" opacity=".25"/><text x={left+t*plotW} y={height-bottom+24} textAnchor="middle">{longitudeLabel(lon[0]+t*(lon.at(-1)!-lon[0]),2)}</text><text x={left-8} y={top+t*plotH+4} textAnchor="end">{latitudeLabel(lat.at(-1)!-t*(lat.at(-1)!-lat[0]),2)}</text></g>)}{start&&end&&<line x1={x(start[0])} y1={y(start[1])} x2={x(end[0])} y2={y(end[1])} stroke="#f0f8fa" strokeWidth="3" strokeDasharray="7 4"/>}{([['A',start],['B',end]] as const).map(([name,p])=>p&&<g key={name}><circle cx={x(p[0])} cy={y(p[1])} r="7" fill="#0a1925" stroke="#fff" strokeWidth="2"/><text x={x(p[0])+12} y={y(p[1])-10} fill="#fff">{name}</text></g>)}<text x={left+plotW/2} y={height-10} textAnchor="middle">Longitude · selected model study area</text></svg></div><p className="feature-chart-hint">Scroll the chart sideways when needed. To draw without the map, enter A and B coordinates below.</p><p className="feature-note">Looking down from above. Mint shows the topmost qualifying region in each column. Amber shows all columns touched by the selected region, including deeper cells. Select a result below to inspect regions hidden beneath others.</p></div>;
}
