import { useEffect,useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { appVersion } from '../contracts';
import { number,signed,utc,reasonLabel,type MatchSettings } from '../evidence/contracts';
import { sourceKey,type ImportSources } from '../instruments/imported';
import { postFeature,type FeatureSearch } from './contracts';
import { parseSupport,type Support,type SupportRow } from './support';
import './support.css';
export type SupportTutorialStatus={busy:boolean;error?:string;pairs:number|null;cells:number|null;hours:number|null};

export function ObservationSupport({result,regionId,importSources,active,onCompare,tutorial,onTutorialStatus}:{result:FeatureSearch;regionId:string;importSources:ImportSources;active:boolean;onCompare:(row:SupportRow,settings:MatchSettings)=>void;tutorial?:{action:string;id:number}|null;onTutorialStatus?:(status:SupportTutorialStatus)=>void}){
  const [open,setOpen]=useState(false),[sourceId,setSourceId]=useState(''),[index,setIndex]=useState(0),[reference,setReference]=useState<Support|null>(null);
  const defaults:MatchSettings={variable:result.query.variable==='salinity'?'salinity':'temperature',time_index:result.query.time_index,time_window_hours:6,distance_km:5,max_vertical_gap_m:500,qc:'good_probably_good'};
  const [settings,setSettings]=useState(defaults),[draft,setDraft]=useState(defaults);
  const source=importSources[sourceId],scope=sourceKey(source),unique=Object.entries(importSources).filter(([id,value],i,all)=>all.findIndex(([,s])=>sourceKey(s)===sourceKey(value))===i&&id);
  useEffect(()=>{setReference(null);setIndex(0);},[scope]);
  const supported=['temperature','salinity'].includes(result.query.variable);
  const query=useQuery({queryKey:['evidence-structure-support',appVersion,result.case_id,result.query,regionId,settings,scope],enabled:active&&open&&supported,staleTime:Infinity,gcTime:600000,queryFn:({signal})=>postFeature(`/api/cases/${encodeURIComponent(result.case_id)}/features/support`,{query:result.query,region_id:regionId,settings,...(source?{import_source:source}:{})},v=>parseSupport(v,result,regionId,settings,source),signal)});
  const support=query.data,row=support?.rows[Math.min(index,support.rows.length-1)],dirty=JSON.stringify(settings)!==JSON.stringify(draft);
  useEffect(()=>{if(!tutorial)return;setOpen(true);setSourceId('');setSettings(defaults);setDraft(defaults);setReference(null);},[tutorial?.id]);
  useEffect(()=>{if(tutorial?.action==='sensitivity'&&support&&support.settings.time_window_hours===6&&settings.time_window_hours===6){setReference(support);setSettings({...settings,time_window_hours:0});setDraft({...settings,time_window_hours:0});}},[tutorial?.id,support,settings]);
  useEffect(()=>{if(!tutorial)return;onTutorialStatus?.({busy:query.isFetching||!support||tutorial.action==='sensitivity'&&support.settings.time_window_hours!==0,error:query.error?.message,pairs:support?.eligible_samples??null,cells:support?.supported_cells??null,hours:support?.settings.time_window_hours??null});},[tutorial?.id,tutorial?.action,query.isFetching,query.error,support,onTutorialStatus]);
  function exportSnapshot(){if(!support)return;const url=URL.createObjectURL(new Blob([JSON.stringify({app_version:appVersion,support,reference},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ocean-structure-support.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <section className="structure-support" aria-label="Structure observation support">
    <div className="support-heading"><div><h3>What observations support this region?</h3><p>Locate eligible pairs, inspect their residuals and see the unsampled cells.</p></div><button className="secondary-button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?'Hide observation support':'Show observation support'}</button></div>
    {open&&(!supported?<p role="status">There are no comparable velocity or kinetic-energy observations in this workflow.</p>:<>
      <label>Observation source<select aria-label="Structure support source" value={sourceId} onChange={e=>{setSourceId(e.target.value);setReference(null);setIndex(0);}}><option value="">Bundled observation library</option>{unique.map(([id,s])=><option key={id} value={id}>Imported: {s.filename}</option>)}</select></label>
      <p className="support-note">{source?'Only the selected imported file is included. Its original bytes and mapping are sent to the service again.':'Only the bundled observation library is included.'} Model: {utc(result.model_time)}. Region: {regionId}.</p>
      <details><summary>Support matching rules and sensitivity</summary><form onSubmit={e=>{e.preventDefault();setSettings({...draft});setIndex(0);}} className="support-rules">
        <label>Time window, either side (h)<input aria-label="Support time window" type="number" min="0" max="72" step="0.25" required value={draft.time_window_hours} onChange={e=>setDraft(v=>({...v,time_window_hours:Number(e.target.value)}))}/></label>
        <label>Maximum column distance (km)<input aria-label="Support distance" type="number" min="0" max="50" step="0.1" required value={draft.distance_km} onChange={e=>setDraft(v=>({...v,distance_km:Number(e.target.value)}))}/></label>
        <label>Maximum depth bracket (m)<input aria-label="Support depth gap" type="number" min="1" max="1000" required value={draft.max_vertical_gap_m} onChange={e=>setDraft(v=>({...v,max_vertical_gap_m:Number(e.target.value)}))}/></label>
        <label>Accepted QC<select aria-label="Support QC" value={draft.qc} onChange={e=>setDraft(v=>({...v,qc:e.target.value as MatchSettings['qc']}))}><option value="good_probably_good">Good or probably good</option><option value="good">Good only</option></select></label>
        <button className="secondary-button" disabled={!dirty}>Apply support rules</button>{dirty&&<span role="status">Draft rules are not applied.</span>}
      </form></details>
      <p className="support-note">Applied: +/- {settings.time_window_hours} h, {settings.distance_km} km, depth bracket up to {settings.max_vertical_gap_m} m, {settings.qc==='good'?'good QC':'good or probably-good QC'}. The structure itself keeps its displayed threshold.</p>
      {query.isFetching&&<p role="status">Checking support in the native region...</p>}
      {query.error&&<div role="alert"><p>{query.error.message}</p><button className="secondary-button" onClick={()=>void query.refetch()}>Retry support</button></div>}
      {support&&<><div className="support-counts" aria-label="Structure support counts"><div><strong>{support.eligible_samples}</strong><span>eligible pairs in {support.eligible_profiles} profiles</span></div><div><strong>{support.supported_cells} / {support.region_cells}</strong><span>native cells with eligible pairs</span></div><div><strong>{support.unsupported_cells}</strong><span>cells without eligible pairs in this source</span></div></div>
        {!support.eligible_samples&&<p className="support-empty" role="status">No eligible pairs support this region under these rules. No residual or confidence estimate is invented.</p>}
        <SupportMap support={support} result={result} row={row}/>
        {row&&<div className="support-reading"><label>Eligible source reading<select aria-label="Structure support sample" value={Math.min(index,support.rows.length-1)} onChange={e=>setIndex(Number(e.target.value))}>{support.rows.map((r,i)=><option key={r.profile_id+':'+r.sample_index} value={i}>{r.platform} #{r.sample_index}, {number(r.depth_m,2)} m</option>)}</select></label><dl><div><dt>Observation</dt><dd>{number(row.observed)} {support.units}</dd></div><div><dt>Model at source depth</dt><dd>{number(row.model)} {support.units}</dd></div><div><dt>Model minus observation</dt><dd>{signed(row.residual!)} {support.units}</dd></div><div><dt>Observation time</dt><dd>{utc(row.observation_time)}</dd></div><div><dt>Observation position</dt><dd>{number(row.latitude,5)} N, {number(row.longitude,5)} E</dd></div></dl><button className="secondary-button" onClick={()=>onCompare(row,support.settings)}>Open this pair in comparison</button></div>}
        <div className="support-actions"><button className="secondary-button" disabled={query.isFetching||dirty} onClick={()=>setReference(support)}>Keep support as reference</button><button className="secondary-button" onClick={exportSnapshot}>Export support snapshot</button></div>
        {reference&&<div className="support-reference" aria-label="Support sensitivity"><table><caption>Same structure and source, different matching rules</caption><thead><tr><th>Measure</th><th>Reference</th><th>Current</th><th>Change</th></tr></thead><tbody>{([['Eligible pairs','eligible_samples'],['Cells with pairs','supported_cells'],['Cells without pairs','unsupported_cells']] as const).map(([label,key])=><tr key={key}><th>{label}</th><td>{reference[key]}</td><td>{support[key]}</td><td>{signed(support[key]-reference[key],0)}</td></tr>)}</tbody></table><p>Reference: +/- {reference.settings.time_window_hours} h, {reference.settings.distance_km} km, {reference.settings.max_vertical_gap_m} m depth bracket, {reference.settings.qc.replaceAll('_',' ')}. Changes are sensitivity, not probability.</p><button className="secondary-button" onClick={()=>{setSettings(reference.settings);setDraft(reference.settings);}}>Restore support reference</button><button className="context-button" onClick={()=>setReference(null)}>Clear support reference</button></div>}
        <details><summary>Collection exclusions and method</summary><p>{support.accepted_outside_region} eligible pairs lie outside this region; {support.excluded_samples} source samples failed matching gates across the selected collection. These are not counts of excluded samples inside the region.</p><ul>{Object.entries(support.exclusion_counts).map(([k,v])=><li key={k}>{v}: {reasonLabel(k)}</li>)}</ul><ul>{support.limitations.map(v=><li key={v}>{v}</li>)}</ul><p>Method {support.method_version}. Export includes the selected support result and reference with source hashes. It is a result snapshot, not a replay bundle. Save the structure or comparison separately for checked replay.</p></details>
      </>}
    </>)}
  </section>;
}

function SupportMap({support,result,row}:{support:Support;result:FeatureSearch;row?:SupportRow}){
  const nx=result.shape[2],lon=result.edges.longitude,lat=result.edges.latitude;
  const x=(v:number)=>52+(v-lon[0])/(lon.at(-1)!-lon[0])*520,y=(v:number)=>275-(v-lat[0])/(lat.at(-1)!-lat[0])*250;
  const columns=new Set(support.supported_columns);
  return <figure className="support-map"><figcaption>Plan view of {support.region_id}: mint cells have an eligible pair at some depth; hatched cells have none in this source.</figcaption><svg viewBox="0 0 600 318" role="img" aria-label="Observation support footprint and coverage gaps"><defs><pattern id="support-gap" width="5" height="5" patternUnits="userSpaceOnUse"><rect width="5" height="5" fill="#253946"/><path d="M0 5L5 0" stroke="#4c616b" strokeWidth="1"/></pattern></defs>{support.footprint_indices.map(i=>{const iy=Math.floor(i/nx),ix=i%nx;return <rect key={i} x={x(lon[ix])} y={y(lat[iy+1])} width={Math.max(.3,x(lon[ix+1])-x(lon[ix]))} height={Math.max(.3,y(lat[iy])-y(lat[iy+1]))} fill={columns.has(i)?'#80d6c0':'url(#support-gap)'}/>;})}{support.supported_columns.map(i=><circle key={'marker-'+i} cx={x(result.coordinates.longitude[i%nx])} cy={y(result.coordinates.latitude[Math.floor(i/nx)])} r="5" fill="none" stroke="#80d6c0" strokeWidth="1.5"/>)}{row&&<circle cx={x(result.coordinates.longitude[row.cell[2]])} cy={y(result.coordinates.latitude[row.cell[1]])} r="6" fill="#f1b982" stroke="#091b26" strokeWidth="2"/>}<text x="52" y="306">{number(lon[0],2)} to {number(lon.at(-1)!,2)} degrees east</text><text x="52" y="19">{number(lat[0],2)} to {number(lat.at(-1)!,2)} degrees north</text></svg><p>Rings mark supported model columns and are enlarged for visibility. Amber marks the selected pair. {support.unsupported_columns} of {support.footprint_indices.length} region columns have no eligible pair. Uncoloured space is outside this structure. Depth gaps remain even in mint columns.</p></figure>;
}
