import { useEffect,useRef,useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RotateCcw } from 'lucide-react';
import { format,type FeatureRegion } from './contracts';

export default function RegionMesh({result,active,exaggerationValue,onExaggeration}:{result:FeatureRegion;active:boolean;exaggerationValue?:number;onExaggeration?:(n:number)=>void}){
  const host=useRef<HTMLDivElement>(null),controls=useRef<OrbitControls|null>(null),[failure,setFailure]=useState(''),[localExaggeration,setLocalExaggeration]=useState(1000),[reset,setReset]=useState(0);
  const exaggeration=exaggerationValue??localExaggeration,setExaggeration=(value:number)=>{setLocalExaggeration(value);onExaggeration?.(value);};
  useEffect(()=>{
    if(!host.current||!active||!result.mesh_available)return;
    const element=host.current,disposables:{dispose:()=>void}[]=[];let renderer:THREE.WebGLRenderer|undefined,frame=0,observer:ResizeObserver|undefined;
    try{
      const e=result.edges,axes=[e.depth_m,e.latitude,e.longitude],lon0=(e.longitude[0]+e.longitude.at(-1)!)/2,lat0=(e.latitude[0]+e.latitude.at(-1)!)/2,cos=Math.cos(lat0*Math.PI/180),toPoint=(d:number,lat:number,lon:number)=>new THREE.Vector3((lon-lon0)*111.195*cos,-d*.001*exaggeration,-(lat-lat0)*111.195),positions:number[]=[];
      for(const [axis,plane,u0,u1,v0,v1] of result.faces){const other=[0,1,2].filter(i=>i!==axis),points=[[u0,v0],[u1,v0],[u1,v1],[u0,v1]].map(([u,v])=>{const c=[0,0,0];c[axis]=axes[axis][plane];c[other[0]]=axes[other[0]][u];c[other[1]]=axes[other[1]][v];return toPoint(c[0],c[1],c[2]);});for(const i of [0,1,2,0,2,3])positions.push(points[i].x,points[i].y,points[i].z);}
      const scene=new THREE.Scene();scene.background=new THREE.Color('#0b1c28');
      const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.computeVertexNormals();disposables.push(geometry);
      const material=new THREE.MeshStandardMaterial({color:'#e9b986',roughness:.64,metalness:.06,side:THREE.DoubleSide,flatShading:true});disposables.push(material);scene.add(new THREE.Mesh(geometry,material));
      const q=result.query,min=toPoint(q.depth_max_m,e.latitude.at(-1)!,e.longitude[0]),max=toPoint(q.depth_min_m,e.latitude[0],e.longitude.at(-1)!),box=new THREE.Box3(min,max),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),boxHelper=new THREE.Box3Helper(box,new THREE.Color('#4e7080'));scene.add(boxHelper);disposables.push(boxHelper.geometry,boxHelper.material as THREE.Material);
      const edges=new THREE.EdgesGeometry(geometry,45),lineMaterial=new THREE.LineBasicMaterial({color:'#784f32',transparent:true,opacity:.28});disposables.push(edges,lineMaterial);if(result.faces.length<12000)scene.add(new THREE.LineSegments(edges,lineMaterial));
      scene.add(new THREE.HemisphereLight('#dcf2ed','#2b354a',2.4));const sun=new THREE.DirectionalLight('#fff0d7',3.1);sun.position.set(300,500,300);scene.add(sun);
      const extent=Math.max(size.x,size.y,size.z,1),camera=new THREE.PerspectiveCamera(38,1,.1,extent*30);camera.position.copy(center).add(new THREE.Vector3(extent*1.15,extent*.4,extent*1.2));camera.lookAt(center);
      renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power',alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.setAttribute('aria-label',`3D boundary of region ${result.region.id}; use the adjacent numerical inspector for exact values`);renderer.domElement.setAttribute('role','img');element.append(renderer.domElement);
      const orbit=new OrbitControls(camera,renderer.domElement);controls.current=orbit;orbit.target.copy(center);orbit.enableDamping=false;orbit.minDistance=extent*.4;orbit.maxDistance=extent*7;orbit.saveState();disposables.push(orbit);
      const draw=()=>{if(renderer&&!document.hidden){renderer.render(scene,camera);element.dataset.rendered='region';}};orbit.addEventListener('change',draw);const resize=()=>{const width=element.clientWidth,height=element.clientHeight;renderer!.setSize(width,height,false);camera.aspect=width/Math.max(1,height);camera.updateProjectionMatrix();draw();};observer=new ResizeObserver(resize);observer.observe(element);resize();frame=requestAnimationFrame(draw);setFailure('');
      const lose=(event:Event)=>{event.preventDefault();setFailure('3D graphics became unavailable. The plan view, region statistics and section remain usable.');};renderer.domElement.addEventListener('webglcontextlost',lose);
      return()=>{cancelAnimationFrame(frame);observer?.disconnect();orbit.removeEventListener('change',draw);renderer?.domElement.removeEventListener('webglcontextlost',lose);disposables.forEach(d=>d.dispose());renderer?.dispose();renderer?.domElement.remove();controls.current=null;};
    }catch{setFailure('3D graphics are unavailable on this browser. Use the plan view, numerical region inspector and vertical section.');observer?.disconnect();disposables.forEach(d=>d.dispose());renderer?.dispose();renderer?.domElement.remove();}
  },[result,active,exaggeration,reset]);
  return <div className="feature-mesh"><div className="feature-mesh-toolbar"><span>Selected region boundary</span><button className="secondary-button" onClick={()=>{controls.current?.reset();setReset(n=>n+1);}}><RotateCcw size={14}/>Reset 3D view</button></div><div className="feature-mesh-canvas" ref={host} data-region={result.region.id}>{(failure||!result.mesh_available)&&<p role="status">{failure||'This region has too many boundary faces for the browser mesh. The exact statistics, plan view and section are available.'}</p>}</div><div className="feature-mesh-caption"><span>Initial view: West ↔ East · North at the back · Depth downward</span><label>Depth exaggeration <select aria-label="Structure depth exaggeration" value={exaggeration} onChange={e=>setExaggeration(Number(e.target.value))}>{[1,100,500,1000,2000].map(n=><option value={n} key={n}>{n}×</option>)}</select></label></div><div className="feature-depth-labels"><span>Selected top: {format(result.region.cell_bounds.depth_min_m)} m</span><span>Selected bottom: {format(result.region.cell_bounds.depth_max_m)} m</span></div><p className="feature-note">Drag to rotate, scroll to zoom. Amber surfaces enclose the selected native cells. Warm surface queries can form a thin layer; that thickness comes from the source values. The outline covers {format(result.query.depth_min_m)} to {format(result.query.depth_max_m)} m. Depth is exaggerated for visibility; volume calculations use metres.</p></div>;
}
