import { useMemo,useState } from 'react';
import { rgb } from '../ocean/grid';
import { longitudeLabel,latitudeLabel } from '../geography';
import { format,timestamp,type FeatureSection,type FeatureSearch } from './contracts';

export function SectionView({result,search,selected,onObservation,selection,onSelectionChange}:{result:FeatureSection;search:FeatureSearch;selected:string;onObservation:(id:string)=>void;selection?:{pick:number;showObservations:boolean};onSelectionChange?:(value:{pick:number;showObservations:boolean})=>void}){
  const [localPick,setLocalPick]=useState(0),[localShow,setLocalShow]=useState(true);
  const pick=selection?.pick??localPick,showObservations=selection?.showObservations??localShow;
  const setPick=(value:number)=>{setLocalPick(value);onSelectionChange?.({pick:value,showObservations});},setShowObservations=(value:boolean)=>{setLocalShow(value);onSelectionChange?.({pick,showObservations:value});};
  const nz=result.shape[0],nx=result.shape[1],width=780,height=420,left=62,right=23,top=23,bottom=60,pw=width-left-right,ph=height-top-bottom,maxDistance=result.stations.at(-1)!.distance_km,q=result.query,x=(d:number)=>left+d/maxDistance*pw,y=(d:number)=>top+(d-q.depth_min_m)/(q.depth_max_m-q.depth_min_m)*ph;
  const depthTickDigits=Math.min(12,Math.max(0,Math.ceil(-Math.log10((q.depth_max_m-q.depth_min_m)/4))+1));
  const depthEdges=result.depth_m.map(d=>{const i=search.coordinates.depth_m.indexOf(d);return [search.edges.depth_m[i],search.edges.depth_m[i+1]];}),stationEdges=result.stations.map((s,i)=>[i===0?0:(result.stations[i-1].distance_km+s.distance_km)/2,i===nx-1?maxDistance:(s.distance_km+result.stations[i+1].distance_km)/2]);
  const range=useMemo(()=>{const values=result.values.filter((v):v is number=>v!==null),min=values.length?Math.min(...values):0,max=values.length?Math.max(...values):1;return {min,max:max>min?max:min+1,actualMax:max,count:values.length};},[result]);
  const paint={min:range.min,max:range.max,log:false,palette:'thermal' as const,opacity:1},safePick=Math.min(pick,Math.max(0,result.values.length-1)),zi=Math.floor(safePick/nx),xi=safePick%nx,station=result.stations[xi],value=result.values[safePick];
  function choose(event:React.MouseEvent<SVGSVGElement>){const transform=event.currentTarget.getScreenCTM();if(!transform)return;const point=new DOMPoint(event.clientX,event.clientY).matrixTransform(transform.inverse()),px=point.x,py=point.y;if(px<left||px>width-right||py<top||py>height-bottom||!nz)return;const distance=(px-left)/pw*maxDistance,depth=q.depth_min_m+(py-top)/ph*(q.depth_max_m-q.depth_min_m),i=stationEdges.findIndex(([a,b])=>distance>=a&&distance<=b),j=depthEdges.findIndex(([a,b],index)=>depth>=a&&(depth<b||index===depthEdges.length-1&&depth<=b));if(i>=0&&j>=0)setPick(j*nx+i);}
  const profiles=[...new Map(result.observations.map(o=>[o.profile_id,{id:o.profile_id,platform:o.platform}])).values()];
  return <div className="feature-section-view"><div className="feature-section-title"><h3>Along your line</h3><span>{format(maxDistance,1)} km · {nx} sampling stations · {nz} native depth levels</span></div><p className="feature-line-identity">Displayed line A: {longitudeLabel(result.start[0],6)}, {latitudeLabel(result.start[1],6)}<br/>B: {longitudeLabel(result.end[0],6)}, {latitudeLabel(result.end[1],6)}</p><p className="feature-note">A to B, looking sideways through the water. Colour shows native model values. White cell outlines identify the selected region. Depth spacing is physical, with no vertical interpolation.</p>
    <div className="feature-chart-scroll feature-section-scroll" tabIndex={0} role="region" aria-label="Vertical section, scroll horizontally to see the full chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Vertical section along the drawn line" onClick={choose}><defs><pattern id="feature-missing" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0" stroke="#527181" strokeWidth="1"/></pattern></defs><rect x={left} y={top} width={pw} height={ph} fill="#0b1b28" stroke="#527181"/>{result.values.map((v,i)=>{const j=Math.floor(i/nx),k=i%nx,colour=v===null?null:rgb(v,paint);return <rect key={i} x={x(stationEdges[k][0])} y={y(depthEdges[j][0])} width={Math.max(.1,x(stationEdges[k][1])-x(stationEdges[k][0]))} height={Math.max(.1,y(depthEdges[j][1])-y(depthEdges[j][0]))} fill={colour?`rgb(${colour.map(c=>Math.round(c*255)).join(',')})`:'url(#feature-missing)'} stroke={result.region_ids[i]===selected?'#fff':undefined} strokeOpacity=".24" strokeWidth=".7"/>;})}{[0,.25,.5,.75,1].map(t=><g key={t}><text x={left+t*pw} y={height-bottom+24} textAnchor={t===0?'start':t===1?'end':'middle'}>{format(t*maxDistance,1)}</text><text x={left-10} y={top+t*ph+4} textAnchor="end">{format(q.depth_min_m+t*(q.depth_max_m-q.depth_min_m),depthTickDigits)}</text></g>)}<text x={left+pw/2} y={height-11} textAnchor="middle">Distance from A (km) → B</text><text transform={`translate(15 ${top+ph/2}) rotate(-90)`} textAnchor="middle">Depth (m)</text>{nz>0&&<rect x={x(stationEdges[xi][0])} y={y(depthEdges[zi][0])} width={Math.max(3,x(stationEdges[xi][1])-x(stationEdges[xi][0]))} height={Math.max(3,y(depthEdges[zi][1])-y(depthEdges[zi][0]))} fill="none" stroke="#162f37" strokeWidth="3"/>}{showObservations&&result.observations.map(o=><circle key={`${o.profile_id}-${o.sample_index}`} cx={x(result.stations[o.station_index].distance_km)} cy={y(o.depth_m)} r="3.8" stroke="#102c38" strokeWidth="1.4" fill="#fff"><title>{o.platform}: {format(o.observed)} {q.units} at {format(o.depth_m)} m</title></circle>)}</svg></div><p className="feature-chart-hint">Scroll the chart sideways when needed. Use the station and depth controls below to read exact values.</p>
    <div className="feature-colourbar" aria-label="Section colour scale">{range.count===0?<span>No finite source values. Hatching marks missing samples.</span>:range.min===range.actualMax?<span>Constant source value: {format(range.min,6)} {q.units}. Hatching marks missing samples.</span>:<><span>{format(range.min)} {q.units}</span><span className="feature-scale"/><span>{format(range.actualMax)} {q.units}</span></>}</div>
    {nz>0?<><div className="feature-probe-controls"><label>Section station<select aria-label="Section station" value={xi} onChange={e=>setPick(zi*nx+Number(e.target.value))}>{result.stations.map((s,i)=><option key={i} value={i}>{i+1}: {format(s.distance_km,1)} km from A</option>)}</select></label><label>Section native depth<select aria-label="Section native depth" value={zi} onChange={e=>setPick(Number(e.target.value)*nx+xi)}>{result.depth_m.map((d,i)=><option value={i} key={d}>{format(d)} m</option>)}</select></label></div><div className="feature-probe" aria-label="Section source value"><span>Native model value at {format(result.depth_m[zi])} m</span><strong>{value===null?'Missing in the source':`${format(value,6)} ${q.units}`}</strong><p>Requested station: {longitudeLabel(station.longitude,6)}, {latitudeLabel(station.latitude,6)}.</p><p>Model column: {longitudeLabel(station.model_longitude,6)}, {latitudeLabel(station.model_latitude,6)}. Nearest-column offset: {format(station.offset_km,3)} km.</p><p>{timestamp(result.model_time)} · {result.region_ids[safePick]===null?'Does not qualify for this query':`Belongs to region ${result.region_ids[safePick]}`}</p></div></>:<p className="feature-notice">This depth interval contains no native source levels. Expand the depth range to inspect a section.</p>}
    <div className="feature-linked-observations"><label><input type="checkbox" checked={showObservations} onChange={e=>setShowObservations(e.target.checked)}/>Show eligible observations</label><p>{result.observations.length} eligible samples lie within 5 km of a sampled station. White dots use actual observation depths. Their values need not meet the model threshold.</p>{profiles.map(p=><button className="secondary-button" key={p.id} onClick={()=>onObservation(p.id)}>Inspect {p.platform}</button>)}</div>
  </div>;
}
