import { ApiError, appVersion, type CaseManifest } from '../contracts';

export const heatMethod = 'p12-heat-v1';
export type HeatQuery = { location_id: string; year: 2023 | 2024; event_id: string | null; model_time_index: number; depth_limit_m: 100 | 300 | 700 | 1000 };
export type HeatRecipe = { mode: 'heat'; case_id: string; query: HeatQuery };
export type HeatEvent = { id: string; start: string; end: string; peak_date: string; duration_days: number; exceedance_days: number; bridged_days: number; mean_intensity_c: number; max_intensity_c: number; cumulative_intensity_c_days: number; left_boundary_unknown: boolean; right_boundary_unknown: boolean; complete_boundaries: boolean; starts_before_year: boolean; ends_after_year: boolean; depth_overlap: boolean };
export type HeatDay = { date: string; sst_c: number | null; seasonal_mean_c: number; threshold_c: number; anomaly_c: number | null; exceeds_threshold: boolean | null; event_id: string | null };
export type HeatPoint = { index: number; depth_m: number; in_situ_temperature_c: number | null; practical_salinity: number | null; pressure_dbar: number | null; absolute_salinity_g_kg: number | null; conservative_temperature_c: number | null; potential_temperature_c: number | null; sigma0_kg_m3: number | null; density_kg_m3: number | null; status: string };
export type HeatLayer = { top_depth_m: number; bottom_depth_m: number; midpoint_depth_m: number; temperature_gradient_c_per_m: number | null; n_squared_s2: number | null; pressure_mid_dbar: number | null; n_squared_depth_m: number | null };
export type MixedLayer = { depth_m: number | null; status: 'crossing' | 'no_crossing' | 'missing_support' | 'reference_unavailable'; reference_depth_m: number; reference_value: number | null; threshold: number; supported_to_m: number | null };
export type HeatDiagnostics = { points: HeatPoint[]; layers: HeatLayer[]; mixed_layer: { density: MixedLayer; temperature: MixedLayer }; heat_content: { value_j_m2: number | null; value_gj_m2: number | null; status: string; top_depth_m: number; bottom_depth_m: number; reference_conservative_temperature_c: number; cp0_j_kg_k: number; name: string } };
export type HeatLocation = { id: string; case_id: string; label: string; latitude: number; longitude: number; requested_latitude: number; requested_longitude: number; selection_rule: string };
export type HeatCatalog = { schema_version: '1'; method_version: string; case_id: string; model_manifest_sha256: string; heat_manifest_sha256: string; locations: HeatLocation[]; years: (2023 | 2024)[]; baseline_period: [number, number]; model_times: string[]; depth_limits_m: number[]; default_query: HeatQuery; source: Record<string, unknown>; methods: string[]; caveats: string[] };
export type HeatProfile = HeatDiagnostics & { latitude: number; longitude: number; requested_latitude: number; requested_longitude: number; distance_km: number; model_time: string; time_index: number; depth_limit_m: number; longitude_index: number; latitude_index: number };
export type HeatObservation = { id: string; title: string; platform: string; time: string; latitude: number; longitude: number; distance_km: number; time_offset_hours: number; source_id: string; source_url: string; source_sha256: string; provenance_hold: boolean; note: string };
export type HeatAnalysis = { schema_version: '1'; kind: 'derived'; method_version: string; case_id: string; query: HeatQuery; model_manifest_sha256: string; heat_manifest_sha256: string; location_sha256: string; location: HeatLocation; source: Record<string, unknown>; baseline: { baseline_period: [number, number]; percentile: number; window_days: number; smooth_days: number; feb29: string; missing_policy: string; seasonal_mean_c: number[]; threshold_c: number[]; pool_count: number[] }; series: HeatDay[]; events: HeatEvent[]; selected_event: HeatEvent | null; depth_link: { status: 'available' | 'no_event' | 'outside_model_period' | 'time_outside_event'; message: string; available_time_indices: number[]; model_time: string }; depth_profile: HeatProfile | null; observations: HeatObservation[]; methods: string[]; caveats: string[] };
const obj = (value: unknown): value is Record<string, unknown> => value !== null && typeof value === 'object' && !Array.isArray(value);
const finite = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value);
const integer = (value: unknown): value is number => finite(value) && Number.isInteger(value);
const nullable = (value: unknown): value is number | null => value === null || finite(value);
const date = (value: unknown): value is string => typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) && Number.isFinite(Date.parse(value));
const hash = (value: unknown) => typeof value === 'string' && /^[a-f0-9]{64}$/.test(value);
const strings = (value: unknown): value is string[] => Array.isArray(value) && value.every(item => typeof item === 'string');
export const sameHeatQuery = (a: HeatQuery, b: HeatQuery) => Object.entries(a).every(([key, value]) => value === b[key as keyof HeatQuery]) && Object.keys(a).length === Object.keys(b).length;
export const supportedHeatMethod = (value: unknown) => value === heatMethod;
export function validHeatQuery(value: unknown): value is HeatQuery { return obj(value) && typeof value.location_id === 'string' && /^[a-z0-9-]{1,80}$/.test(value.location_id) && [2023, 2024].includes(Number(value.year)) && integer(value.year) && (value.event_id === null || typeof value.event_id === 'string' && /^mhw-\d{4}-\d{2}-\d{2}-\d{4}-\d{2}-\d{2}$/.test(value.event_id)) && integer(value.model_time_index) && value.model_time_index >= 0 && value.model_time_index <= 6 && finite(value.depth_limit_m) && [100, 300, 700, 1000].includes(value.depth_limit_m); }
export function validHeatRecipe(value: unknown): value is HeatRecipe { return obj(value) && value.mode === 'heat' && typeof value.case_id === 'string' && validHeatQuery(value.query); }
const invalid = () => new ApiError('The heat and depth result could not be verified. Your previous analysis is kept.', undefined, 'response');
function validEvent(value: unknown): value is HeatEvent {
  if (!obj(value) || typeof value.id !== 'string' || !date(value.start) || !date(value.end) || !date(value.peak_date) || value.id !== `mhw-${value.start}-${value.end}` || !integer(value.duration_days) || value.duration_days < 5 || value.duration_days !== (Date.parse(value.end) - Date.parse(value.start)) / 86400000 + 1 || !integer(value.exceedance_days) || !integer(value.bridged_days) || value.exceedance_days + value.bridged_days !== value.duration_days || !finite(value.mean_intensity_c) || !finite(value.max_intensity_c) || !finite(value.cumulative_intensity_c_days) || typeof value.left_boundary_unknown !== 'boolean' || typeof value.right_boundary_unknown !== 'boolean' || value.complete_boundaries !== (!value.left_boundary_unknown && !value.right_boundary_unknown)) return false;
  return value.peak_date >= value.start && value.peak_date <= value.end && value.exceedance_days >= 5 && value.bridged_days >= 0 && ['starts_before_year', 'ends_after_year', 'depth_overlap'].every(key => typeof value[key] === 'boolean');
}
function validMixedLayer(value: unknown): value is MixedLayer { return obj(value) && nullable(value.depth_m) && ['crossing', 'no_crossing', 'missing_support', 'reference_unavailable'].includes(String(value.status)) && (value.status === 'crossing' ? finite(value.depth_m) : value.depth_m === null) && value.reference_depth_m === 10 && nullable(value.reference_value) && finite(value.threshold) && nullable(value.supported_to_m); }
function validDiagnostics(value: unknown): value is HeatDiagnostics {
  if (!obj(value) || !Array.isArray(value.points) || value.points.length < 2 || value.points.length > 100 || !value.points.every((point, index, points) => obj(point) && integer(point.index) && finite(point.depth_m) && (index === 0 ? point.depth_m === 0 : point.depth_m > points[index - 1].depth_m) && ['in_situ_temperature_c', 'practical_salinity', 'pressure_dbar', 'absolute_salinity_g_kg', 'conservative_temperature_c', 'potential_temperature_c', 'sigma0_kg_m3', 'density_kg_m3'].every(key => nullable(point[key])) && typeof point.status === 'string') || !Array.isArray(value.layers) || value.layers.length !== value.points.length - 1 || !obj(value.mixed_layer) || !validMixedLayer(value.mixed_layer.density) || !validMixedLayer(value.mixed_layer.temperature) || !obj(value.heat_content) || !nullable(value.heat_content.value_j_m2) || !nullable(value.heat_content.value_gj_m2) || value.heat_content.top_depth_m !== 0 || !finite(value.heat_content.bottom_depth_m) || value.heat_content.reference_conservative_temperature_c !== 0 || value.heat_content.cp0_j_kg_k !== 3991.86795711963) return false;
  const points = value.points;
  return value.layers.every((layer, index) => obj(layer) && layer.top_depth_m === points[index].depth_m && layer.bottom_depth_m === points[index + 1].depth_m && layer.midpoint_depth_m === (points[index].depth_m + points[index + 1].depth_m) / 2 && ['temperature_gradient_c_per_m', 'n_squared_s2', 'pressure_mid_dbar', 'n_squared_depth_m'].every(key => nullable(layer[key])));
}

function validLocation(value: unknown): value is HeatLocation { return obj(value) && typeof value.id === 'string' && typeof value.case_id === 'string' && typeof value.label === 'string' && ['latitude', 'longitude', 'requested_latitude', 'requested_longitude'].every(key => finite(value[key])) && typeof value.selection_rule === 'string'; }
export function parseHeatCatalog(raw: unknown): HeatCatalog {
  if (!obj(raw) || raw.schema_version !== '1' || raw.method_version !== heatMethod || typeof raw.case_id !== 'string' || !hash(raw.model_manifest_sha256) || !hash(raw.heat_manifest_sha256) || !Array.isArray(raw.locations) || !raw.locations.length || !raw.locations.every(location => validLocation(location) && location.case_id === raw.case_id) || !Array.isArray(raw.years) || raw.years.some(year => year !== 2023 && year !== 2024) || !Array.isArray(raw.baseline_period) || raw.baseline_period[0] !== 1982 || raw.baseline_period[1] !== 2011 || !strings(raw.model_times) || !Array.isArray(raw.depth_limits_m) || !raw.depth_limits_m.every(value => [100, 300, 700, 1000].includes(Number(value))) || !validHeatQuery(raw.default_query) || !obj(raw.source) || !strings(raw.methods) || !strings(raw.caveats)) throw invalid();
  return raw as HeatCatalog;
}
export function parseHeat(raw: unknown): HeatAnalysis {
  if (!obj(raw) || raw.schema_version !== '1' || raw.kind !== 'derived' || raw.method_version !== heatMethod || typeof raw.case_id !== 'string' || !validHeatQuery(raw.query) || !hash(raw.model_manifest_sha256) || !hash(raw.heat_manifest_sha256) || !hash(raw.location_sha256) || !validLocation(raw.location) || raw.location.case_id !== raw.case_id || raw.location.id !== raw.query.location_id || !obj(raw.source) || !obj(raw.baseline) || !Array.isArray(raw.baseline.baseline_period) || raw.baseline.baseline_period[0] !== 1982 || raw.baseline.baseline_period[1] !== 2011 || raw.baseline.percentile !== 90 || raw.baseline.window_days !== 11 || raw.baseline.smooth_days !== 31 || !['seasonal_mean_c', 'threshold_c', 'pool_count'].every(key => { const values = (raw.baseline as Record<string, unknown>)[key]; return Array.isArray(values) && values.length === 366 && values.every(finite); }) || !Array.isArray(raw.events) || !raw.events.every(validEvent) || !Array.isArray(raw.series) || raw.series.length !== (raw.query.year === 2024 ? 366 : 365) || !obj(raw.depth_link) || !['available', 'no_event', 'outside_model_period', 'time_outside_event'].includes(String(raw.depth_link.status)) || typeof raw.depth_link.message !== 'string' || !Array.isArray(raw.depth_link.available_time_indices) || !raw.depth_link.available_time_indices.every(i => integer(i) && i >= 0 && i <= 6) || typeof raw.depth_link.model_time !== 'string' || !Array.isArray(raw.observations) || !strings(raw.methods) || !strings(raw.caveats)) throw invalid();
  const r = raw as HeatAnalysis, ids = new Set(r.events.map(event => event.id));
  if (ids.size !== r.events.length || (r.selected_event === null ? r.query.event_id !== null : !validEvent(r.selected_event) || r.selected_event.id !== r.query.event_id || !ids.has(r.selected_event.id))) throw invalid();
  if (r.selected_event) { const event = r.events.find(event => event.id === r.selected_event!.id)!; if (Object.entries(event).some(([key, value]) => value !== r.selected_event![key as keyof HeatEvent])) throw invalid(); }
  for (let index = 0; index < r.series.length; index++) {
    const sample = r.series[index];
    if (!obj(sample) || !date(sample.date) || Number(sample.date.slice(0, 4)) !== r.query.year || index > 0 && Date.parse(sample.date) - Date.parse(r.series[index - 1].date) !== 86400000 || !nullable(sample.sst_c) || !finite(sample.seasonal_mean_c) || !finite(sample.threshold_c) || !nullable(sample.anomaly_c) || (sample.sst_c === null ? sample.anomaly_c !== null || sample.exceeds_threshold !== null || sample.event_id !== null : sample.anomaly_c !== sample.sst_c - sample.seasonal_mean_c || sample.exceeds_threshold !== (sample.sst_c > sample.threshold_c)) || sample.event_id !== null && !ids.has(sample.event_id)) throw invalid();
  }
  if (r.depth_link.status === 'available') {
    if (!validDiagnostics(r.depth_profile) || !r.depth_profile || r.depth_profile.depth_limit_m !== r.query.depth_limit_m || r.depth_profile.time_index !== r.query.model_time_index || r.depth_profile.model_time !== r.depth_link.model_time || !finite(r.depth_profile.latitude) || !finite(r.depth_profile.longitude) || !finite(r.depth_profile.distance_km) || !r.depth_link.available_time_indices.includes(r.query.model_time_index)) throw invalid();
  } else if (r.depth_profile !== null) throw invalid();
  if (!r.observations.every(observation => obj(observation) && typeof observation.id === 'string' && typeof observation.title === 'string' && typeof observation.platform === 'string' && typeof observation.time === 'string' && finite(observation.distance_km) && finite(observation.time_offset_hours) && typeof observation.provenance_hold === 'boolean' && typeof observation.note === 'string' && hash(observation.source_sha256))) throw invalid();
  return r;
}

export const formatHeatNumber = (value: number | null, digits = 3) => value === null ? 'Not available' : value.toLocaleString('en-US', { maximumFractionDigits: digits });
export const dateLabel = (value: string) => new Date(value.slice(0, 10) + 'T00:00:00Z').toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' });
export const timestampLabel = (value: string) => value.replace('T', ' ').replace(/:00Z$/, ' UTC');

export async function postHeat(path: string, query: HeatQuery, manifest: CaseManifest, signal: AbortSignal): Promise<HeatAnalysis> {
  const controller = new AbortController(), abort = () => controller.abort();
  if (signal.aborted) abort(); signal.addEventListener('abort', abort, { once: true });
  const timer = setTimeout(abort, 45000);
  try {
    const response = await fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(query), signal: controller.signal, cache: 'no-store' });
    if (response.headers.get('X-Ocean-App-Version') !== appVersion) throw new ApiError('The workspace was updated. Reload before calculating another heat and depth analysis.', undefined, 'update');
    const raw: unknown = await response.json();
    if (!response.ok) throw new ApiError(obj(raw) && obj(raw.error) && typeof raw.error.message === 'string' ? raw.error.message : 'The heat and depth calculation could not finish. Your previous result is kept.');
    const result = parseHeat(raw);
    if (result.case_id !== manifest.case.id || !sameHeatQuery(result.query, { ...query, event_id: query.event_id ?? result.query.event_id }) || result.depth_link.model_time !== manifest.coordinates.times[query.model_time_index]) throw invalid();
    if (result.depth_profile) { const profile = result.depth_profile, depths = manifest.coordinates.depth_m.filter(depth => depth <= query.depth_limit_m); if (profile.latitude !== manifest.coordinates.latitude[profile.latitude_index] || profile.longitude !== manifest.coordinates.longitude[profile.longitude_index] || profile.points.length !== depths.length || profile.points.some((point, index) => point.depth_m !== depths[index] || point.index !== index)) throw invalid(); }
    return result;
  } catch (error) {
    if (signal.aborted) throw new DOMException('Calculation cancelled.', 'AbortError');
    if (error instanceof ApiError) throw error;
    throw new ApiError(controller.signal.aborted ? 'The heat and depth calculation timed out. Your previous analysis is kept. Try again.' : 'Could not finish the heat and depth calculation. Your previous analysis is kept.');
  } finally { clearTimeout(timer); signal.removeEventListener('abort', abort); }
}
