import { useEffect, useMemo, useRef, useState } from 'react';
import { useLearningTool, modelSource } from '../learning/bridge';
import { useQuery } from '@tanstack/react-query';
import { ArrowDown, Bookmark, Info, LoaderCircle, RefreshCw, Thermometer } from 'lucide-react';
import { ApiError, appVersion, getApi, type CaseManifest } from '../contracts';
import type { SaveDraft } from '../investigations/contracts';
import { DepthChart, SurfaceChart, type DepthSample } from './HeatCharts';
import { HeatLocations } from './HeatLocations';
import { dateLabel, formatHeatNumber as number, parseHeatCatalog, postHeat, sameHeatQuery, timestampLabel, type HeatAnalysis, type HeatEvent, type HeatProfile, type HeatQuery, type HeatRecipe, type MixedLayer } from './contracts';
import './heat.css';

type Props = { manifest: CaseManifest; active: boolean; restore?: HeatRecipe; restoredAnalysis?: HeatAnalysis; onSave: (draft: SaveDraft) => void; onObservation: (id: string) => void };
const initialQuery = (caseId: string): HeatQuery => ({ location_id: caseId.startsWith('bay') ? 'bay-center' : 'arabian-center', year: 2024, event_id: null, model_time_index: 0, depth_limit_m: 300 });
const dayMs = 86400000;
const eventLabel = (event: HeatEvent) => `${dateLabel(event.start)} to ${dateLabel(event.end)} (${event.duration_days} days)${event.depth_overlap ? ' · Depth context available' : ''}`;

function ErrorNotice({ error, retry }: { error: Error; retry: () => void }) {
  const reload = error instanceof ApiError && error.kind !== 'service';
  return <div className="heat-error" role="alert"><p><strong>{reload ? 'The response could not be verified.' : 'This calculation could not finish.'}</strong><br/>{error.message}</p><button className="secondary-button" onClick={reload ? () => window.location.reload() : retry}><RefreshCw size={15}/>{reload ? 'Reload workspace' : 'Try again'}</button></div>;
}

export function HeatWorkspace({ manifest, active, restore, restoredAnalysis, onSave, onObservation }: Props) {
  const base = `/api/cases/${encodeURIComponent(manifest.case.id)}/heat`;
  const [draft, setDraft] = useState<HeatQuery>(restore?.query ?? initialQuery(manifest.case.id));
  const [result, setResult] = useState<HeatAnalysis | null>(restoredAnalysis ?? null), [busy, setBusy] = useState(false), [error, setError] = useState<Error | null>(null), [notice, setNotice] = useState('');
  const [windowMode, setWindowMode] = useState<'event' | 'year'>('event'), [sampleIndex, setSampleIndex] = useState(0);
  const generation = useRef(0), controllerRef = useRef<AbortController | null>(null), initialized = useRef(Boolean(restoredAnalysis)), pendingQuery = useRef<HeatQuery | null>(null);
  const catalog = useQuery({ queryKey: ['heat-catalog', appVersion, manifest.case.id], queryFn: ({ signal }) => getApi(`${base}/catalog`, raw => { const catalog = parseHeatCatalog(raw); if (catalog.case_id !== manifest.case.id || JSON.stringify(catalog.model_times) !== JSON.stringify(manifest.coordinates.times)) throw new ApiError('The heat catalogue does not match this historical case.', undefined, 'response'); return catalog; }, signal), enabled: active, staleTime: Infinity, gcTime: 600000 });
  useEffect(() => () => { generation.current++; controllerRef.current?.abort(); }, []);
  useEffect(() => { if (active && catalog.data && !initialized.current) { initialized.current = true; const query = restore?.query ?? catalog.data.default_query; setDraft(query); void calculate(query); } }, [active, catalog.data, restore]);

  async function calculate(query: HeatQuery) {
    const controller = new AbortController(), currentGeneration = ++generation.current;
    controllerRef.current?.abort(); controllerRef.current = controller; pendingQuery.current = query;
    setBusy(true); setError(null); setNotice('');
    try {
      const analysis = await postHeat(`${base}/analyse`, query, manifest, controller.signal);
      if (currentGeneration !== generation.current) return;
      if (catalog.data && (analysis.heat_manifest_sha256 !== catalog.data.heat_manifest_sha256 || analysis.model_manifest_sha256 !== catalog.data.model_manifest_sha256)) throw new ApiError('The analysis sources differ from the loaded catalogue. Reload the workspace.', undefined, 'response');
      setResult(analysis); setDraft(analysis.query);
      const preferredDay = analysis.selected_event?.peak_date ?? `${analysis.query.year}-01-01`, found = analysis.series.findIndex(sample => sample.date === preferredDay);
      const firstEventDay = analysis.selected_event ? analysis.series.findIndex(sample => sample.date >= analysis.selected_event!.start && sample.date <= analysis.selected_event!.end) : 0;
      setSampleIndex(found >= 0 ? found : Math.max(0, firstEventDay));
      setNotice('Analysis updated. Surface events and model depth context retain their separate sources.');
    } catch (error) {
      if (currentGeneration !== generation.current) return;
      if (error instanceof Error && error.name === 'AbortError') setNotice('Calculation cancelled. Your completed analysis is kept.');
      else setError(error instanceof Error ? error : new Error('The heat and depth analysis could not finish.'));
    } finally { if (currentGeneration === generation.current) { setBusy(false); controllerRef.current = null; } }
  }
  function update<K extends keyof HeatQuery>(key: K, value: HeatQuery[K]) { setDraft(previous => ({ ...previous, [key]: value, ...(key === 'location_id' || key === 'year' ? { event_id: null } : {}) })); setError(null); }
  function chooseEvent(eventId: string) { if (!result) return; const query = { ...result.query, event_id: eventId }; setDraft(query); void calculate(query); }
  function setModelTime(time: number) { if (!result) return; const query = { ...result.query, model_time_index: time }; setDraft(query); void calculate(query); }
  function setDepthLimit(depth: HeatQuery['depth_limit_m']) { if (!result) return; const query = { ...result.query, depth_limit_m: depth }; setDraft(query); void calculate(query); }
  const changed = Boolean(result && !sameHeatQuery(result.query, draft));
  const event = result?.selected_event, selectedDay = result?.series[sampleIndex];
  const displayedSamples = useMemo(() => {
    if (!result) return [];
    if (windowMode === 'year' || !event) return result.series;
    const start = Date.parse(event.start) - 25 * dayMs, end = Date.parse(event.end) + 25 * dayMs;
    return result.series.filter(sample => Date.parse(sample.date) >= start && Date.parse(sample.date) <= end);
  }, [result, event, windowMode]);
  const displayedIndex = displayedSamples.findIndex(sample => sample.date === selectedDay?.date), caseOverlap = result?.events.find(event => event.depth_overlap);
  useLearningTool('heat',active,{
    tool:'heat',caseId:manifest.case.id,status:error||catalog.error?'error':busy||!result?'loading':'ready',title:'Surface heat and depth evidence',kind:'derived',
    facts:[{label:'Detected events in the selected year',value:result?.events.length??null},{label:'Selected event duration',value:event?.duration_days??null,unit:'days'},{label:'Selected peak intensity above seasonal mean',value:event?.max_intensity_c??null,unit:'°C'},{label:'Depth evidence',value:result?.depth_link.status??null}],parameters:result?{...result.query}:{},sources:[modelSource(manifest.case.id),{label:'Surface source, baseline and method',href:`/api/cases/${encodeURIComponent(manifest.case.id)}/heat/catalog`}],limits:['A warm surface alone does not establish warmth throughout the water column.','Depth evidence is available only where the event and model dates overlap.'],message:error?.message??catalog.error?.message,
  },command=>{if(command.action==='inspect'){if(catalog.error)void catalog.refetch();if(error&&!busy)void calculate(pendingQuery.current??draft);return true;}throw new Error('This heat action is not supported.');});
  const scope = `${manifest.case.time_start.slice(0, 10)} to ${manifest.case.time_end.slice(0, 10)}`;
  return <section className="heat-workspace" aria-label="Heat and Depth Lab">
    <div className="heat-heading"><div><span className="eyebrow">SURFACE EVENTS / WATER COLUMN</span><h2>Heat &amp; Depth Lab</h2><p>Find when the sea surface stayed unusually warm, then inspect the separate evidence below it.</p></div><button className="secondary-button" disabled={!result} onClick={() => result && onSave({ recipe: { mode: 'heat', case_id: manifest.case.id, query: result.query }, expected_model_sha256: result.model_manifest_sha256, expected_heat_manifest_sha256: result.heat_manifest_sha256 })}><Bookmark size={16}/>Save heat investigation</button></div>
    <div className="heat-scope"><Info size={18}/><p><strong>Two sources, two questions.</strong> NOAA OISST analysed SST detects surface events against a 1982–2011 seasonal baseline. HYCOM supplies depth context for {scope}. A surface event does not prove a heatwave at depth.</p></div>
    <div className="heat-content">
      <div className="heat-steps"><span><b>1</b>Choose a source location</span><span><b>2</b>Inspect a surface event</span><span><b>3</b>Check depth evidence</span></div>
      {catalog.isPending && <div className="heat-loading" role="status"><LoaderCircle size={18} className="spin"/>Loading supported locations and method definitions.</div>}
      {catalog.error && <ErrorNotice error={catalog.error} retry={() => void catalog.refetch()}/>}
      {catalog.data && <>
        <form className="heat-settings" onSubmit={event => { event.preventDefault(); void calculate(draft); }}>
          <label>Surface location<select aria-label="Heat surface location" value={draft.location_id} onChange={event => update('location_id', event.target.value)} disabled={busy}>{catalog.data.locations.map(location => <option key={location.id} value={location.id}>{location.label} · {number(location.latitude)}° N, {number(location.longitude)}° E</option>)}</select></label>
          <label>Event year<select aria-label="Heat event year" value={draft.year} onChange={event => update('year', Number(event.target.value) as 2023 | 2024)} disabled={busy}>{catalog.data.years.map(year => <option key={year}>{year}</option>)}</select></label>
          <label>Reference period<input aria-label="Heat baseline period" readOnly value="1982–2011 · 30 years"/></label>
          <button className="primary-button" disabled={busy}><Thermometer size={16}/>{busy ? 'Calculating' : 'Analyse surface record'}</button>
          <p className="heat-note">Fixed OISST cells were selected from the study geometry before looking at event outcomes. Automatic selection prefers the first event with model-date overlap, then the first event in the selected year.</p>
        </form>
        <HeatLocations bounds={manifest.case.bounds} locations={catalog.data.locations.map(location => ({ ...location, label: location.id.endsWith('west') ? 'West' : location.id.endsWith('east') ? 'East' : 'Centre' }))} selected={draft.location_id} onSelect={id => { if (!busy) update('location_id', id); }}/>
      </>}
      {busy && <div className="heat-loading" role="status"><LoaderCircle size={18} className="spin"/><span>Calculating against the fixed seasonal baseline. {result ? 'The previous analysis remains visible with its original labels.' : 'Loading the first checked analysis.'}</span><button className="secondary-button" onClick={() => controllerRef.current?.abort()}>Cancel analysis</button></div>}
      {error && <ErrorNotice error={error} retry={() => void calculate(pendingQuery.current ?? draft)}/>}
      {!busy && notice && <p className="heat-note" role="status">{notice}</p>}
      {changed && result && <div className="heat-applied-note">The controls contain unapplied changes. Charts and saves still describe <strong>{result.location.label}, {result.query.year}</strong>.</div>}
      {result && <div aria-label="Applied heat analysis">
        <section className="heat-surface" aria-label="Surface heatwave evidence">
          <div className="heat-section-heading"><div><h3>{result.location.label}: surface temperature in {result.query.year}</h3><p>NOAA OISST analysed SST · {number(result.location.latitude)}° N, {number(result.location.longitude)}° E · daily values in °C</p></div><span>Historical analysis</span></div>
          <div className="heat-chart-controls"><div><button className="secondary-button" aria-pressed={windowMode === 'event'} disabled={!event} onClick={() => { setWindowMode('event'); if (event) { const target = result.series.findIndex(sample => sample.date >= event.start && sample.date <= event.end); if (target >= 0) setSampleIndex(target); } }}>Around selected event</button><button className="secondary-button" aria-pressed={windowMode === 'year'} onClick={() => setWindowMode('year')}>Whole year</button></div><p>{displayedSamples.length ? `${dateLabel(displayedSamples[0].date)} to ${dateLabel(displayedSamples.at(-1)!.date)}` : 'No dates in this view'}</p></div>
          <SurfaceChart samples={displayedSamples.map(sample => ({ date: sample.date, temperature: sample.sst_c, baseline: sample.seasonal_mean_c, threshold: sample.threshold_c }))} events={result.events} selectedEvent={event?.id ?? null} selectedIndex={displayedIndex} onSample={index => setSampleIndex(result.series.findIndex(sample => sample.date === displayedSamples[index].date))}/>
          <div className="heat-day-inspector"><label>Inspect a daily sample<span aria-label="Selected surface date">{selectedDay ? dateLabel(selectedDay.date) : 'Choose a day'}</span><input aria-label="Heat daily sample" type="range" min={0} max={displayedSamples.length - 1} value={Math.max(0, displayedIndex)} onChange={event => { const sample = displayedSamples[Number(event.target.value)]; setSampleIndex(result.series.findIndex(day => day.date === sample.date)); }}/></label><dl className="heat-day-facts" aria-label="Selected surface sample"><div><dt>Analysed SST</dt><dd>{number(selectedDay?.sst_c ?? null)} °C</dd></div><div><dt>Seasonal mean</dt><dd>{number(selectedDay?.seasonal_mean_c ?? null)} °C</dd></div><div><dt>Seasonal threshold</dt><dd>{number(selectedDay?.threshold_c ?? null)} °C</dd></div></dl><p className="heat-note">{selectedDay?.sst_c === null ? 'The source sample is missing. It is not filled or used to join events.' : selectedDay?.exceeds_threshold ? 'This day exceeds the seasonal threshold. A heatwave requires at least five consecutive qualifying days.' : selectedDay?.event_id ? 'This is a finite cool day inside a joined event, not a threshold exceedance.' : 'This day does not exceed the seasonal threshold.'} Lines connect daily samples; they are not higher-frequency observations.</p></div>
        </section>
        <div className="heat-events-grid">
          <section className="heat-event-picker"><h3>Choose a detected surface event</h3>{result.events.length ? <><label>Event dates<select aria-label="Detected surface event" value={event?.id ?? ''} disabled={busy} onChange={event => chooseEvent(event.target.value)}>{result.events.map(event => <option key={event.id} value={event.id}>{eventLabel(event)}</option>)}</select></label><span className="heat-event-count">{result.events.length} detected {result.events.length === 1 ? 'event intersects' : 'events intersect'} {result.query.year} at this source cell.</span><p className="heat-note">At least five consecutive days above the smoothed 90th-percentile threshold. Qualifying events may join across up to two observed cool days. Missing days are never bridged.</p>{caseOverlap && event?.id !== caseOverlap.id && <button className="secondary-button" disabled={busy} onClick={() => chooseEvent(caseOverlap.id)}><ArrowDown size={15}/>Open event with depth context</button>}</> : <p className="heat-note">No surface event meets the declared method at this location in {result.query.year}. This is a valid result, not a missing chart.</p>}</section>
          <section className="heat-event-card" aria-label="Selected heatwave event"><h3>{event ? 'Selected event' : 'No detected event'}</h3>{event ? <><dl className="heat-facts"><div><dt>Full event dates</dt><dd>{dateLabel(event.start)} to {dateLabel(event.end)}</dd></div><div><dt>Duration</dt><dd>{event.duration_days} days, including {event.bridged_days} joined cool {event.bridged_days === 1 ? 'day' : 'days'}</dd></div><div><dt>Maximum intensity</dt><dd>{number(event.max_intensity_c)} °C above seasonal mean</dd></div><div><dt>Mean intensity</dt><dd>{number(event.mean_intensity_c)} °C above seasonal mean</dd></div><div><dt>Cumulative intensity</dt><dd>{number(event.cumulative_intensity_c_days)} °C·days</dd></div><div><dt>Peak date</dt><dd>{dateLabel(event.peak_date)}</dd></div></dl>{(!event.complete_boundaries || event.starts_before_year || event.ends_after_year) && <p className="heat-note">{!event.complete_boundaries ? 'An event boundary touches missing or unavailable context, so the full duration may be unresolved. ' : ''}{event.starts_before_year || event.ends_after_year ? 'The event crosses the displayed year boundary. Metrics use its complete available context, not only the days drawn here.' : ''}</p>}</> : <p className="heat-note">There is no event duration or intensity to report. Source samples and seasonal curves remain available.</p>}</section>
        </div>
        <section className="heat-depth-section" aria-label="Linked depth evidence"><span className="eyebrow">SEPARATE SUBSURFACE EVIDENCE</span><h3>What was happening below the surface?</h3><p className="heat-note">A linked HYCOM column describes temperature, salt and layer structure during the surface event. There is no subsurface climatology here, so this view does not classify a marine heatwave at depth.</p>
          <div className="heat-depth-controls"><label>Historical model snapshot<select aria-label="Heat model snapshot" value={result.query.model_time_index} disabled={busy} onChange={event => setModelTime(Number(event.target.value))}>{manifest.coordinates.times.map((time, index) => <option key={time} value={index}>{timestampLabel(time)}{result.depth_link.available_time_indices.includes(index) ? ' · within event' : ''}</option>)}</select></label><label>Column and integration limit<select aria-label="Heat depth limit" value={result.query.depth_limit_m} disabled={busy} onChange={event => setDepthLimit(Number(event.target.value) as HeatQuery['depth_limit_m'])}>{[100, 300, 700, 1000].map(depth => <option key={depth} value={depth}>0 to {number(depth, 0)} m</option>)}</select></label><div className="heat-note">All samples use their actual native depths. No layer is filled to make a complete column.</div></div>
          {result.depth_profile ? <DepthEvidence key={`${result.location.id}-${result.query.model_time_index}-${result.query.depth_limit_m}`} profile={result.depth_profile}/> : <div className="heat-depth-unavailable" role="status"><h4>Depth evidence is unavailable for this selection</h4><p>{result.depth_link.message}</p><p>The available model period is {scope}. An unrelated snapshot will not be substituted.</p>{result.depth_link.status === 'time_outside_event' && result.depth_link.available_time_indices.length > 0 && <button className="secondary-button" disabled={busy} onClick={() => setModelTime(result.depth_link.available_time_indices[0])}>Use first snapshot within this event</button>}</div>}
          <section className="heat-observations" aria-label="Heat event observation context"><h4>Observation context for the selected event</h4><p className="heat-note">Profiles listed here fall inside the study bounds and event dates. Their distance and time offset from the selected model column are explicit. Open a profile to inspect its original quality flags. HYCOM assimilates observations, so agreement alone is not independent validation.</p>{result.observations.length ? <div className="heat-observation-list">{result.observations.map(observation => <article className="heat-observation-card" key={observation.id}><strong>{observation.title}</strong><p>{timestampLabel(observation.time)}<br/>{number(observation.distance_km, 2)} km from model column · {number(observation.time_offset_hours, 1)} h from selected snapshot</p><p>{observation.note}</p>{observation.provenance_hold && <p>Provenance hold: excluded from quantitative comparisons.</p>}<button className="secondary-button" onClick={() => onObservation(observation.id)}>Inspect source profile</button></article>)}</div> : <p className="heat-note">{result.depth_link.status === 'available' ? 'No source profile in this case library meets the selected event dates and bounds. No observation is invented or moved to match.' : 'Event-linked observation context is unavailable for this selection. It is loaded with a supported model snapshot inside the selected event.'}</p>}</section>
        </section>
        <details className="heat-table-details"><summary>Inspect daily source values and event membership</summary><div className="heat-table-scroll" role="region" aria-label="Heat daily values, scrollable" tabIndex={0}><table><thead><tr><th>Date (UTC)</th><th>SST (°C)</th><th>Mean (°C)</th><th>Threshold (°C)</th><th>Anomaly (°C)</th><th>Event membership</th></tr></thead><tbody>{result.series.map((sample, index) => <tr key={sample.date} aria-selected={index === sampleIndex}><td><button onClick={() => { setWindowMode('year'); setSampleIndex(index); }}>{sample.date}</button></td><td>{number(sample.sst_c, 5)}</td><td>{number(sample.seasonal_mean_c, 5)}</td><td>{number(sample.threshold_c, 5)}</td><td>{number(sample.anomaly_c, 5)}</td><td>{sample.sst_c === null ? 'Missing source' : sample.event_id ? sample.exceeds_threshold ? 'Threshold exceedance in event' : 'Joined cool day' : sample.exceeds_threshold ? 'Exceeds threshold, outside qualifying event' : 'Outside event'}</td></tr>)}</tbody></table></div><p className="heat-note">Displayed values are rounded for reading. Saved records and CSV exports retain the numerical output.</p></details>
        <details className="heat-methods"><summary>Methods, baseline and source identities</summary><h4>Surface source and preserved metadata</h4><dl className="heat-facts">{([['provider', 'Provider'], ['version', 'Product version'], ['definition', 'Source definition'], ['merge_policy', 'Distributor merge policy'], ['time_policy', 'Daily timestamp policy'], ['lineage_note', 'Historical product lineage'], ['quality_policy', 'Source quality policy'], ['citation', 'Citation']] as const).map(([key, label]) => typeof result.source[key] === 'string' ? <div key={key}><dt>{label}</dt><dd>{result.source[key] as string}</dd></div> : null)}</dl><h4>Definitions used in this analysis</h4><ol>{result.methods.map((method, index) => <li key={index}>{method}</li>)}</ol><h4>Interpretation limits</h4><ul>{result.caveats.map((caveat, index) => <li key={index}>{caveat}</li>)}</ul><p>Location selection: {result.location.selection_rule}</p><p>Baseline: {result.baseline.baseline_period.join(' to ')}. {result.baseline.feb29} {result.baseline.missing_policy}</p><p>Numerical method: <code>{result.method_version}</code><br/>OISST source pack: <code>{result.heat_manifest_sha256}</code><br/>HYCOM source pack: <code>{result.model_manifest_sha256}</code></p><p><a href="https://www.ncei.noaa.gov/products/optimum-interpolation-sst" target="_blank" rel="noreferrer">NOAA OISST product information</a> · <a href="https://www.teos-10.org/pubs/gsw/html/gsw_contents.html" target="_blank" rel="noreferrer">TEOS-10 / GSW definitions</a></p><p>Saving includes the complete daily series, event catalogue, 366-day seasonal curves, depth diagnostics, selected limits and source identities. Export the evidence ZIP for the numerical tables and methods.</p></details>
      </div>}
    </div>
  </section>;
}

const profileVariables = {
  temperature: { label: 'In-situ temperature', units: '°C', description: 'Original HYCOM in-situ temperature at each native depth.' },
  salinity: { label: 'Practical salinity', units: 'PSS-78', description: 'Original practical salinity, distinct from Absolute Salinity.' },
  density: { label: 'Potential-density anomaly', units: 'kg/m³', description: 'GSW sigma0, referenced to 0 dbar. This is not in-situ density minus 1,000.' },
  gradient: { label: 'Temperature gradient', units: '°C/m', description: 'Adjacent temperature difference divided by actual depth spacing. Negative values mean cooling with increasing depth.' },
  stratification: { label: 'N-squared', units: 's⁻²', description: 'GSW buoyancy-frequency squared at the pressure-derived middle depth of each valid layer. Negative values remain visible and indicate static instability in the sampled profile.' },
} as const;
type ProfileVariable = keyof typeof profileVariables;

function DepthEvidence({ profile }: { profile: HeatProfile }) {
  const [variable, setVariable] = useState<ProfileVariable>('temperature'), [selectedDepth, setSelectedDepth] = useState(0);
  const definition = profileVariables[variable];
  const samples: DepthSample[] = variable === 'gradient' ? profile.layers.map(layer => ({ depth: layer.midpoint_depth_m, value: layer.temperature_gradient_c_per_m })) : variable === 'stratification' ? profile.layers.map(layer => ({ depth: layer.n_squared_depth_m ?? layer.midpoint_depth_m, value: layer.n_squared_s2 })) : profile.points.map(point => ({ depth: point.depth_m, value: variable === 'temperature' ? point.in_situ_temperature_c : variable === 'salinity' ? point.practical_salinity : point.sigma0_kg_m3 }));
  const selected = samples.find(sample => sample.depth === selectedDepth) ?? samples[0];
  const densityDepth = profile.mixed_layer.density, temperatureDepth = profile.mixed_layer.temperature, heat = profile.heat_content;
  const references = variable === 'temperature' && temperatureDepth.depth_m !== null ? [{ depth: temperatureDepth.depth_m, label: 'Potential-temperature MLD', colour: '#e8bf8e' }] : variable === 'density' && densityDepth.depth_m !== null ? [{ depth: densityDepth.depth_m, label: 'Density MLD', colour: '#e8bf8e' }] : [];
  return <div aria-label="Heat model depth profile">
    <p className="heat-note">HYCOM native column at {number(profile.latitude, 5)}° N, {number(profile.longitude, 5)}° E, {number(profile.distance_km, 3)} km from the selected OISST centre. Snapshot: {timestampLabel(profile.model_time)}. The two datasets are not the same measurement.</p>
    <div className="heat-depth-body"><section className="heat-depth-plot"><div className="heat-profile-selection"><label>Depth variable<select aria-label="Heat depth variable" value={variable} onChange={event => { setVariable(event.target.value as ProfileVariable); setSelectedDepth(0); }}>{Object.entries(profileVariables).map(([key, variable]) => <option key={key} value={key}>{variable.label}</option>)}</select></label><label>Inspect depth sample<select aria-label="Heat depth sample" value={selected?.depth ?? 0} onChange={event => setSelectedDepth(Number(event.target.value))}>{samples.map(sample => <option value={sample.depth} key={sample.depth}>{number(sample.depth, 2)} m</option>)}</select></label></div><DepthChart samples={samples} name={definition.label} units={definition.units} selectedDepth={selected?.depth ?? null} onDepth={setSelectedDepth} referenceDepths={references}/><div className="heat-profile-readout" aria-label="Selected depth value"><strong>{selected ? `${number(selected.depth, 3)} m: ${number(selected.value, variable === 'stratification' ? 9 : 5)} ${definition.units}` : 'No supported depth samples'}</strong><br/>{definition.description}{variable === 'temperature' && temperatureDepth.depth_m !== null && <><br/>The mixed-layer marker uses potential temperature; the curve shows in-situ temperature.</>}</div></section>
      <div className="heat-diagnostics" aria-label="Derived column diagnostics"><LayerDiagnostic title="Density-threshold mixed layer" layer={densityDepth} criterion="First sigma0 increase of 0.03 kg/m³ from 10 m."/><LayerDiagnostic title="Temperature-threshold mixed layer" layer={temperatureDepth} criterion="First absolute potential-temperature change of 0.2 °C from 10 m."/><article className="heat-diagnostic"><h4>Column potential-enthalpy content</h4><strong>{heat.value_gj_m2 === null ? 'Not available' : `${number(heat.value_gj_m2, 4)} GJ/m²`}</strong><p>Integrated from {number(heat.top_depth_m, 0)} to {number(heat.bottom_depth_m, 0)} m, relative to Conservative Temperature = 0 °C. Uses in-situ density × cp0 × CT and trapezoidal integration over actual native depths.</p><small>{heat.status !== 'available' ? 'Incomplete or unsupported input prevents a full-column integral. ' : ''}This is not heatwave excess, a depth anomaly or cyclone heat potential.</small></article></div>
    </div>
    <details className="heat-table-details"><summary>Inspect native profile and layer diagnostics</summary><div className="heat-table-scroll" role="region" aria-label="Heat native profile values, scrollable" tabIndex={0}><table><thead><tr><th>Depth (m)</th><th>In-situ T (°C)</th><th>Practical salinity</th><th>SA (g/kg)</th><th>CT (°C)</th><th>Sigma0 (kg/m³)</th><th>Support</th></tr></thead><tbody>{profile.points.map(point => <tr key={point.index}><td>{number(point.depth_m)}</td><td>{number(point.in_situ_temperature_c, 5)}</td><td>{number(point.practical_salinity, 5)}</td><td>{number(point.absolute_salinity_g_kg, 5)}</td><td>{number(point.conservative_temperature_c, 5)}</td><td>{number(point.sigma0_kg_m3, 5)}</td><td>{point.status.replaceAll('_', ' ')}</td></tr>)}</tbody></table></div><div className="heat-table-scroll" role="region" aria-label="Heat adjacent layer values, scrollable" tabIndex={0}><table><thead><tr><th>Layer depths (m)</th><th>Gradient midpoint (m)</th><th>Temperature gradient (°C/m)</th><th>N² depth (m)</th><th>N² (s⁻²)</th></tr></thead><tbody>{profile.layers.map(layer => <tr key={layer.top_depth_m}><td>{number(layer.top_depth_m)} to {number(layer.bottom_depth_m)}</td><td>{number(layer.midpoint_depth_m)}</td><td>{number(layer.temperature_gradient_c_per_m, 7)}</td><td>{number(layer.n_squared_depth_m, 5)}</td><td>{number(layer.n_squared_s2, 10)}</td></tr>)}</tbody></table></div></details>
  </div>;
}

function LayerDiagnostic({ title, layer, criterion }: { title: string; layer: MixedLayer; criterion: string }) {
  const value = layer.status === 'crossing' ? `${number(layer.depth_m, 2)} m` : layer.status === 'no_crossing' ? `Deeper than ${number(layer.supported_to_m, 0)} m` : 'Not available';
  return <article className="heat-diagnostic"><h4>{title}</h4><strong>{value}</strong><p>{criterion} A crossing is interpolated only within an adjacent valid bracket.</p><small>{layer.status === 'crossing' ? 'Derived threshold estimate, not a supplied model MLD field.' : layer.status === 'no_crossing' ? 'No threshold crossing in the supported column. This is a lower bound, not an exact layer depth.' : layer.status === 'missing_support' ? `Missing support stops the search after ${number(layer.supported_to_m, 0)} m. No deeper crossing is invented.` : 'The 10 m reference is missing or unsupported.'}</small></article>;
}
