import { useMemo } from 'react';
import { geoMercator,geoPath } from 'd3-geo';
import { feature } from 'topojson-client';
import type { GeometryObject,Topology } from 'topojson-specification';
import landTopology from 'world-atlas/land-110m.json';
import type { CaseManifest } from '../contracts';
import { type Coverage,type CoverageProfile,number,signed,utc,reasonLabel } from './contracts';

const topology=landTopology as unknown as Topology<{land:GeometryObject}>,land=feature(topology,topology.objects.land);
export function CoverageView({coverage,manifest,selected,onSelect}:{coverage:Coverage;manifest:CaseManifest;selected:string;onSelect:(id:string)=>void}){
  const [west,south,east,north]=manifest.case.bounds;
  const projection=useMemo(()=>geoMercator().center([(west+east)/2,(south+north)/2]).scale(1500).translate([325,175]),[west,south,east,north]),path=geoPath(projection);
  const regional=coverage.profiles.filter(p=>p.profile.longitude>=west-5&&p.profile.longitude<=east+5&&p.profile.latitude>=south-5&&p.profile.latitude<=north+5);
  const boundary=path({type:'LineString',coordinates:[[west,south],[east,south],[east,north],[west,north],[west,south]]});
  const accepted=regional.filter(p=>p.matched_count>0),maxDepth=Math.max(10,...accepted.flatMap(p=>p.eligible_depths_m));
  const rowReason=(p:CoverageProfile)=>Object.entries(p.exclusion_counts).sort((a,b)=>b[1]-a[1])[0];
  return <section className="evidence-coverage" aria-label="Evidence coverage"><div className="evidence-section-heading"><div><h3>Where eligible observations exist</h3><p>{coverage.matched_profiles} of {coverage.total_profiles} library profiles contribute {coverage.matched_samples} pairs at this model time. Each pair passes the current matching rules.</p></div></div>
    <div className="evidence-coverage-visuals"><figure className="evidence-map"><figcaption>Profile locations and model domain</figcaption><svg viewBox="0 0 650 350" role="group" aria-label="Comparison coverage map"><defs><clipPath id="evidence-map-clip"><rect width="650" height="350"/></clipPath></defs><g clipPath="url(#evidence-map-clip)"><rect width="650" height="350" fill="#0a202b"/><path d={path(land)??''} fill="#29424c" stroke="#71909a" strokeWidth=".7"/><path d={boundary??''} fill="none" stroke="#a8c7d4" strokeWidth="1.5" strokeDasharray="6 4"/>{regional.map((p,i)=>{const xy=projection([p.profile.longitude,p.profile.latitude]);if(!xy)return null;return <g key={p.profile.id} role="button" tabIndex={0} aria-label={`${p.profile.title}, ${p.matched_count} eligible pairs`} aria-pressed={selected===p.profile.id} transform={`translate(${xy[0]},${xy[1]})`} onClick={()=>onSelect(p.profile.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(p.profile.id);}}} className="evidence-map-point"><title>{p.profile.title}: {p.matched_count} eligible pairs, {utc(p.profile.time)}</title><circle r="16" fill="transparent"/><circle r={selected===p.profile.id?8:6} fill={p.matched_count?'#a1e1cf':'#0b2230'} stroke={selected===p.profile.id?'#fff0c8':'#b4ced8'} strokeWidth="2"/><text x="11" y="4" fill="#d4e8eb" fontSize="11">{i+1}</text></g>;})}</g><text x="12" y="333" fill="#a7c4ce" fontSize="12">Natural Earth coastlines · model bounds dashed</text></svg><p><span className="coverage-accepted-key"/> Eligible <span className="coverage-empty-key"/> No eligible pairs. {coverage.total_profiles-regional.length} profiles outside this regional view remain listed below.</p></figure>
      <figure className="evidence-depth-coverage"><figcaption>Actual eligible sample depths</figcaption><svg viewBox="0 0 390 350" role="img" aria-label={`${coverage.matched_samples} eligible samples by profile and physical depth`}>
        {[0,.25,.5,.75,1].map(f=><g key={f}><line x1="58" x2="373" y1={27+f*255} y2={27+f*255} stroke="#294652"/><text x="50" y={31+f*255} textAnchor="end">{number(f*maxDepth,0)}</text></g>)}
        {accepted.map((p,i)=>{const x=80+i*260/Math.max(1,accepted.length-1);return <g key={p.profile.id}><title>{p.profile.title}, {p.matched_count} accepted depths</title>{p.eligible_depths_m.map((d,j)=><line key={j} x1={x-7} x2={x+7} y1={27+d/maxDepth*255} y2={27+d/maxDepth*255} stroke={p.profile.id===selected?'#ffe3ae':'#a1e1cf'} strokeWidth="1.3"/>)}<text x={x} y="304" textAnchor="middle">{regional.findIndex(r=>r.profile.id===p.profile.id)+1}</text></g>;})}
        {!accepted.length&&<text x="214" y="157" textAnchor="middle">No eligible depths at this time.</text>}<text x="216" y="331" textAnchor="middle">Profile number on the map</text><text transform="translate(14,158) rotate(-90)" textAnchor="middle">Depth (m)</text>
      </svg><p>Each stroke is an accepted sample depth. Overlapping strokes may coincide. Empty water is unsampled, not a confidence estimate.</p></figure></div>
    <div className="evidence-table-scroll"><table className="evidence-coverage-table"><caption>Checked source library under the current filters</caption><thead><tr><th scope="col">Profile</th><th scope="col">Eligible pairs</th><th scope="col">Sample time minus model time</th><th scope="col">Distance to column</th><th scope="col">Main exclusion</th></tr></thead><tbody>{coverage.profiles.map(p=>{const reason=rowReason(p);return <tr key={p.profile.id} className={selected===p.profile.id?'is-selected':''}><th scope="row"><button aria-pressed={selected===p.profile.id} onClick={()=>onSelect(p.profile.id)}>{p.profile.instrument.toUpperCase()} {p.profile.platform}</button><small>{utc(p.profile.time)}</small></th><td>{p.matched_count} / {p.total_samples}</td><td>{signed(p.time_offset_hours_min)}{p.time_offset_hours_max!==p.time_offset_hours_min?` to ${signed(p.time_offset_hours_max)}`:''} h<small>{p.matched_count?'Eligible samples':'All source samples; none eligible'}</small></td><td>{p.distance_km_min===null?'No eligible pair':`${number(p.distance_km_min,2)}${p.distance_km_max!==p.distance_km_min?` to ${number(p.distance_km_max,2)}`:''} km`}</td><td>{reason?`${reasonLabel(reason[0])} (${reason[1]})`:'None'}</td></tr>;})}</tbody></table></div>
  </section>;
}
