import { selectedOffset,type SharedSample } from '../workspace/selection';
import { importedEvidence,sourceKey,type ImportSources } from '../instruments/imported';
import type { InstrumentProfile } from '../instruments/contracts';
import type { ComparisonRecipe,SaveDraft } from '../investigations/contracts';
import { useLearningTool, modelSource } from '../learning/bridge';
import { useEffect,useMemo,useState,useRef } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight,ChevronLeft,ChevronRight,RefreshCw,Search,SlidersHorizontal } from 'lucide-react';
import { appVersion,getApi,type CaseManifest } from '../contracts';
import { safeSource,type InstrumentCatalog } from '../instruments/contracts';
import { ComparisonCharts } from './ComparisonCharts';
import { CoverageView } from './CoverageView';
import { type Comparison,type CoverageProfile,type MatchRow,type MatchSettings,type MatchVariable,number,parseComparison,parseCoverage,querySettings,reasonLabel,signed,utc,verifyRequest } from './contracts';
import './evidence.css';
import { inModel } from '../instruments/InstrumentWorkspace';

type Filters=Pick<MatchSettings,'time_window_hours'|'distance_km'|'max_vertical_gap_m'|'qc'>;
type Props={onDraft?:(draft:SaveDraft|null)=>void;onReady?:(ready:boolean)=>void;selection?:SharedSample;onSampleSelection?:(comparison:Comparison,row:MatchRow)=>void;imports:InstrumentProfile[];importSources:ImportSources;manifest:CaseManifest;catalog?:InstrumentCatalog;selected:string;onSelect:(id:string)=>void;timeIndex:number;onTime:(i:number)=>void;variable:MatchVariable;onVariable:(v:MatchVariable)=>void;active:boolean;onModel:(row:MatchRow)=>void;onObservation:(id:string)=>void;restore?:ComparisonRecipe;referenceResult?:Comparison;onSave?:(draft:SaveDraft)=>void};
const defaults:Filters={time_window_hours:6,distance_km:5,max_vertical_gap_m:500,qc:'good_probably_good'};
const filterDescription=(s:MatchSettings)=>`±${number(s.time_window_hours)} h, ${number(s.distance_km)} km, depth gaps up to ${number(s.max_vertical_gap_m)} m, ${s.qc==='good'?'good QC only':'good or probably-good QC'}`;
const title=(v:MatchVariable)=>v==='temperature'?'In-situ temperature':'Practical salinity';
const closestTime=(p:CoverageProfile)=>p.minimum_abs_time_offset_hours??Infinity;
const kind={argo:'Argo',bgc:'BGC Argo',ctd:'Ship CTD',glider:'Glider'};
const position=(lat:number,lon:number)=>`${number(Math.abs(lat),6)}° ${lat<0?'S':'N'}, ${number(Math.abs(lon),6)}° ${lon<0?'W':'E'}`;

export function EvidenceWorkspace({imports,importSources,manifest,catalog,selected,onSelect,timeIndex,onTime,variable,onVariable,active,onModel,onObservation,restore,referenceResult,onSave,selection,onSampleSelection,onReady,onDraft}:Props){
  const initialFilters=restore?{time_window_hours:restore.settings.time_window_hours,distance_km:restore.settings.distance_km,max_vertical_gap_m:restore.settings.max_vertical_gap_m,qc:restore.settings.qc}:defaults;
  const [filters,setFilters]=useState<Filters>(initialFilters),[draft,setDraft]=useState<Filters>(initialFilters),[advanced,setAdvanced]=useState(false),[view,setView]=useState<'comparison'|'coverage'>(restore?.view??'comparison'),[rank,setRank]=useState<'nearest'|'residual'>(restore?.rank??'nearest'),[notice,setNotice]=useState(''),[index,setIndex]=useState(restore?.sample_index??0),[baseline,setBaseline]=useState<Comparison|null>(referenceResult??null),[suggestion,setSuggestion]=useState<CoverageProfile|null>(null);
  const settings=useMemo<MatchSettings>(()=>({...filters,variable,time_index:timeIndex}),[filters,variable,timeIndex]),params=querySettings(settings),caseId=manifest.case.id;
  const importSource=importSources[selected],scope=sourceKey(importSource);
  const priorScope=useRef(scope);
  useEffect(()=>{if(priorScope.current!==scope){setBaseline(null);setView('comparison');setNotice(baseline?'Comparison source changed. The previous reference was cleared.':'');priorScope.current=scope;}},[scope,baseline]);
  const coverageQuery=useQuery({queryKey:['evidence-coverage',appVersion,caseId,params,scope],queryFn:({signal})=>{
    const parse=(v:unknown)=>verifyRequest(parseCoverage(v),settings,caseId,undefined,manifest.coordinates.times[timeIndex]);
    return importSource?importedEvidence(caseId,'coverage',{import_source:importSource,settings},parse,signal):getApi(`/api/cases/${encodeURIComponent(caseId)}/evidence/coverage?${params}`,parse,signal);
  },enabled:active,staleTime:Infinity,gcTime:600000});
  const coverage=coverageQuery.data,currentId=importSource?selected:catalog?.profiles.some(p=>p.id===selected)?selected:coverage?.profiles.find(p=>p.profile.id===selected)?.profile.id??coverage?.profiles.find(p=>inModel(manifest,p.profile))?.profile.id??coverage?.profiles[0]?.profile.id;
  const query=useQuery({queryKey:['evidence-comparison',appVersion,caseId,currentId,params,scope],queryFn:({signal})=>{
    const parse=(v:unknown)=>verifyRequest(parseComparison(v),settings,caseId,currentId,manifest.coordinates.times[timeIndex]);
    return importSource?importedEvidence(caseId,'comparison',{import_source:importSource,profile_id:currentId,settings},parse,signal):getApi(`/api/cases/${encodeURIComponent(caseId)}/evidence/profiles/${encodeURIComponent(currentId!)}?${params}`,parse,signal);
  },enabled:active&&Boolean(currentId),staleTime:Infinity,gcTime:600000});
  const comparison=query.data;
  const effectiveIndex=selectedOffset(selection,comparison?.profile.id,comparison?.rows.map(r=>r.sample_index)??[],!restore&&selection?.profileId!==comparison?.profile.id?Math.max(0,comparison?.rows.findIndex(r=>r.accepted)??0):index);
  const row=comparison?.rows[effectiveIndex];
  function chooseSample(i:number){setIndex(i);if(comparison)onSampleSelection?.(comparison,comparison.rows[i]);}
  useEffect(()=>{if(active&&comparison&&row)onSampleSelection?.(comparison,row);},[active,comparison,effectiveIndex]);
  const busy=coverageQuery.isFetching||query.isFetching;
  useEffect(()=>setSuggestion(null),[params,caseId,rank]);
  const initialComparison=useRef(restore?JSON.stringify({id:restore.profile_id,settings:restore.settings}):null);
  useEffect(()=>{if(comparison){const identity=JSON.stringify({id:comparison.profile.id,settings:comparison.settings});if(initialComparison.current===identity)return;initialComparison.current=null;setIndex(Math.max(0,comparison.rows.findIndex(r=>r.accepted)));}},[comparison]);
  useEffect(()=>{onReady?.(Boolean(active&&comparison&&!busy&&JSON.stringify(filters)===JSON.stringify(draft)));},[active,comparison,busy,filters,draft]);
  const pendingFilters=JSON.stringify(filters)!==JSON.stringify(draft);
  const saveDraft:SaveDraft|null=comparison&&!busy&&!pendingFilters?{...(importSource?{import_source:importSource}:{}),expected_model_sha256:comparison.manifest_sha256,expected_profile_sha256:comparison.profile.source_sha256,expected_observation_library_sha256:comparison.observation_library_sha256,recipe:{mode:"comparison",case_id:caseId,profile_id:comparison.profile.id,settings:comparison.settings,sample_index:effectiveIndex,view,rank,baseline:baseline?{profile_id:baseline.profile.id,settings:baseline.settings}:null}}:null;
  const draftIdentity=JSON.stringify(saveDraft);
  useEffect(()=>{onDraft?.(active?saveDraft:null);},[active,draftIdentity]);
  const ranked=useMemo(()=>{const pairs=(coverage?.profiles??[]).filter(p=>p.matched_count>0);return pairs.sort(rank==='residual'?(a,b)=>(b.metrics.maximum_abs_residual??0)-(a.metrics.maximum_abs_residual??0)||a.profile.id.localeCompare(b.profile.id):(a,b)=>closestTime(a)-closestTime(b)||(a.distance_km_min??Infinity)-(b.distance_km_min??Infinity)||a.profile.id.localeCompare(b.profile.id));},[coverage,rank]);
  function discover(){
    if(!coverage)return;
    if(ranked[0]){onSelect(ranked[0].profile.id);setView('comparison');setNotice(`${kind[ranked[0].profile.instrument]} ${ranked[0].profile.platform} has ${ranked[0].matched_count} eligible pairs at the selected model time. ${rank==='residual'?'It has the largest absolute residual among currently eligible profiles.':'It ranks first by absolute time separation, then distance.'}`);return;}
    if(rank==='residual'){setNotice('No eligible residuals exist at this model time. Choose nearest eligible match to find another bundled snapshot.');return;}
    const suggestions=coverage.profiles.filter(p=>p.suggested_time_index!==null&&p.suggested_matched_count>0).sort((a,b)=>(a.suggested_time_offset_hours??Infinity)-(b.suggested_time_offset_hours??Infinity)||(a.suggested_distance_km??Infinity)-(b.suggested_distance_km??Infinity)||a.profile.id.localeCompare(b.profile.id));
    const best=suggestions[0];if(!best){setNotice('No eligible comparison was found in the bundled snapshots under these rules. Inspect exclusions or change the matching rules explicitly.');return;}
    setSuggestion(best);setNotice(`Found ${best.suggested_matched_count} eligible pairs for ${kind[best.profile.instrument]} ${best.profile.platform} at ${utc(manifest.coordinates.times[best.suggested_time_index!])}. Use the suggested snapshot below to open this comparison. Your current time has not changed.`);
  }
  function apply(){setFilters({...draft});setNotice('Matching rules applied. The profile, residuals and coverage use the same eligibility gates.');}
  function restoreReference(){if(!baseline)return;const s=baseline.settings,next={time_window_hours:s.time_window_hours,distance_km:s.distance_km,max_vertical_gap_m:s.max_vertical_gap_m,qc:s.qc};setFilters(next);setDraft(next);onVariable(s.variable);onTime(s.time_index);onSelect(baseline.profile.id);setNotice('Restored the reference comparison settings.');}
  const alternatives=[...(catalog?.profiles??[]),...imports].map(profile=>({profile}));
  useLearningTool('comparison',active,{
    tool:'comparison',caseId,status:query.error||coverageQuery.error?'error':busy||!comparison?'loading':'ready',title:'Model and measurement',kind:'comparison',
    facts:[{label:'Eligible pairs',value:comparison?.matched_count??null},{label:'Observation',value:row?.accepted?row.observed:null,unit:comparison?.units},{label:'Model at observation depth',value:row?.accepted?row.model:null,unit:comparison?.units},{label:'Model minus observation',value:row?.accepted?row.residual:null,unit:comparison?.units},{label:'Model time (UTC)',value:comparison?.model_time??null},{label:'Observation time (UTC)',value:comparison?.profile.time??null}],parameters:{...settings,profile_id:currentId??null},
    sources:[modelSource(caseId),...(currentId&&!importSource?[{label:'Eligible pairs and exclusion reasons',href:`/api/cases/${encodeURIComponent(caseId)}/evidence/profiles/${encodeURIComponent(currentId)}?${params}`}]:[])],
    limits:['Only physically compatible samples passing time, distance, depth and quality rules count.','Model agreement is not independent validation: observations may have been assimilated.'],message:query.error?.message??coverageQuery.error?.message,
  },async command=>{
    if(coverageQuery.error){const retried=await coverageQuery.refetch();if(retried.error)throw retried.error;return false;}
    if(query.error)void query.refetch();
    if(command.action==='compare'){
      if(!coverage)return false;
      const best=ranked[0];
      if(best){onSelect(best.profile.id);setView('comparison');return true;}
      const suggestion=coverage.profiles.find(p=>p.suggested_time_index!==null&&p.suggested_matched_count>0);
      if(suggestion){onSelect(suggestion.profile.id);onTime(suggestion.suggested_time_index!);setView('comparison');return true;}
      throw new Error('No eligible comparison is available under these matching rules.');
    }
    if(command.action==='inspect')return true;
    throw new Error('This comparison action is not supported.');
  });
  return <section className="evidence-workspace" aria-label="Model and observation comparison">
    <header className="evidence-heading"><span className="eyebrow">EVIDENCE / HISTORICAL CASE</span><h2>Compare measurements with the model</h2><p>Choose a profile and model time. Only samples that meet the physical, quality, time and distance rules form a comparison.</p><a className="evidence-results-jump" href="#comparison-results">Go to results</a></header>
    {onSave&&<div className="save-analysis"><button className="secondary-button" disabled={!comparison||busy||pendingFilters} onClick={()=>saveDraft&&onSave(saveDraft)}>Save investigation</button></div>}
    {importSource&&<p className="evidence-notice" role="status"><strong>Imported file: {importSource.filename}.</strong> Coverage and discovery use this file only. Original bytes, mapping and QC are rechecked.</p>}
    <div className="evidence-controls"><label>Compared variable<select aria-label="Compared variable" value={variable} onChange={e=>{onVariable(e.target.value as MatchVariable);setNotice('');}}><option value="temperature">In-situ temperature</option><option value="salinity">Practical salinity</option></select></label><label>Model snapshot (UTC)<select aria-label="Comparison model snapshot" value={timeIndex} onChange={e=>{onTime(Number(e.target.value));setNotice('');}}>{manifest.coordinates.times.map((t,i)=><option value={i} key={t}>{utc(t)}</option>)}</select></label><label>Observation profile<select aria-label="Comparison profile" disabled={!alternatives.length} value={currentId??''} onChange={e=>{onSelect(e.target.value);setNotice('');}}>{!alternatives.length&&<option value="">Loading checked profiles...</option>}{alternatives.map(p=><option value={p.profile.id} key={p.profile.id}>{p.profile.id.startsWith('import-')?'Imported: ':''}{kind[p.profile.instrument]} {p.profile.platform} · {utc(p.profile.time)}</option>)}</select></label></div>
    <div className="evidence-rule-summary"><p><strong>Current rules:</strong> {filterDescription(settings)}.</p><button className="secondary-button" aria-expanded={advanced} onClick={()=>setAdvanced(v=>!v)}><SlidersHorizontal size={15}/>Matching rules</button><a href="#matching-sensitivity" className="sensitivity-jump">Compare rule changes</a></div>
    {advanced&&<form className="evidence-advanced" aria-label="Matching rules" onSubmit={e=>{e.preventDefault();apply();}}><div className="evidence-filter-grid"><label>Time window, either side (hours)<input aria-label="Matching time window" type="number" min="0" max="72" step="0.25" required value={draft.time_window_hours} onChange={e=>setDraft(s=>({...s,time_window_hours:Number(e.target.value)}))}/></label><label>Maximum column distance (km)<input aria-label="Matching distance" type="number" min="0" max="50" step="0.1" required value={draft.distance_km} onChange={e=>setDraft(s=>({...s,distance_km:Number(e.target.value)}))}/></label><label>Largest native depth gap (m)<input aria-label="Matching depth gap" type="number" min="1" max="1000" step="1" required value={draft.max_vertical_gap_m} onChange={e=>setDraft(s=>({...s,max_vertical_gap_m:Number(e.target.value)}))}/></label><label>Accepted quality categories<select aria-label="Comparison QC policy" value={draft.qc} onChange={e=>setDraft(s=>({...s,qc:e.target.value as Filters['qc']}))}><option value="good_probably_good">Good or probably good</option><option value="good">Good only</option></select></label></div><p>The nearest native grid column is used. Time is a selected snapshot, with no temporal interpolation. Linear interpolation is allowed only between valid adjacent depths inside the gap limit. Quality categories follow each source's own scheme.</p><div className="evidence-actions"><button className="secondary-button" type="submit" disabled={!pendingFilters}>Apply matching rules</button><button className="secondary-button" type="button" onClick={()=>setDraft({...defaults})}>Reset draft to defaults</button>{pendingFilters&&<span role="status">Draft changes are not applied yet.</span>}</div></form>}
    <div className="evidence-discovery"><div><label>Discovery order<select aria-label="Comparison discovery order" value={rank} onChange={e=>setRank(e.target.value as 'nearest'|'residual')}><option value="nearest">Nearest eligible match</option><option value="residual">Largest absolute residual</option></select></label><p>{rank==='nearest'?'Rank by absolute time separation, then distance. If this snapshot has no pairs, search other bundled snapshots.':'Rank by the largest absolute model-minus-observation residual among accepted pairs at this snapshot.'}</p></div><button className="secondary-button evidence-find" disabled={!coverage||coverageQuery.isFetching} onClick={discover}><Search size={16}/>Find a useful comparison</button></div>
    {notice&&<p className="evidence-notice" role="status">{notice}</p>}
    {suggestion&&<div className="evidence-snapshot-suggestion"><button className="secondary-button" onClick={()=>{onSelect(suggestion.profile.id);onTime(suggestion.suggested_time_index!);setView('comparison');setNotice(`Opened the suggested ${utc(manifest.coordinates.times[suggestion.suggested_time_index!])} model snapshot. Matching limits and QC stay as shown.`);setSuggestion(null);}}>Use {utc(manifest.coordinates.times[suggestion.suggested_time_index!])} snapshot <ArrowRight size={15}/></button><p>This changes the shared model time. The observation retains its source timestamp.</p></div>}
    <div id="comparison-results" className="evidence-tabs" role="group" aria-label="Comparison view"><button aria-pressed={view==='comparison'} onClick={()=>setView('comparison')}>Profile comparison</button><button aria-pressed={view==='coverage'} onClick={()=>setView('coverage')}>Evidence coverage</button></div>
    {busy&&<p className="evidence-loading" role="status">Checking the selected samples and matching rules...</p>}
    {view==='coverage'&&(coverage?<CoverageView coverage={coverage} manifest={manifest} selected={currentId??''} onSelect={id=>{onSelect(id);setView('comparison');}}/>:coverageQuery.isError?<ErrorPanel error={coverageQuery.error} onRetry={()=>void coverageQuery.refetch()}/>:null)}
    {view==='comparison'&&(comparison?<>
      <div className="evidence-result-heading"><div><h3>{kind[comparison.profile.instrument]} {comparison.profile.platform}</h3><p><strong>Observation:</strong> {utc(comparison.profile.time)}{comparison.profile.time_end!==comparison.profile.time?` to ${utc(comparison.profile.time_end)}`:''}<br/><strong>Model:</strong> {utc(comparison.model_time)}</p></div><button className="secondary-button" onClick={()=>{if(row)onSampleSelection?.(comparison,row);onObservation(comparison.profile.id);}}>Inspect source readings <ArrowRight size={15}/></button></div>
      <div className="evidence-result-count" aria-label="Eligible comparison count"><strong>{comparison.matched_count} / {comparison.total_samples}</strong><span>samples form eligible pairs</span><span>{comparison.excluded_count} excluded</span></div>
      {!comparison.matched_count&&<div className="evidence-empty" role="status"><h3>No eligible pairs for this selection</h3><p>No residual or agreement score can be calculated. Use discovery to find a supported comparison, or inspect the exclusion reasons below.</p></div>}
      <p className="evidence-legend"><span className="evidence-line observation"/> Observed {title(variable).toLowerCase()} <span className="evidence-line model"/> Model at observation depth</p>
      <ComparisonCharts comparison={comparison} index={effectiveIndex} onSample={chooseSample}/>
      {row&&<><div className="evidence-sample-controls"><button className="icon-button" aria-label="Previous comparison sample" disabled={effectiveIndex===0} onClick={()=>chooseSample(Math.max(0,effectiveIndex-1))}><ChevronLeft size={17}/></button><label>Source sample<select aria-label="Comparison sample" value={effectiveIndex} onChange={e=>chooseSample(Number(e.target.value))}>{comparison.rows.map((r,i)=><option key={r.sample_index} value={i}>#{r.sample_index} · {number(r.depth_m,1)} m · {r.accepted?'eligible':reasonLabel(r.reason)}</option>)}</select></label><button className="icon-button" aria-label="Next comparison sample" disabled={effectiveIndex>=comparison.rows.length-1} onClick={()=>chooseSample(Math.min(comparison.rows.length-1,effectiveIndex+1))}><ChevronRight size={17}/></button></div>
      <section className="evidence-selected" aria-label="Selected comparison sample"><div className="evidence-selected-heading"><h3>Source sample #{row.sample_index} at {number(row.depth_m,2)} m</h3><span className={row.accepted?'evidence-eligible':'evidence-excluded'}>{row.accepted?'Eligible pair':reasonLabel(row.reason)}</span></div><div className="evidence-sample-values"><div><span>Observed</span><strong>{number(row.observed)} <small>{comparison.units}</small></strong></div><div><span>Model at this depth</span><strong>{row.accepted?number(row.model):'Not paired'}{row.accepted&&<small> {comparison.units}</small>}</strong></div><div><span>Model minus observation</span><strong>{row.accepted?signed(row.residual!,3):'Not calculated'}{row.accepted&&<small> {comparison.units}</small>}</strong></div></div>
      <dl className="evidence-facts"><div><dt>Observation time</dt><dd>{utc(row.observation_time)}</dd></div><div><dt>Time offset</dt><dd>{signed(row.time_offset_hours)} h, observation minus model</dd></div><div><dt>Observation position</dt><dd>{position(row.latitude,row.longitude)}</dd></div><div><dt>Nearest model column</dt><dd>{row.model_latitude===null||row.model_longitude===null?'Not evaluated':position(row.model_latitude,row.model_longitude)}</dd></div><div><dt>Column separation</dt><dd>{row.distance_km===null?'Not evaluated':`${number(row.distance_km,3)} km`}</dd></div><div><dt>Selected variable QC / mode</dt><dd>{comparison.profile.parameters[variable]?.qc_scheme.toUpperCase()??'Unknown scheme'} {row.qc||'Not supplied'} / {row.mode||'Not supplied'}</dd></div></dl>
      <details><summary>Native depth bracket and method</summary><p>Values are read from the analytical grid. The model value is linearly interpolated in physical depth only; no model values are filled through masks or beyond the available column.</p><dl className="evidence-facts"><div><dt>Shallower / deeper native depth</dt><dd>{row.lower_depth_m===null?'Not evaluated':`${number(row.lower_depth_m)} m / ${number(row.upper_depth_m)} m`}</dd></div><div><dt>Values at those depths</dt><dd>{row.model_lower_value===null?'Not evaluated':`${number(row.model_lower_value)} / ${number(row.model_upper_value)} ${comparison.units}`}</dd></div><div><dt>Deeper depth weight</dt><dd>{number(row.upper_weight,6)}</dd></div></dl></details>
      <button className="secondary-button" disabled={!row.accepted} onClick={()=>onModel(row)}>View matched model column <ArrowRight size={15}/></button><p className="evidence-note">Highlights the matched column in the model panel. The 3D depth slice snaps to its nearest native level; the comparison above uses the stated depth interpolation.</p></section></>}
      <section className="evidence-metrics" aria-label="Selected sample metrics"><h3>Summary of these eligible pairs</h3><div className="evidence-metric-grid"><Metric label="Pairs (N)" value={String(comparison.metrics.count)}/><Metric label="Mean residual (bias)" value={number(comparison.metrics.bias)} units={comparison.units}/><Metric label="Root mean square error" value={number(comparison.metrics.rmse)} units={comparison.units}/><Metric label="Mean absolute error" value={number(comparison.metrics.mae)} units={comparison.units}/></div><p>These are unweighted summaries of this profile's accepted pairs. Adjacent depths are not independent samples. Agreement with an assimilating model is not independent validation, and these numbers do not establish forecast skill.</p></section>
      <details className="evidence-exclusions"><summary>Why {comparison.excluded_count} samples were excluded</summary>{comparison.excluded_count?<ul>{Object.entries(comparison.exclusion_counts).map(([code,n])=><li key={code}><strong>{n}</strong> {reasonLabel(code)}</li>)}</ul>:<p>Every source sample passes the current gates.</p>}<p>Each sample receives its first failed gate. Counts do not add the same sample twice. Use the source sample selector to inspect an excluded reading.</p></details>
      <section id="matching-sensitivity" className="evidence-sensitivity" aria-label="Matching sensitivity"><h3>Compare matching assumptions</h3><p>Keep this result, then change the rules to see which samples and summaries change. Save an investigation to keep both this reference and the current result.</p><button className="secondary-button" onClick={()=>setBaseline(comparison)}>Keep this result as reference</button>{baseline&&<div className="evidence-baseline"><h4>Reference: {kind[baseline.profile.instrument]} {baseline.profile.platform}, {title(baseline.settings.variable).toLowerCase()}</h4><p>{utc(baseline.model_time)} · {filterDescription(baseline.settings)}</p><p>{baseline.matched_count} eligible pairs · bias {number(baseline.metrics.bias)} {baseline.units} · RMSE {number(baseline.metrics.rmse)} {baseline.units}</p>{baseline.profile.id===comparison.profile.id&&baseline.settings.variable===comparison.settings.variable&&<p aria-label="Sensitivity count change">Current minus reference: <strong>{signed(comparison.matched_count-baseline.matched_count,0)} eligible pairs</strong>. Residual metrics describe each setting's own accepted samples.</p>}{baseline.profile.id===comparison.profile.id&&baseline.settings.variable===comparison.settings.variable&&<table className="sensitivity-table"><caption>Each column uses its own eligible samples. Units: {comparison.units}.</caption><thead><tr><th>Measure</th><th>Reference</th><th>Current</th></tr></thead><tbody><tr><th>Pairs</th><td>{baseline.matched_count}</td><td>{comparison.matched_count}</td></tr>{([['Bias','bias'],['RMSE','rmse'],['Mean absolute error','mae']] as const).map(([label,key])=><tr key={key}><th>{label}</th><td>{number(baseline.metrics[key])}</td><td>{number(comparison.metrics[key])}</td></tr>)}</tbody></table>}<div className="evidence-actions"><button className="secondary-button" onClick={restoreReference}>Restore reference settings</button><button className="secondary-button" onClick={()=>setBaseline(null)}>Clear reference</button></div></div>}</section>
      <details className="evidence-methods"><summary>Sources, scientific method and limitations</summary><p>{importSource?'This result uses the selected imported file. Original source bytes, declared mapping and QC are retained.':'This result uses the bundled observation library. Choose an imported profile to compare its file separately.'}</p>{safeSource(comparison.profile.source_url)&&<a href={safeSource(comparison.profile.source_url)} target="_blank" rel="noreferrer">Open observation source</a>}<p>Observation file: {comparison.profile.source_file}</p><p>Model: {manifest.case.source_label}</p><ul>{comparison.methods.map(m=><li key={m}>{m}</li>)}</ul><ul>{comparison.caveats.map(c=><li key={c}>{c.startsWith('Comparisons currently use the checked observation library.')?'This result uses the bundled observation library. To compare an imported file, select its profile.':c}</li>)}</ul><p>Method version: {comparison.method_version}</p><p className="evidence-hash">Model manifest SHA-256: {comparison.manifest_sha256}</p><p className="evidence-hash">Observation source SHA-256: {comparison.profile.source_sha256}</p><p className="evidence-hash">{importSource?'Imported file collection':'Observation library'} SHA-256: {comparison.observation_library_sha256}</p></details>
    </>:query.isError?<ErrorPanel error={query.error} onRetry={()=>void query.refetch()}/>:coverageQuery.isError?<ErrorPanel error={coverageQuery.error} onRetry={()=>void coverageQuery.refetch()}/>:null)}
    <p className="comparison-footnote">Historical model analysis and observations have separate timestamps. Coverage describes these checked samples under the stated rules, not a calibrated confidence score.</p>
  </section>;
}
function Metric({label,value,units}:{label:string;value:string;units?:string}){return <div><span>{label}</span><strong>{value}</strong>{units&&<small>{units}</small>}</div>;}
function ErrorPanel({error,onRetry}:{error:Error;onRetry:()=>void}){return <div className="evidence-error" role="alert"><p>{error.message}</p><button className="secondary-button" onClick={onRetry}><RefreshCw size={15}/>Retry comparison</button></div>;}
