import {useEffect,useRef,useState} from 'react';
import {appVersion} from './contracts';
export type Publication={schema_version:'1';app_version:string;serving:null|{publication_id:string;checked_at:string;cases:{id:string;title:string;time_start:string;time_end:string;sources:{title:string;retrieved_at:string}[]}[]};refresh:{state:string;message:string;checked_at?:string;restart_required?:boolean}};
export function PublicationStatus({expanded=false,requestId=0,onChecked,onError}:{expanded?:boolean;requestId?:number;onChecked?:(data:Publication|undefined)=>void;onError?:(error:string)=>void}){
 const [data,setData]=useState<Publication>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState('');
 const running=useRef<AbortController|null>(null),generation=useRef(0);
 const details=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{if(expanded&&details.current)details.current.open=true;},[expanded]);
 useEffect(()=>onChecked?.(data),[data,onChecked]);
 useEffect(()=>onError?.(error),[error,onError]);
 useEffect(()=>{if(requestId)void check();},[requestId]);
 useEffect(()=>()=>{generation.current++;running.current?.abort();},[]);
 async function check(){const g=++generation.current,c=new AbortController();running.current?.abort();running.current=c;setBusy(true);setError('');let timeout=false;const timer=setTimeout(()=>{timeout=true;c.abort();},15000);
  try{const r=await fetch('/api/publication',{signal:c.signal,cache:'no-store'});if(r.headers.get('X-Ocean-App-Version')!==appVersion)throw Error('The application was updated. Reload to use the new publication.');if(!r.ok)throw Error('Publication status could not be reached. Current views are kept.');const p:Publication=await r.json();if(p.schema_version!=='1'||p.app_version!==appVersion||typeof p.refresh?.message!=='string'||(p.serving&&(!Array.isArray(p.serving.cases)||!Number.isFinite(Date.parse(p.serving.checked_at)))))throw Error('Publication status could not be verified.');if(g!==generation.current)return;setData(p);setChecked(new Date().toLocaleString());}
  catch(e){if(g===generation.current)setError(timeout?'Status check timed out. Last checked information is kept.':e instanceof Error?e.message:'Status unavailable.');}finally{clearTimeout(timer);if(g===generation.current)setBusy(false);}}
 return <details ref={details} className="source-entry publication-status" onToggle={e=>{if(e.currentTarget.open&&!data&&!busy&&!requestId)void check();}}><summary>Data publication and updates</summary><p>Checks the published release. Historical cases do not become live conditions when refreshed.</p><button className="secondary-button" disabled={busy} onClick={()=>void check()}>Check publication</button>{busy&&<><p role="status">Checking the serving release...</p><button className="secondary-button" onClick={()=>{generation.current++;running.current?.abort();setBusy(false);setError('Status check cancelled. Last checked information is kept.');}}>Cancel status check</button></>}{error&&<p role="alert">{error}</p>}{data&&<><p>Last checked on this device: {checked}</p><p>{data.refresh.message}</p>{data.refresh.restart_required&&<p>A newer prepared release is waiting for the server to restart. This process keeps its existing data.</p>}{data.serving?<><p>Publication checked: {new Date(data.serving.checked_at).toLocaleString()}<br/>Release {data.serving.publication_id.slice(0,12)} | App {data.app_version}</p><details><summary>Published dates and source retrieval</summary>{data.serving.cases.map(c=><div key={c.id}><strong>{c.title}</strong><p>{c.time_start} to {c.time_end}</p>{c.sources.map((s,i)=><p key={i}>{s.title}: retrieved {s.retrieved_at}</p>)}</div>)}</details></>:<p>No publication manifest is configured in this local installation.</p>}</>}<p>Publishing new data is a maintainer operation. Failed candidates retain the previous publication. No public refresh job or external scheduler is configured.</p></details>;
}
